<a href="https://colab.research.google.com/github/Sarah-0405/Cold_Spots_Bayern/blob/main/KNN_Gi_Cold_Spot_Berechnungen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dieses Notebook berechnet eine KNN-Matrix sowie Gi*-Klassifizierung in Cold Spots, Hot Spots, Neutral Spots für
- jede Stadt über 50.000 EW der Jahre 2019-2024 einzeln (funktioniert bisher noch nicht, zu wenig RAM-Speicher)
- **jede Stadt über 50.000 EW im Gesamtzeitraum 2019-2024** (ab Kapitel "KNN für Mittelwert aller Sommer")
    - dafür wird zuerst ein gemeinsamer gdf erstellt, der für jeden Pixel den Durchschnitts-LST-Wert aller Sommerszenen von 2019-2024 speichert (in drive: averaged_lst_per_pixel_allyears.geojson)
    - daraus werden dann lokale gdf pro Stadt erstellt und auf Basis dessen für jede Stadt eine KNN-Matrix (drive Ordner: Cold Spots Bayern > knn_weights_averaged, jede Stadt einzeln gespeichert)
    - für **Gi*-Analyse** wird jede Stadt in mehreren Chunks verarbeitet, dafür werden Gitterzellen erstellt, die dann nacheinander verarbeitet werden
      - die Gitterzellen werden mit den lokalen gdfs der LST-Mittelwerte jeder Stadt gejoined und Gi* Analyse durchgeführt Drive ordner: Cold Spots Bayern > gi_results_chunked (Ergebnisse der einzelnen chunks vorher wieder zusammengefügt zu gesamtem Stadtgebiet))

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install geemap
!pip install geopandas
!pip install geopy
!pip install folium
!pip install matplotlib
!pip install numpy
!pip install pandas
!pip install rasterio
!pip install seaborn
!pip install shapely
!pip install sklearn
!pip install pysal

Requirement already satisfied: geemap in /usr/local/lib/python3.11/dist-packages (0.35.3)
Requirement already satisfied: bqplot in /usr/local/lib/python3.11/dist-packages (from geemap) (0.12.45)
Requirement already satisfied: colour in /usr/local/lib/python3.11/dist-packages (from geemap) (0.1.5)
Requirement already satisfied: earthengine-api>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from geemap) (1.5.23)
Requirement already satisfied: eerepr>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from geemap) (0.1.2)
Requirement already satisfied: folium>=0.17.0 in /usr/local/lib/python3.11/dist-packages (from geemap) (0.19.7)
Requirement already satisfied: geocoder in /usr/local/lib/python3.11/dist-packages (from geemap) (1.38.1)
Requirement already satisfied: ipyevents in /usr/local/lib/python3.11/dist-packages (from geemap) (2.0.2)
Requirement already satisfied: ipyfilechooser>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from geemap) (0.6.0)
Requirement already satisfied: ipyleaflet>=0.19.2 in /usr/local/lib/python3.11/dist-packages (from geemap) (0.20.0)
Requirement already satisfied: ipytree in /usr/local/lib/python3.11/dist-packages (from geemap) (0.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from geemap) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from geemap) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from geemap) (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (from geemap) (5.24.1)
Requirement already satisfied: pyperclip in /usr/local/lib/python3.11/dist-packages (from geemap) (1.9.0)
Requirement already satisfied: pyshp>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from geemap) (2.3.1)
Requirement already satisfied: python-box in /usr/local/lib/python3.11/dist-packages (from geemap) (7.3.2)
Requirement already satisfied: scooby in /usr/local/lib/python3.11/dist-packages (from geemap) (0.10.1)
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.11/dist-packages (from earthengine-api>=1.0.0->geemap) (2.19.0)
Requirement already satisfied: google-api-python-client>=1.12.1 in /usr/local/lib/python3.11/dist-packages (from earthengine-api>=1.0.0->geemap) (2.176.0)
Requirement already satisfied: google-auth>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from earthengine-api>=1.0.0->geemap) (2.38.0)
Requirement already satisfied: google-auth-httplib2>=0.0.3 in /usr/local/lib/python3.11/dist-packages (from earthengine-api>=1.0.0->geemap) (0.2.0)
Requirement already satisfied: httplib2<1dev,>=0.9.2 in /usr/local/lib/python3.11/dist-packages (from earthengine-api>=1.0.0->geemap) (0.22.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from earthengine-api>=1.0.0->geemap) (2.32.3)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from folium>=0.17.0->geemap) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.11/dist-packages (from folium>=0.17.0->geemap) (3.1.6)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.11/dist-packages (from folium>=0.17.0->geemap) (2025.4.0)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.11/dist-packages (from ipyfilechooser>=0.6.0->geemap) (7.7.1)
Requirement already satisfied: jupyter-leaflet<0.21,>=0.20 in /usr/local/lib/python3.11/dist-packages (from ipyleaflet>=0.19.2->geemap) (0.20.0)
Requirement already satisfied: traittypes<3,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from ipyleaflet>=0.19.2->geemap) (0.2.1)
Requirement already satisfied: traitlets>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from bqplot->geemap) (5.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->geemap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->geemap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->geemap) (2025.2)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from geocoder->geemap) (8.2.1)
Requirement already satisfied: future in /usr/local/lib/python3.11/dist-packages (from geocoder->geemap) (1.0.0)
Requirement already satisfied: ratelim in /usr/local/lib/python3.11/dist-packages (from geocoder->geemap) (0.1.6)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from geocoder->geemap) (1.17.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->geemap) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->geemap) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->geemap) (4.58.5)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->geemap) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->geemap) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->geemap) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->geemap) (3.2.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly->geemap) (8.5.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.12.1->earthengine-api>=1.0.0->geemap) (2.25.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.12.1->earthengine-api>=1.0.0->geemap) (4.2.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.4.1->earthengine-api>=1.0.0->geemap) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.4.1->earthengine-api>=1.0.0->geemap) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.4.1->earthengine-api>=1.0.0->geemap) (4.9.1)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.11/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.11/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.11/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.6.10)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (7.34.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.0.15)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2>=2.9->folium>=0.17.0->geemap) (3.0.2)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage->earthengine-api>=1.0.0->geemap) (2.4.3)
Requirement already satisfied: google-resumable-media>=2.7.2 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage->earthengine-api>=1.0.0->geemap) (2.7.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage->earthengine-api>=1.0.0->geemap) (1.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->earthengine-api>=1.0.0->geemap) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->earthengine-api>=1.0.0->geemap) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->earthengine-api>=1.0.0->geemap) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->earthengine-api>=1.0.0->geemap) (2025.7.9)
Requirement already satisfied: decorator in /usr/local/lib/python3.11/dist-packages (from ratelim->geocoder->geemap) (4.4.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.12.1->earthengine-api>=1.0.0->geemap) (1.70.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /usr/local/lib/python3.11/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.12.1->earthengine-api>=1.0.0->geemap) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.12.1->earthengine-api>=1.0.0->geemap) (1.26.1)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.8.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.1.12)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.1.7)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (24.0.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.11/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.4.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.11/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (75.2.0)
Collecting jedi>=0.16 (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.11/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.0.51)
Requirement already satisfied: pygments in /usr/local/lib/python3.11/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.11/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.11/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.9.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->earthengine-api>=1.0.0->geemap) (0.6.1)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.11/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.5.7)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.11/dist-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.8.4)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (5.8.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (25.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (7.16.6)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.22.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.11/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.3.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.11/dist-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.13)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.11/dist-packages (from jupyter-core>=4.6.0->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.3.8)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.11/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.13.4)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.11/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.2.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.11/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.21.1)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.11/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.24.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.11/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (21.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.4.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.26.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.11/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.16.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.14.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.22)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.9.0)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.11/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.8.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio>=3.1.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.3.1)

In [2]:
!pip install pysal

Collecting pysal
  Downloading pysal-25.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: beautifulsoup4>=4.10 in /usr/local/lib/python3.11/dist-packages (from pysal) (4.13.4)
Requirement already satisfied: geopandas>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from pysal) (1.0.1)
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.11/dist-packages (from pysal) (2.0.2)
Requirement already satisfied: packaging>=22 in /usr/local/lib/python3.11/dist-packages (from pysal) (25.0)
Requirement already satisfied: pandas>=1.4 in /usr/local/lib/python3.11/dist-packages (from pysal) (2.2.2)
Requirement already satisfied: platformdirs>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from pysal) (4.3.8)
Requirement already satisfied: requests>=2.27 in /usr/local/lib/python3.11/dist-packages (from pysal) (2.32.3)
Requirement already satisfied: scipy>=1.8 in /usr/local/lib/python3.11/dist-packages (from pysal) (1.15.3)
Requirement already satisfied: shapely>=2.0.1 in /usr/local/lib/python3.11/dist-packages (from pysal) (2.1.1)
Requirement already satisfied: scikit-learn>=1.1 in /usr/local/lib/python3.11/dist-packages (from pysal) (1.6.1)
Requirement already satisfied: libpysal>=4.12.1 in /usr/local/lib/python3.11/dist-packages (from pysal) (4.13.0)
Collecting access>=1.1.9 (from pysal)
  Downloading access-1.1.9-py3-none-any.whl.metadata (2.4 kB)
Collecting esda>=2.6.0 (from pysal)
  Downloading esda-2.7.1-py3-none-any.whl.metadata (2.0 kB)
Collecting giddy>=2.3.6 (from pysal)
  Downloading giddy-2.3.6-py3-none-any.whl.metadata (6.3 kB)
Collecting inequality>=1.1.1 (from pysal)
  Downloading inequality-1.1.2-py3-none-any.whl.metadata (3.9 kB)
Collecting pointpats>=2.5.1 (from pysal)
  Downloading pointpats-2.5.1-py3-none-any.whl.metadata (4.7 kB)
Collecting segregation>=2.5.1 (from pysal)
  Downloading segregation-2.5.2-py3-none-any.whl.metadata (2.2 kB)
Collecting spaghetti>=1.7.6 (from pysal)
  Downloading spaghetti-1.7.6-py3-none-any.whl.metadata (12 kB)
Collecting mgwr>=2.2.1 (from pysal)
  Downloading mgwr-2.2.1-py3-none-any.whl.metadata (1.5 kB)
Collecting momepy>=0.9.1 (from pysal)
  Downloading momepy-0.10.0-py3-none-any.whl.metadata (1.5 kB)
Collecting spglm>=1.1.0 (from pysal)
  Downloading spglm-1.1.0-py3-none-any.whl.metadata (3.9 kB)
Collecting spint>=1.0.7 (from pysal)
  Downloading spint-1.0.7.tar.gz (28 kB)
  Preparing metadata (setup.py) ... done
Collecting spreg>=1.8.1 (from pysal)
  Downloading spreg-1.8.3-py3-none-any.whl.metadata (1.7 kB)
Collecting tobler>=0.12.1 (from pysal)
  Downloading tobler-0.12.1-py3-none-any.whl.metadata (1.9 kB)
Collecting mapclassify>=2.8.1 (from pysal)
  Downloading mapclassify-2.10.0-py3-none-any.whl.metadata (3.1 kB)
Collecting splot>=1.1.7 (from pysal)
  Downloading splot-1.1.7-py3-none-any.whl.metadata (8.9 kB)
Collecting spopt>=0.6.1 (from pysal)
  Downloading spopt-0.7.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.10->pysal) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.10->pysal) (4.14.1)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.11/dist-packages (from geopandas>=0.10.0->pysal) (0.11.0)
Requirement already satisfied: pyproj>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from geopandas>=0.10.0->pysal) (3.7.1)
Collecting quantecon>=0.7 (from giddy>=2.3.6->pysal)
  Downloading quantecon-0.8.1-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.11/dist-packages (from inequality>=1.1.1->pysal) (3.10.0)
Requirement already satisfied: networkx>=3.2 in /usr/local/lib/python3.11/dist-packages (from mapclassify>=2.8.1->pysal) (3.5)
Requirement already satisfied: tqdm>=4.65 in /usr/local/lib/python3.11/dist-packages (from momepy>=0.9.1->pysal) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->pysal) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->pysal) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->pysal) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->pysal) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->pysal) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->pysal) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->pysal) (2025.7.14)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.1->pysal) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.1->pysal) (3.6.0)
Collecting deprecation (from segregation>=2.5.1->pysal)
  Downloading deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (from segregation>=2.5.1->pysal) (0.13.2)
Requirement already satisfied: numba in /usr/local/lib/python3.11/dist-packages (from segregation>=2.5.1->pysal) (0.60.0)
Collecting rtree>=1.0 (from spaghetti>=1.7.6->pysal)
  Downloading rtree-1.4.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting pulp>=2.8 (from spopt>=0.6.1->pysal)
  Downloading pulp-3.2.1-py3-none-any.whl.metadata (6.9 kB)
Collecting rasterio (from tobler>=0.12.1->pysal)
  Downloading rasterio-1.4.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.1 kB)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.11/dist-packages (from tobler>=0.12.1->pysal) (0.14.5)
Collecting rasterstats (from tobler>=0.12.1->pysal)
  Downloading rasterstats-0.20.0-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->inequality>=1.1.1->pysal) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->inequality>=1.1.1->pysal) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->inequality>=1.1.1->pysal) (4.58.5)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->inequality>=1.1.1->pysal) (1.4.8)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->inequality>=1.1.1->pysal) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.8->inequality>=1.1.1->pysal) (3.2.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4->pysal) (1.17.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from quantecon>=0.7->giddy>=2.3.6->pysal) (1.13.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba->segregation>=2.5.1->pysal) (0.43.0)
Collecting affine (from rasterio->tobler>=0.12.1->pysal)
  Downloading affine-2.4.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: attrs in /usr/local/lib/python3.11/dist-packages (from rasterio->tobler>=0.12.1->pysal) (25.3.0)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.11/dist-packages (from rasterio->tobler>=0.12.1->pysal) (8.2.1)
Collecting cligj>=0.5 (from rasterio->tobler>=0.12.1->pysal)
  Downloading cligj-0.7.2-py3-none-any.whl.metadata (5.0 kB)
Collecting click-plugins (from rasterio->tobler>=0.12.1->pysal)
  Downloading click_plugins-1.1.1.2-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting fiona (from rasterstats->tobler>=0.12.1->pysal)
  Downloading fiona-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.6/56.6 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: simplejson in /usr/local/lib/python3.11/dist-packages (from rasterstats->tobler>=0.12.1->pysal) (3.20.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels->tobler>=0.12.1->pysal) (1.0.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy->quantecon>=0.7->giddy>=2.3.6->pysal) (1.3.0)
Downloading pysal-25.1-py3-none-any.whl (17 kB)
Downloading access-1.1.9-py3-none-any.whl (21 kB)
Downloading esda-2.7.1-py3-none-any.whl (142 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.0/142.0 kB 2.8 MB/s eta 0:00:00
Downloading giddy-2.3.6-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 5.2 MB/s eta 0:00:00
Downloading inequality-1.1.2-py3-none-any.whl (21 kB)
Downloading mapclassify-2.10.0-py3-none-any.whl (882 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 882.2/882.2 kB 10.2 MB/s eta 0:00:00
Downloading mgwr-2.2.1-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.9/47.9 kB 3.7 MB/s eta 0:00:00
Downloading momepy-0.10.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 29.7 MB/s eta 0:00:00
Downloading pointpats-2.5.1-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 5.0 MB/s eta 0:00:00
Downloading segregation-2.5.2-py3-none-any.whl (141 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.6/141.6 kB 12.1 MB/s eta 0:00:00
Downloading spaghetti-1.7.6-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.9/53.9 kB 4.4 MB/s eta 0:00:00
Downloading spglm-1.1.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 kB 3.6 MB/s eta 0:00:00
Downloading splot-1.1.7-py3-none-any.whl (39 kB)
Downloading spopt-0.7.0-py3-none-any.whl (248 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.1/248.1 kB 19.0 MB/s eta 0:00:00
Downloading spreg-1.8.3-py3-none-any.whl (389 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.9/389.9 kB 26.7 MB/s eta 0:00:00
Downloading tobler-0.12.1-py3-none-any.whl (28 kB)
Downloading pulp-3.2.1-py3-none-any.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 60.8 MB/s eta 0:00:00
Downloading quantecon-0.8.1-py3-none-any.whl (322 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.8/322.8 kB 21.6 MB/s eta 0:00:00
Downloading rtree-1.4.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (541 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 541.1/541.1 kB 34.0 MB/s eta 0:00:00
Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Downloading rasterio-1.4.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (22.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.2/22.2 MB 65.6 MB/s eta 0:00:00
Downloading rasterstats-0.20.0-py3-none-any.whl (17 kB)
Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Downloading affine-2.4.0-py3-none-any.whl (15 kB)
Downloading click_plugins-1.1.1.2-py2.py3-none-any.whl (11 kB)
Downloading fiona-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 66.9 MB/s eta 0:00:00
Building wheels for collected packages: spint
  Building wheel for spint (setup.py) ... done
  Created wheel for spint: filename=spint-1.0.7-py3-none-any.whl size=31354 sha256=2ba7713dd510d656321f8a495f3a1f543460d63fea77c428fee4878de4a4f0d9
  Stored in directory: /root/.cache/pip/wheels/32/dc/2e/400caaa67e697355772a82b77b8c2ac7cd61633f595c477fd8
Successfully built spint
Installing collected packages: rtree, pulp, deprecation, cligj, click-plugins, affine, rasterio, quantecon, fiona, rasterstats, mapclassify, access, tobler, spreg, segregation, pointpats, momepy, inequality, esda, spglm, spaghetti, giddy, spopt, splot, spint, mgwr, pysal
Successfully installed access-1.1.9 affine-2.4.0 click-plugins-1.1.1.2 cligj-0.7.2 deprecation-2.1.0 esda-2.7.1 fiona-1.10.1 giddy-2.3.6 inequality-1.1.2 mapclassify-2.10.0 mgwr-2.2.1 momepy-0.10.0 pointpats-2.5.1 pulp-3.2.1 pysal-25.1 quantecon-0.8.1 rasterio-1.4.3 rasterstats-0.20.0 rtree-1.4.0 segregation-2.5.2 spaghetti-1.7.6 spglm-1.1.0 spint-1.0.7 splot-1.1.7 spopt-0.7.0 spreg-1.8.3 tobler-0.12.1

In [2]:
# Importieren Sie notwendige Bibliotheken
import ee
import geemap
import folium
from datetime import datetime
import geopandas as gpd
from shapely.geometry import mapping, Point
import pandas as pd
import matplotlib.pyplot as plt
import pysal.lib as ps
import pysal.explore as pe
from esda.getisord import G_Local
from libpysal.weights import KNN
from sklearn.preprocessing import StandardScaler
import numpy as np
import os

/usr/local/lib/python3.11/dist-packages/spaghetti/network.py:41: FutureWarning: The next major release of pysal/spaghetti (2.0.0) will drop support for all ``libpysal.cg`` geometries. This change is a first step in refactoring ``spaghetti`` that is expected to result in dramatically reduced runtimes for network instantiation and operations. Users currently requiring network and point pattern input as ``libpysal.cg`` geometries should prepare for this simply by converting to ``shapely`` geometries.
  warnings.warn(dep_msg, FutureWarning, stacklevel=1)

# KNN für Mittelwert aller Sommer

**KNN für Durchschnitt der Jahre 2019-2025** erstellen => erstmal gdfs Mittelwert der Jahre, dann KNN

In [ ]:
all_cities_summer_avg_lst_per_pixel = gpd.read_file("/content/drive/MyDrive/Cold Spots Bayern/all_cities_summer_avg_lst_per_pixel_allyears.geojson")
display(all_cities_summer_avg_lst_per_pixel.head())

In [ ]:
# 1. Gruppierung und Mittelwertbildung
# Gruppieren nach 'city' und 'geometry' und berechnen des Mittelwerts für 'avg_summer_LST_Celsius'
# Setzen Sie 'geometry' als Index, um die Gruppierung zu vereinfachen und dann zurückzusetzen
averaged_lst_per_pixel_per_city = all_cities_summer_avg_lst_per_pixel.set_index('geometry').groupby(['city', 'geometry'])['avg_summer_LST_Celsius'].mean().reset_index()

# Konvertieren Sie das Ergebnis zurück in ein GeoDataFrame
# Annahme: Das ursprüngliche CRS des GeoDataFrames ist bekannt oder kann von der ersten Zeile abgeleitet werden.
# Wenn das ursprüngliche CRS nicht bekannt ist, müssen Sie es hier explizit festlegen.
# Beispiel: original_crs = all_cities_summer_avg_lst_per_pixel.crs
# Wenn das CRS None ist und Sie wissen, dass es sich um WGS84 (EPSG:4326) handelt:
# original_crs = "EPSG:4326"

# Verwenden Sie das CRS des ursprünglichen GeoDataFrames
original_crs = all_cities_summer_avg_lst_per_pixel.crs

averaged_lst_per_pixel_per_city = gpd.GeoDataFrame(
    averaged_lst_per_pixel_per_city,
    geometry='geometry',
    crs=original_crs # Setzen Sie das CRS des ursprünglichen GeoDataFrames
)

print("Mittelwert der LST pro Pixel pro Stadt über alle Jahre berechnet.")
display(averaged_lst_per_pixel_per_city.head())

Mittelwert der LST pro Pixel pro Stadt über alle Jahre berechnet.

            city                  geometry  avg_summer_LST_Celsius
0  Aschaffenburg  POINT (9.23257 49.93527)               25.827932
1  Aschaffenburg     POINT (9.2355 49.935)               25.828958
2  Aschaffenburg   POINT (9.2355 49.93527)               25.846390
3  Aschaffenburg    POINT (9.23591 49.935)               25.713771
4  Aschaffenburg  POINT (9.23591 49.93527)               25.751711

## Geodataframe 2019-2024 Durchschnitt speichern

In [ ]:
# Definieren Sie den Pfad zum Speichern der Datei in Google Drive
# Passen Sie den Ordner und Dateinamen bei Bedarf an
output_path_averaged_gdf = "/content/drive/MyDrive/Cold Spots Bayern/averaged_lst_per_pixel_per_city_allyears.geojson"

try:
    # Speichern Sie den GeoDataFrame als GeoJSON-Datei
    averaged_lst_per_pixel_per_city.to_file(output_path_averaged_gdf, driver='GeoJSON')
    print(f"GeoDataFrame mit gemittelten LST-Werten erfolgreich gespeichert unter: {output_path_averaged_gdf}")
except Exception as e:
    print(f"Fehler beim Speichern des GeoDataFrames: {e}")

GeoDataFrame mit gemittelten LST-Werten erfolgreich gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/averaged_lst_per_pixel_per_city_allyears.geojson

gespeicherten gdf laden und damit weiterarbeiten: enthält die Mittelwerte aller verfügbaren Sommerszenen 2019-2024

In [3]:
# Definieren Sie den Pfad, von dem die Datei geladen werden soll
# Stellen Sie sicher, dass dies mit dem Pfad übereinstimmt, unter dem Sie die Datei gespeichert haben
input_path_averaged_gdf = "/content/drive/MyDrive/Cold Spots Bayern/averaged_lst_per_pixel_per_city_allyears.geojson"

try:
    # Laden Sie den GeoDataFrame aus der GeoJSON-Datei
    loaded_averaged_lst_gdf = gpd.read_file(input_path_averaged_gdf)
    print(f"GeoDataFrame erfolgreich geladen von: {input_path_averaged_gdf}")
    print(f"Anzahl der Einträge im geladenen GeoDataFrame: {len(loaded_averaged_lst_gdf)}")
    display(loaded_averaged_lst_gdf.head())

except Exception as e:
    print(f"Fehler beim Laden des GeoDataFrames von {input_path_averaged_gdf}: {e}")
    print("Bitte überprüfen Sie den Dateipfad und stellen Sie sicher, dass die Datei existiert.")

# Nun können Sie mit 'loaded_averaged_lst_gdf' weiterarbeiten
# Zum Beispiel können Sie es in city_averaged_gdfs aufteilen oder direkt verwenden
# loaded_averaged_lst_gdf sollte die gleiche Struktur wie 'averaged_lst_per_pixel_per_city' haben

GeoDataFrame erfolgreich geladen von: /content/drive/MyDrive/Cold Spots Bayern/averaged_lst_per_pixel_per_city_allyears.geojson
Anzahl der Einträge im geladenen GeoDataFrame: 1992069

            city  avg_summer_LST_Celsius                  geometry
0  Aschaffenburg               25.827932  POINT (9.23257 49.93527)
1  Aschaffenburg               25.828958     POINT (9.2355 49.935)
2  Aschaffenburg               25.846390   POINT (9.2355 49.93527)
3  Aschaffenburg               25.713771    POINT (9.23591 49.935)
4  Aschaffenburg               25.751711  POINT (9.23591 49.93527)

In [4]:
# 2. Erstellung stadtspezifischer GeoDataFrames
# Dictionary zum Speichern der stadtspezifischen GeoDataFrames mit gemittelten Werten
city_averaged_gdfs = {}

unique_cities_averaged = loaded_averaged_lst_gdf['city'].unique()
print(f"\nEindeutige Städte im gemittelten GeoDataFrame: {list(unique_cities_averaged)}")


print("\nErstelle stadtspezifische GeoDataFrames mit gemittelten LST-Werten...")

for city in unique_cities_averaged:
    print(f"  Erstelle GeoDataFrame für Stadt: {city}...")
    gdf_city_averaged = loaded_averaged_lst_gdf[
        loaded_averaged_lst_gdf['city'] == city
    ].copy() # Wichtig: Kopie erstellen

    if not gdf_city_averaged.empty:
        city_averaged_gdfs[city] = gdf_city_averaged
        print(f"    GeoDataFrame für {city} erstellt mit {len(gdf_city_averaged)} Pixeln.")
    else:
        print(f"    Keine gemittelten Daten für Stadt {city} gefunden.")

print("\nStadtspezifische GeoDataFrames mit gemittelten LST-Werten erstellt.")

# Jetzt haben Sie ein Dictionary 'city_averaged_gdfs', das für jede Stadt einen GeoDataFrame
# mit den gemittelten LST-Werten pro Pixel über alle Jahre enthält.
# Beispiel: city_averaged_gdfs['Munich'] gibt den GeoDataFrame für München mit gemittelten LST-Werten zurück.

Eindeutige Städte im gemittelten GeoDataFrame: ['Aschaffenburg', 'Augsburg', 'Bamberg', 'Bayreuth', 'Erlangen', 'Fürth', 'Ingolstadt', 'Kempten (Allgäu)', 'Landshut', 'Munich', 'Nuremberg', 'Passau', 'Regensburg', 'Rosenheim', 'Schweinfurt', 'Würzburg']

Erstelle stadtspezifische GeoDataFrames mit gemittelten LST-Werten...
  Erstelle GeoDataFrame für Stadt: Aschaffenburg...
    GeoDataFrame für Aschaffenburg erstellt mit 69391 Pixeln.
  Erstelle GeoDataFrame für Stadt: Augsburg...
    GeoDataFrame für Augsburg erstellt mit 164425 Pixeln.
  Erstelle GeoDataFrame für Stadt: Bamberg...
    GeoDataFrame für Bamberg erstellt mit 121604 Pixeln.
  Erstelle GeoDataFrame für Stadt: Bayreuth...
    GeoDataFrame für Bayreuth erstellt mit 149925 Pixeln.
  Erstelle GeoDataFrame für Stadt: Erlangen...
    GeoDataFrame für Erlangen erstellt mit 80705 Pixeln.
  Erstelle GeoDataFrame für Stadt: Fürth...
    GeoDataFrame für Fürth erstellt mit 60360 Pixeln.
  Erstelle GeoDataFrame für Stadt: Ingolstadt...
    GeoDataFrame für Ingolstadt erstellt mit 150379 Pixeln.
  Erstelle GeoDataFrame für Stadt: Kempten (Allgäu)...
    GeoDataFrame für Kempten (Allgäu) erstellt mit 67441 Pixeln.
  Erstelle GeoDataFrame für Stadt: Landshut...
    GeoDataFrame für Landshut erstellt mit 146398 Pixeln.
  Erstelle GeoDataFrame für Stadt: Munich...
    GeoDataFrame für Munich erstellt mit 349956 Pixeln.
  Erstelle GeoDataFrame für Stadt: Nuremberg...
    GeoDataFrame für Nuremberg erstellt mit 209693 Pixeln.
  Erstelle GeoDataFrame für Stadt: Passau...
    GeoDataFrame für Passau erstellt mit 77739 Pixeln.
  Erstelle GeoDataFrame für Stadt: Regensburg...
    GeoDataFrame für Regensburg erstellt mit 172599 Pixeln.
  Erstelle GeoDataFrame für Stadt: Rosenheim...
    GeoDataFrame für Rosenheim erstellt mit 42317 Pixeln.
  Erstelle GeoDataFrame für Stadt: Schweinfurt...
    GeoDataFrame für Schweinfurt erstellt mit 39886 Pixeln.
  Erstelle GeoDataFrame für Stadt: Würzburg...
    GeoDataFrame für Würzburg erstellt mit 89251 Pixeln.

Stadtspezifische GeoDataFrames mit gemittelten LST-Werten erstellt.

In [ ]:
# 3. KNN-Matrix Berechnung pro Stadt
# Dictionary zum Speichern der KNN-Gewichtsmatrizen für jede Stadt
city_knn_weights_averaged = {}

# Definieren Sie die Anzahl der Nachbarn für KNN
k_neighbors = 12 # Sie können diesen Wert anpassen

print(f"\nBerechne KNN-Gewichtsmatrizen (k={k_neighbors}) für jede Stadt basierend auf gemittelten LST-Werten...")

# Schleife über die stadtspezifischen GeoDataFrames
for city, gdf_city_averaged in city_averaged_gdfs.items():
    print(f"\n✨ Verarbeite Stadt: {city}...")

    # Stellen Sie sicher, dass genügend Punkte für die KNN-Analyse vorhanden sind
    min_points_for_knn = k_neighbors + 1
    if not gdf_city_averaged.empty and len(gdf_city_averaged) >= min_points_for_knn:
        # Extrahieren Sie die Koordinaten
        # Konvertiere in ein metrisches CRS vor der KNN-Berechnung, wenn es noch nicht projiziert ist
        gdf_city_spatial = gdf_city_averaged.copy() # Kopie erstellen
        if gdf_city_spatial.crs is None or gdf_city_spatial.crs.is_geographic:
             # Für Bayern ist EPSG:25832 (ETRS89 / UTM zone 32N) oft passend.
             try:
                 print(f"    Konvertiere Daten für {city} nach EPSG:25832 (UTM 32N) für metrische Distanzen.")
                 gdf_city_spatial = gdf_city_spatial.to_crs(epsg=25832)
             except Exception as crs_e:
                 print(f"    Fehler bei der CRS-Konvertierung für {city}: {crs_e}. Versuche es ohne Konvertierung, Ergebnisse könnten ungenau sein.")
                 pass # Geht weiter mit den ursprünglichen Koordinaten

        coords = np.array(list(zip(gdf_city_spatial.geometry.x, gdf_city_spatial.geometry.y)))

        # Berechne die KNN-Matrix
        try:
            w_city_averaged = KNN.from_array(coords, k=k_neighbors)
            w_city_averaged.transform = 'R' # Zeilenstandardisierung anwenden

            # Prüfen auf Konnektivität
            if w_city_averaged.n_components > 1:
                 print(f"    Warnung: Gewichtsmatrix für {city} ist nicht vollständig verbunden ({w_city_averaged.n_components} Komponenten).")

            # Speichere die Gewichtsmatrix im Dictionary
            city_knn_weights_averaged[city] = w_city_averaged
            print(f"    KNN-Matrix für {city} erfolgreich berechnet.")

        except Exception as knn_e:
            print(f"    Fehler bei der KNN-Berechnung für {city}: {knn_e}. Überspringe diese Stadt.")


    else:
        print(f"  Nicht genügend Daten ({len(gdf_city_averaged)} Punkte) für KNN-Berechnung für {city}. Benötigt mindestens {min_points_for_knn} Punkte. Überspringe.")


print("\nKNN-Berechnung für alle Städte (basierend auf gemittelten LST-Werten) abgeschlossen.")

# Das Dictionary 'city_knn_weights_averaged' enthält nun die KNN-Matrizen
# für jede Stadt, basierend auf den über die Jahre gemittelten LST-Werten pro Pixel.
# Beispiel: city_knn_weights_averaged['Munich'] gibt die KNN-Matrix für München zurück.

Berechne KNN-Gewichtsmatrizen (k=12) für jede Stadt basierend auf gemittelten LST-Werten...

✨ Verarbeite Stadt: Aschaffenburg...
    Konvertiere Daten für Aschaffenburg nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Aschaffenburg erfolgreich berechnet.

✨ Verarbeite Stadt: Augsburg...
    Konvertiere Daten für Augsburg nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Augsburg erfolgreich berechnet.

✨ Verarbeite Stadt: Bamberg...
    Konvertiere Daten für Bamberg nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Bamberg erfolgreich berechnet.

✨ Verarbeite Stadt: Bayreuth...
    Konvertiere Daten für Bayreuth nach EPSG:25832 (UTM 32N) für metrische Distanzen.

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

    Warnung: Gewichtsmatrix für Bayreuth ist nicht vollständig verbunden (2 Komponenten).
    KNN-Matrix für Bayreuth erfolgreich berechnet.

✨ Verarbeite Stadt: Erlangen...
    Konvertiere Daten für Erlangen nach EPSG:25832 (UTM 32N) für metrische Distanzen.

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 10 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

    Warnung: Gewichtsmatrix für Erlangen ist nicht vollständig verbunden (10 Komponenten).
    KNN-Matrix für Erlangen erfolgreich berechnet.

✨ Verarbeite Stadt: Fürth...
    Konvertiere Daten für Fürth nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Fürth erfolgreich berechnet.

✨ Verarbeite Stadt: Ingolstadt...
    Konvertiere Daten für Ingolstadt nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Ingolstadt erfolgreich berechnet.

✨ Verarbeite Stadt: Kempten (Allgäu)...
    Konvertiere Daten für Kempten (Allgäu) nach EPSG:25832 (UTM 32N) für metrische Distanzen.

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

    Warnung: Gewichtsmatrix für Kempten (Allgäu) ist nicht vollständig verbunden (3 Komponenten).
    KNN-Matrix für Kempten (Allgäu) erfolgreich berechnet.

✨ Verarbeite Stadt: Landshut...
    Konvertiere Daten für Landshut nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Landshut erfolgreich berechnet.

✨ Verarbeite Stadt: Munich...
    Konvertiere Daten für Munich nach EPSG:25832 (UTM 32N) für metrische Distanzen.

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

    Warnung: Gewichtsmatrix für Munich ist nicht vollständig verbunden (3 Komponenten).
    KNN-Matrix für Munich erfolgreich berechnet.

✨ Verarbeite Stadt: Nuremberg...
    Konvertiere Daten für Nuremberg nach EPSG:25832 (UTM 32N) für metrische Distanzen.

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

    Warnung: Gewichtsmatrix für Nuremberg ist nicht vollständig verbunden (2 Komponenten).
    KNN-Matrix für Nuremberg erfolgreich berechnet.

✨ Verarbeite Stadt: Passau...
    Konvertiere Daten für Passau nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Passau erfolgreich berechnet.

✨ Verarbeite Stadt: Regensburg...
    Konvertiere Daten für Regensburg nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Regensburg erfolgreich berechnet.

✨ Verarbeite Stadt: Rosenheim...
    Konvertiere Daten für Rosenheim nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Rosenheim erfolgreich berechnet.

✨ Verarbeite Stadt: Schweinfurt...
    Konvertiere Daten für Schweinfurt nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Schweinfurt erfolgreich berechnet.

✨ Verarbeite Stadt: Würzburg...
    Konvertiere Daten für Würzburg nach EPSG:25832 (UTM 32N) für metrische Distanzen.
    KNN-Matrix für Würzburg erfolgreich berechnet.

KNN-Berechnung für alle Städte (basierend auf gemittelten LST-Werten) abgeschlossen.

### KNN-Gewichtsmatrizen speichern

Dieser Code speichert jede KNN-Gewichtsmatrix aus dem `city_knn_weights_averaged` Dictionary als separate Datei.

In [ ]:
import os
import libpysal as ps # libpysal wird zum Speichern benötigt

# Definieren Sie den Ordner, in dem die Gewichtsmatrizen gespeichert werden sollen
# Passen Sie diesen Pfad bei Bedarf an, idealerweise in Ihrem Google Drive
output_weights_folder = "/content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/"
os.makedirs(output_weights_folder, exist_ok=True) # Erstellt den Ordner, falls er nicht existiert

print(f"Speichere KNN-Gewichtsmatrizen im Ordner: {output_weights_folder}")

# Schleife über das Dictionary und speichern Sie jede Gewichtsmatrix
for city, w_matrix in city_knn_weights_averaged.items():
    if w_matrix is not None:
        # Erstellen Sie einen Dateinamen basierend auf dem Stadtnamen
        # Verwenden Sie ein Format, das von libpysal unterstützt wird, z.B. .gal oder .gwt
        # Für KNN ist .gwt (General Weights format) oft passend, aber .gal funktioniert auch oft.
        # Wir verwenden hier .gal als Beispiel.
        file_name = f"{city.replace(' ', '_')}_knn_averaged.gal"
        file_path = os.path.join(output_weights_folder, file_name)

        try:
            # Speichern Sie die Gewichtsmatrix mit libpysal.io.open()
            # Verwenden Sie nicht den context manager (with), da GalIO ihn nicht unterstützt
            f = ps.io.open(file_path, mode='w')
            f.write(w_matrix)
            f.close() # Datei explizit schließen

            print(f"  Gewichtsmatrix für {city} gespeichert unter: {file_path}")
        except Exception as e:
            print(f"  Fehler beim Speichern der Gewichtsmatrix für {city}: {e}")
    else:
        print(f"  Keine Gewichtsmatrix für {city} verfügbar zum Speichern.")

print("\nSpeichern der KNN-Gewichtsmatrizen abgeschlossen.")

Speichere KNN-Gewichtsmatrizen im Ordner: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/
  Gewichtsmatrix für Aschaffenburg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Aschaffenburg_knn_averaged.gal
  Gewichtsmatrix für Augsburg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Augsburg_knn_averaged.gal
  Gewichtsmatrix für Bamberg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Bamberg_knn_averaged.gal
  Gewichtsmatrix für Bayreuth gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Bayreuth_knn_averaged.gal
  Gewichtsmatrix für Erlangen gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Erlangen_knn_averaged.gal
  Gewichtsmatrix für Fürth gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Fürth_knn_averaged.gal
  Gewichtsmatrix für Ingolstadt gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Ingolstadt_knn_averaged.gal
  Gewichtsmatrix für Kempten (Allgäu) gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Kempten_(Allgäu)_knn_averaged.gal
  Gewichtsmatrix für Landshut gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Landshut_knn_averaged.gal
  Gewichtsmatrix für Munich gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Munich_knn_averaged.gal
  Gewichtsmatrix für Nuremberg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Nuremberg_knn_averaged.gal
  Gewichtsmatrix für Passau gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Passau_knn_averaged.gal
  Gewichtsmatrix für Regensburg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Regensburg_knn_averaged.gal
  Gewichtsmatrix für Rosenheim gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Rosenheim_knn_averaged.gal
  Gewichtsmatrix für Schweinfurt gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Schweinfurt_knn_averaged.gal
  Gewichtsmatrix für Würzburg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/Würzburg_knn_averaged.gal

Speichern der KNN-Gewichtsmatrizen abgeschlossen.

### KNN-Gewichtsmatrizen laden

Dieser Code lädt die zuvor gespeicherten KNN-Gewichtsmatrizen wieder in ein Dictionary.

In [ ]:
import os
import libpysal as ps # libpysal wird zum Laden benötigt

# Definieren Sie den Ordner, aus dem die Gewichtsmatrizen geladen werden sollen
input_weights_folder = "/content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/"

# Dictionary zum Speichern der geladenen Gewichtsmatrizen
loaded_city_knn_weights_averaged = {}

print(f"Lade KNN-Gewichtsmatrizen aus dem Ordner: {input_weights_folder}")

# Holen Sie sich eine Liste aller Gewichtsmatrizen-Dateien im Ordner
weight_files = [f for f in os.listdir(input_weights_folder) if f.endswith(".gal")] # Passen Sie die Dateiendung an, falls Sie ein anderes Format verwendet haben

# Schleife über die Dateien und laden Sie jede Gewichtsmatrix
for file_name in weight_files:
    file_path = os.path.join(input_weights_folder, file_name)
    # Extrahiere den Stadtnamen aus dem Dateinamen
    city_name = file_name.replace("_knn_averaged.gal", "").replace("_", " ") # Passen Sie dies an Ihren Dateinamen an

    try:
        # Laden Sie die Gewichtsmatrix
        w_matrix = ps.io.open(file_path, mode='r').read()
        # Wenn die Matrix zeilenstandardisiert war beim Speichern, bleibt sie das beim Laden.
        # Stellen Sie sicher, dass die Transformation korrekt ist, falls notwendig.
        # w_matrix.transform = 'R' # Optional: Zeilenstandardisierung erneut anwenden, falls nicht erhalten

        # Speichere die geladene Gewichtsmatrix im Dictionary
        loaded_city_knn_weights_averaged[city_name] = w_matrix
        print(f"  Gewichtsmatrix für {city_name} erfolgreich geladen.")
    except Exception as e:
        print(f"  Fehler beim Laden der Gewichtsmatrix aus {file_path}: {e}")

print("\nLaden der KNN-Gewichtsmatrizen abgeschlossen.")

# Das Dictionary 'loaded_city_knn_weights_averaged' enthält nun die geladenen Gewichtsmatrizen.
# Sie können dieses Dictionary anstelle von 'city_knn_weights_averaged' in Ihrer Gi* Analyse verwenden.

Lade KNN-Gewichtsmatrizen aus dem Ordner: /content/drive/MyDrive/Cold Spots Bayern/knn_weights_averaged/
  Gewichtsmatrix für Fürth erfolgreich geladen.
  Gewichtsmatrix für Bamberg erfolgreich geladen.

/usr/local/lib/python3.11/dist-packages/libpysal/io/iohandlers/gal.py:185: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  w = W(neighbors, id_order=ids)

  Gewichtsmatrix für Kempten (Allgäu) erfolgreich geladen.

/usr/local/lib/python3.11/dist-packages/libpysal/io/iohandlers/gal.py:185: UserWarning: The weights matrix is not fully connected:
 There are 10 disconnected components.
  w = W(neighbors, id_order=ids)

  Gewichtsmatrix für Erlangen erfolgreich geladen.
  Gewichtsmatrix für Aschaffenburg erfolgreich geladen.
  Gewichtsmatrix für Ingolstadt erfolgreich geladen.
  Gewichtsmatrix für Landshut erfolgreich geladen.

/usr/local/lib/python3.11/dist-packages/libpysal/io/iohandlers/gal.py:185: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  w = W(neighbors, id_order=ids)

  Gewichtsmatrix für Bayreuth erfolgreich geladen.
  Gewichtsmatrix für Augsburg erfolgreich geladen.
  Gewichtsmatrix für Munich erfolgreich geladen.
  Gewichtsmatrix für Nuremberg erfolgreich geladen.
  Gewichtsmatrix für Passau erfolgreich geladen.
  Gewichtsmatrix für Rosenheim erfolgreich geladen.
  Gewichtsmatrix für Schweinfurt erfolgreich geladen.
  Gewichtsmatrix für Würzburg erfolgreich geladen.

4. **Ergebnisse speichern/anzeigen**:

Die gemittelten GeoDataFrames pro Stadt sind im Dictionary `city_averaged_gdfs` gespeichert.
Die KNN-Gewichtsmatrizen pro Stadt sind im Dictionary `city_knn_weights_averaged` gespeichert.

Sie können diese Ergebnisse nun speichern oder weiter analysieren (z.B. Gi* Statistik berechnen).

# Gi* Analyse

In [ ]:
from esda.getisord import G_Local

Test: nur für Aschaffenburg

In [ ]:
def calculate_hotspots(gdf, w):
    gdf = gdf.copy()  # Kopie, um das Original nicht zu ändern
    g = G_Local(gdf["avg_summer_LST_Celsius"], w)
    gdf["Gi*"] = g.Zs  # Standardisierte Z-Werte
    return gdf

# Hol dir die Daten für Aschaffenburg
gdf_aschaffenburg = city_averaged_gdfs["Aschaffenburg"]
w_aschaffenburg = loaded_city_knn_weights_averaged["Aschaffenburg"]

# Berechne Hotspots
gdf_aschaffenburg_result = calculate_hotspots(gdf_aschaffenburg, w_aschaffenburg)

# Ergebnisse anschauen
print(gdf_aschaffenburg_result.head())

            city  avg_summer_LST_Celsius                  geometry       Gi*
0  Aschaffenburg               25.827932  POINT (9.23257 49.93527) -0.938972
1  Aschaffenburg               25.828958     POINT (9.2355 49.935) -1.077372
2  Aschaffenburg               25.846390   POINT (9.2355 49.93527) -1.221513
3  Aschaffenburg               25.713771    POINT (9.23591 49.935) -1.064959
4  Aschaffenburg               25.751711  POINT (9.23591 49.93527) -1.237013

In [ ]:
def calculate_hotspots(gdf, w):
    gdf = gdf.copy()  # Original nicht verändern
    g = G_Local(gdf["avg_summer_LST_Celsius"], w)
    gdf["Gi*"] = g.Zs  # Standardisierte Z-Werte
    return gdf

# Ergebnisse für alle Städte berechnen
city_gi_results = {}

for city in city_averaged_gdfs.keys():
    print(f"✨ Berechne Gi* für: {city}")

    gdf = city_averaged_gdfs[city]
    w = loaded_city_knn_weights_averaged[city]

    # Berechne Hotspots
    result_gdf = calculate_hotspots(gdf, w)

    # Speichere das Ergebnis
    city_gi_results[city] = result_gdf

print("✅ Berechnung abgeschlossen.")

# Beispiel: Ergebnisse für Aschaffenburg ansehen
print(city_gi_results["Aschaffenburg"].head())

✨ Berechne Gi* für: Aschaffenburg
✨ Berechne Gi* für: Augsburg
✨ Berechne Gi* für: Bamberg
✨ Berechne Gi* für: Bayreuth
✨ Berechne Gi* für: Erlangen
✨ Berechne Gi* für: Fürth

KeyError: 'Fürth'

In [8]:
print("\n📋 Städte in city_averaged_gdfs:")
for c in sorted(city_averaged_gdfs.keys()):
    print(f"- {c}")

print("\n📋 Städte in loaded_city_knn_weights_averaged:")
for c in sorted(loaded_city_knn_weights_averaged.keys()):
    print(f"- {c}")

📋 Städte in city_averaged_gdfs:
- Aschaffenburg
- Augsburg
- Bamberg
- Bayreuth
- Erlangen
- Fürth
- Ingolstadt
- Kempten (Allgäu)
- Landshut
- Munich
- Nuremberg
- Passau
- Regensburg
- Rosenheim
- Schweinfurt
- Würzburg

📋 Städte in loaded_city_knn_weights_averaged:
- Aschaffenburg
- Augsburg
- Bamberg
- Bayreuth
- Erlangen
- Fürth
- Ingolstadt
- Kempten (Allgäu)
- Landshut
- Munich
- Nuremberg
- Passau
- Regensburg
- Rosenheim
- Schweinfurt
- Würzburg

In [ ]:
output_dir = "gi_star_results"
os.makedirs(output_dir, exist_ok=True)

def calculate_hotspots(gdf, w):
    gdf = gdf.copy()
    g = G_Local(gdf["avg_summer_LST_Celsius"], w)
    gdf["Gi*"] = g.Zs
    return gdf

cities_gdfs = set(city_averaged_gdfs.keys())
cities_weights = set(loaded_city_knn_weights_averaged.keys())

print("\n📋 Städte in city_averaged_gdfs:", sorted(cities_gdfs))
print("📋 Städte in loaded_city_knn_weights_averaged:", sorted(cities_weights))

for city in sorted(cities_gdfs):
    if city not in loaded_city_knn_weights_averaged:
        print(f"⚠️  Kein Gewicht für {city} gefunden — überspringe.")
        continue

    print(f"\n✨ Bearbeite {city}...")

    gdf = city_averaged_gdfs[city]
    w = loaded_city_knn_weights_averaged[city]

    # Gi* berechnen
    result_gdf = calculate_hotspots(gdf, w)

    out_path = os.path.join(output_dir, f"{city.replace(' ', '_')}.geojson")

    result_gdf.to_file(out_path, driver="GeoJSON")
    print(f"✅ Ergebnis für {city} gespeichert: {out_path}")

    # Speicher freigeben
    del result_gdf

📋 Städte in city_averaged_gdfs: ['Aschaffenburg', 'Augsburg', 'Bamberg', 'Bayreuth', 'Erlangen', 'Fürth', 'Ingolstadt', 'Kempten (Allgäu)', 'Landshut', 'Munich', 'Nuremberg', 'Passau', 'Regensburg', 'Rosenheim', 'Schweinfurt', 'Würzburg']
📋 Städte in loaded_city_knn_weights_averaged: ['Aschaffenburg', 'Augsburg', 'Bamberg', 'Bayreuth', 'Erlangen', 'Fürth', 'Ingolstadt', 'Kempten (Allgäu)', 'Landshut', 'Munich', 'Nuremberg', 'Passau', 'Regensburg', 'Rosenheim', 'Schweinfurt', 'Würzburg']

✨ Bearbeite Aschaffenburg...
✅ Ergebnis für Aschaffenburg gespeichert: gi_star_results/Aschaffenburg.geojson

✨ Bearbeite Augsburg...
✅ Ergebnis für Augsburg gespeichert: gi_star_results/Augsburg.geojson

✨ Bearbeite Bamberg...
✅ Ergebnis für Bamberg gespeichert: gi_star_results/Bamberg.geojson

✨ Bearbeite Bayreuth...

start city jetzt immer ab da wo vorherige Sitzung abgestürzt ist

In [ ]:
output_dir = "gi_star_results"
os.makedirs(output_dir, exist_ok=True)

def calculate_hotspots(gdf, w):
    gdf = gdf.copy()
    g = G_Local(gdf["avg_summer_LST_Celsius"], w)
    gdf["Gi*"] = g.Zs
    return gdf

cities_gdfs = sorted(city_averaged_gdfs.keys())
cities_weights = set(loaded_city_knn_weights_averaged.keys())

print("\n📋 Städte in city_averaged_gdfs:", cities_gdfs)
print("📋 Städte in loaded_city_knn_weights_averaged:", sorted(cities_weights))

# nur Städte >= "Bayreuth" (alphabetisch) nehmen
start_city = "Passau"
start_index = cities_gdfs.index(start_city)
cities_to_process = cities_gdfs[start_index:]

print(f"\n🚀 Starte Berechnung ab: {start_city}")

for city in cities_to_process:
    if city not in loaded_city_knn_weights_averaged:
        print(f"⚠️  Kein Gewicht für {city} gefunden — überspringe.")
        continue

    print(f"\n✨ Bearbeite {city}...")

    gdf = city_averaged_gdfs[city]
    w = loaded_city_knn_weights_averaged[city]

    # Gi* berechnen
    result_gdf = calculate_hotspots(gdf, w)

    out_path = os.path.join(output_dir, f"{city.replace(' ', '_')}.geojson")

    result_gdf.to_file(out_path, driver="GeoJSON")
    print(f"✅ Ergebnis für {city} gespeichert: {out_path}")

    # Speicher freigeben
    del result_gdf

📋 Städte in city_averaged_gdfs: ['Aschaffenburg', 'Augsburg', 'Bamberg', 'Bayreuth', 'Erlangen', 'Fürth', 'Ingolstadt', 'Kempten (Allgäu)', 'Landshut', 'Munich', 'Nuremberg', 'Passau', 'Regensburg', 'Rosenheim', 'Schweinfurt', 'Würzburg']
📋 Städte in loaded_city_knn_weights_averaged: ['Aschaffenburg', 'Augsburg', 'Bamberg', 'Bayreuth', 'Erlangen', 'Fürth', 'Ingolstadt', 'Kempten (Allgäu)', 'Landshut', 'Munich', 'Nuremberg', 'Passau', 'Regensburg', 'Rosenheim', 'Schweinfurt', 'Würzburg']

🚀 Starte Berechnung ab: Passau

✨ Bearbeite Passau...

## Cold und Hot Spots klassifizieren

## nach Cold Spots mit p<0,05 filtern

# Gi* Analyse mit räumlichen Chunks
Apply spatial chunking to perform the Gi* analysis for each city in the `loaded_averaged_lst_gdf` GeoDataFrame using the pre-calculated KNN weights in the `city_knn_weights_averaged` dictionary. Explain the process and provide the code.

Gi* Analyse wurde mit räumlichen chunks durchgeführt für Speichereffizienz, vorher leider immer abgestürzt

## Define a spatial grid

### Subtask:
Create a spatial grid that covers the extent of each city's GeoDataFrame.

**Reasoning**:
The first step is to iterate through the city_averaged_gdfs, get the bounds of each city's geodataframe and create a spatial grid covering the extent.

In [ ]:
from shapely.geometry import box
import math

city_grids = {}
grid_cell_size = 1000 # Define grid cell size in meters (assuming projected CRS)

for city, gdf in city_averaged_gdfs.items():
    print(f"Creating grid for {city}...")
    if gdf.crs is None or gdf.crs.is_geographic:
        # Convert to a projected CRS for accurate grid creation
        try:
            print(f"  Converting {city} to EPSG:25832 for grid creation.")
            gdf_projected = gdf.to_crs(epsg=25832)
        except Exception as crs_e:
            print(f"  Error converting CRS for {city}: {crs_e}. Skipping grid for this city.")
            continue
    else:
        gdf_projected = gdf.copy()

    bounds = gdf_projected.total_bounds
    minx, miny, maxx, maxy = bounds

    # Calculate the number of rows and columns needed for the grid
    n_cols = int(math.ceil((maxx - minx) / grid_cell_size))
    n_rows = int(math.ceil((maxy - miny) / grid_cell_size))

    # Create the grid of polygons
    grid_cells = []
    for i in range(n_cols):
        for j in range(n_rows):
            cell_minx = minx + i * grid_cell_size
            cell_miny = miny + j * grid_cell_size
            cell_maxx = minx + (i + 1) * grid_cell_size
            cell_maxy = miny + (j + 1) * grid_cell_size
            grid_cells.append(box(cell_minx, cell_miny, cell_maxx, cell_maxy))

    grid_gdf = gpd.GeoDataFrame(geometry=grid_cells, crs=gdf_projected.crs)
    city_grids[city] = grid_gdf
    print(f"  Grid created for {city} with {len(grid_gdf)} cells.")

print("\nGrids created for all cities.")

Creating grid for Aschaffenburg...
  Converting Aschaffenburg to EPSG:25832 for grid creation.
  Grid created for Aschaffenburg with 144 cells.
Creating grid for Augsburg...
  Converting Augsburg to EPSG:25832 for grid creation.
  Grid created for Augsburg with 345 cells.
Creating grid for Bamberg...
  Converting Bamberg to EPSG:25832 for grid creation.
  Grid created for Bamberg with 100 cells.
Creating grid for Bayreuth...
  Converting Bayreuth to EPSG:25832 for grid creation.
  Grid created for Bayreuth with 150 cells.
Creating grid for Erlangen...
  Converting Erlangen to EPSG:25832 for grid creation.
  Grid created for Erlangen with 130 cells.
Creating grid for Fürth...
  Converting Fürth to EPSG:25832 for grid creation.
  Grid created for Fürth with 96 cells.
Creating grid for Ingolstadt...
  Converting Ingolstadt to EPSG:25832 for grid creation.
  Grid created for Ingolstadt with 304 cells.
Creating grid for Kempten (Allgäu)...
  Converting Kempten (Allgäu) to EPSG:25832 for grid creation.
  Grid created for Kempten (Allgäu) with 110 cells.
Creating grid for Landshut...
  Converting Landshut to EPSG:25832 for grid creation.
  Grid created for Landshut with 220 cells.
Creating grid for Munich...
  Converting Munich to EPSG:25832 for grid creation.
  Grid created for Munich with 567 cells.
Creating grid for Nuremberg...
  Converting Nuremberg to EPSG:25832 for grid creation.
  Grid created for Nuremberg with 528 cells.
Creating grid for Passau...
  Converting Passau to EPSG:25832 for grid creation.
  Grid created for Passau with 128 cells.
Creating grid for Regensburg...
  Converting Regensburg to EPSG:25832 for grid creation.
  Grid created for Regensburg with 156 cells.
Creating grid for Rosenheim...
  Converting Rosenheim to EPSG:25832 for grid creation.
  Grid created for Rosenheim with 72 cells.
Creating grid for Schweinfurt...
  Converting Schweinfurt to EPSG:25832 for grid creation.
  Grid created for Schweinfurt with 80 cells.
Creating grid for Würzburg...
  Converting Würzburg to EPSG:25832 for grid creation.
  Grid created for Würzburg with 165 cells.

Grids created for all cities.

## Assign Data to Chunks

### Subtask:
Spatially join the city's GeoDataFrame with the grid to assign each data point (pixel) to a grid cell (chunk).

In [ ]:
# Dictionary to store city GeoDataFrames with assigned chunk IDs
city_data_with_chunks = {}

print("\nAssigning data points to spatial chunks...")

for city, gdf_city_averaged in city_averaged_gdfs.items():
    print(f"  Assigning data for {city} to chunks...")

    if city in city_grids:
        grid_gdf = city_grids[city]

        # Ensure both GeoDataFrames have the same CRS before spatial join
        if gdf_city_averaged.crs != grid_gdf.crs:
            print(f"    CRS mismatch for {city}. Converting city data to grid CRS ({grid_gdf.crs.to_epsg()}).")
            try:
                gdf_city_projected = gdf_city_averaged.to_crs(grid_gdf.crs)
            except Exception as crs_e:
                 print(f"    Error converting CRS for {city}: {crs_e}. Skipping chunk assignment for this city.")
                 continue
        else:
            gdf_city_projected = gdf_city_averaged.copy() # Use projected data if already in grid CRS

        # Perform a spatial join to assign a grid cell ID to each data point
        # Use 'within' predicate to assign points to the grid cell they fall within
        # We'll add a unique chunk ID to the grid first
        grid_gdf['chunk_id'] = range(len(grid_gdf))

        # Perform spatial join
        # Use 'left' join to keep all original data points, even if they fall outside the grid
        # (though ideally all points should be within the grid extent)
        # Suffixes are added to overlapping column names, we'll drop the grid geometry later
        gdf_city_with_chunks = gpd.sjoin(gdf_city_projected, grid_gdf[['geometry', 'chunk_id']], how="left", predicate="within")

        # Handle points outside the grid (chunk_id will be NaN) if any
        if gdf_city_with_chunks['chunk_id'].isnull().any():
            print(f"    Warning: Some points for {city} are outside the grid extent (NaN chunk_id).")
            # You might want to filter these out or handle them specifically
            # For now, we'll keep them but they won't be processed in chunks

        city_data_with_chunks[city] = gdf_city_with_chunks
        print(f"    Data for {city} assigned to chunks. Resulting GDF has {len(gdf_city_with_chunks)} rows.")

    else:
        print(f"  Grid not found for {city}. Skipping chunk assignment.")

print("\nChunk assignment completed for all cities.")

# The dictionary 'city_data_with_chunks' now contains GeoDataFrames for each city,
# with an added 'chunk_id' column indicating which grid cell each pixel belongs to.
# Example: city_data_with_chunks['Munich']

Assigning data points to spatial chunks...
  Assigning data for Aschaffenburg to chunks...
    CRS mismatch for Aschaffenburg. Converting city data to grid CRS (25832).
    Warning: Some points for Aschaffenburg are outside the grid extent (NaN chunk_id).
    Data for Aschaffenburg assigned to chunks. Resulting GDF has 69391 rows.
  Assigning data for Augsburg to chunks...
    CRS mismatch for Augsburg. Converting city data to grid CRS (25832).
    Warning: Some points for Augsburg are outside the grid extent (NaN chunk_id).
    Data for Augsburg assigned to chunks. Resulting GDF has 164425 rows.
  Assigning data for Bamberg to chunks...
    CRS mismatch for Bamberg. Converting city data to grid CRS (25832).
    Warning: Some points for Bamberg are outside the grid extent (NaN chunk_id).
    Data for Bamberg assigned to chunks. Resulting GDF has 121604 rows.
  Assigning data for Bayreuth to chunks...
    CRS mismatch for Bayreuth. Converting city data to grid CRS (25832).
    Warning: Some points for Bayreuth are outside the grid extent (NaN chunk_id).
    Data for Bayreuth assigned to chunks. Resulting GDF has 149925 rows.
  Assigning data for Erlangen to chunks...
    CRS mismatch for Erlangen. Converting city data to grid CRS (25832).
    Warning: Some points for Erlangen are outside the grid extent (NaN chunk_id).
    Data for Erlangen assigned to chunks. Resulting GDF has 80705 rows.
  Assigning data for Fürth to chunks...
    CRS mismatch for Fürth. Converting city data to grid CRS (25832).
    Warning: Some points for Fürth are outside the grid extent (NaN chunk_id).
    Data for Fürth assigned to chunks. Resulting GDF has 60360 rows.
  Assigning data for Ingolstadt to chunks...
    CRS mismatch for Ingolstadt. Converting city data to grid CRS (25832).
    Warning: Some points for Ingolstadt are outside the grid extent (NaN chunk_id).
    Data for Ingolstadt assigned to chunks. Resulting GDF has 150379 rows.
  Assigning data for Kempten (Allgäu) to chunks...
    CRS mismatch for Kempten (Allgäu). Converting city data to grid CRS (25832).
    Warning: Some points for Kempten (Allgäu) are outside the grid extent (NaN chunk_id).
    Data for Kempten (Allgäu) assigned to chunks. Resulting GDF has 67441 rows.
  Assigning data for Landshut to chunks...
    CRS mismatch for Landshut. Converting city data to grid CRS (25832).
    Warning: Some points for Landshut are outside the grid extent (NaN chunk_id).
    Data for Landshut assigned to chunks. Resulting GDF has 146398 rows.
  Assigning data for Munich to chunks...
    CRS mismatch for Munich. Converting city data to grid CRS (25832).
    Warning: Some points for Munich are outside the grid extent (NaN chunk_id).
    Data for Munich assigned to chunks. Resulting GDF has 349956 rows.
  Assigning data for Nuremberg to chunks...
    CRS mismatch for Nuremberg. Converting city data to grid CRS (25832).
    Warning: Some points for Nuremberg are outside the grid extent (NaN chunk_id).
    Data for Nuremberg assigned to chunks. Resulting GDF has 209693 rows.
  Assigning data for Passau to chunks...
    CRS mismatch for Passau. Converting city data to grid CRS (25832).
    Warning: Some points for Passau are outside the grid extent (NaN chunk_id).
    Data for Passau assigned to chunks. Resulting GDF has 77739 rows.
  Assigning data for Regensburg to chunks...
    CRS mismatch for Regensburg. Converting city data to grid CRS (25832).
    Warning: Some points for Regensburg are outside the grid extent (NaN chunk_id).
    Data for Regensburg assigned to chunks. Resulting GDF has 172599 rows.
  Assigning data for Rosenheim to chunks...
    CRS mismatch for Rosenheim. Converting city data to grid CRS (25832).
    Warning: Some points for Rosenheim are outside the grid extent (NaN chunk_id).
    Data for Rosenheim assigned to chunks. Resulting GDF has 42317 rows.
  Assigning data for Schweinfurt to chunks...
    CRS mismatch for Schweinfurt. Converting city data to grid CRS (25832).
    Warning: Some points for Schweinfurt are outside the grid extent (NaN chunk_id).
    Data for Schweinfurt assigned to chunks. Resulting GDF has 39886 rows.
  Assigning data for Würzburg to chunks...
    CRS mismatch for Würzburg. Converting city data to grid CRS (25832).
    Warning: Some points for Würzburg are outside the grid extent (NaN chunk_id).
    Data for Würzburg assigned to chunks. Resulting GDF has 89251 rows.

Chunk assignment completed for all cities.

## Process Each Chunk and Perform Gi* Analysis

### Subtask:
Iterate through each unique chunk for each city, filter the data for the chunk (with buffer), calculate KNN weights, perform Gi* analysis, and store results.

In [ ]:
# Dictionary to store Gi* results per city, combined from all chunks
city_gi_results_chunked = {}

# Define buffer distance (in meters, assuming projected CRS)
# This buffer is crucial to avoid edge effects in spatial analysis of chunks
# Points within the buffer but outside the chunk are used for neighbors, but not for the statistic itself.
buffer_distance = grid_cell_size * 1 # Example: buffer equal to one grid cell size

print(f"\nProcessing each chunk and performing Gi* analysis with a buffer of {buffer_distance} meters...")

for city, gdf_city_with_chunks in city_data_with_chunks.items():
    print(f"\n✨ Processing chunks for city: {city}...")

    if gdf_city_with_chunks.empty:
        print(f"  No data with chunk assignments for {city}. Skipping.")
        continue

    # Ensure we have the corresponding weight matrix available (if needed later, although chunking recalculates weights)
    # This part might need adjustment depending on whether you reuse city-level weights or calculate chunk-level weights
    # Given the plan, we calculate chunk-level weights, so the city-level matrix is not directly used here.
    # However, ensure the original data for the city is available if needed for context or re-joining.
    # We are using gdf_city_with_chunks which already has the necessary data.

    unique_chunks = gdf_city_with_chunks['chunk_id'].dropna().unique()
    print(f"  Found {len(unique_chunks)} chunks for {city}.")

    # List to store Gi* results for all chunks of the current city
    city_chunk_results = []

    # Iterate through each unique chunk ID
    for chunk_id in unique_chunks:
        print(f"    Processing chunk ID: {int(chunk_id)} for {city}...")

        # Get the geometry of the current chunk
        chunk_geometry = city_grids[city][city_grids[city]['chunk_id'] == chunk_id].geometry.iloc[0]

        # Create a buffered version of the chunk geometry
        buffered_chunk_geometry = chunk_geometry.buffer(buffer_distance)

        # Filter data points that are within the buffered chunk geometry
        # This includes points in the chunk AND points in the buffer zone
        gdf_chunk_buffered = gdf_city_with_chunks[
            gdf_city_with_chunks.within(buffered_chunk_geometry)
        ].copy() # Important: Copy to avoid SettingWithCopyWarning

        if gdf_chunk_buffered.empty:
            print(f"      No data points found within buffered chunk {int(chunk_id)}. Skipping.")
            continue

        # Filter data points that are within the original (unbuffered) chunk geometry
        # These are the points for which we will calculate and keep the Gi* results
        gdf_chunk_original = gdf_chunk_buffered[
            gdf_chunk_buffered.within(chunk_geometry)
        ].copy() # Important: Copy

        if gdf_chunk_original.empty:
             print(f"      No data points found within original chunk {int(chunk_id)}. Skipping Gi* calculation for this chunk.")
             continue

        # Ensure enough points for KNN in the buffered chunk
        min_points_for_knn = k_neighbors + 1 # Use the same k as before
        if len(gdf_chunk_buffered) >= min_points_for_knn:

            # Extract coordinates from the buffered chunk data for weight matrix calculation
            # The weight matrix must be built based on ALL points in the buffered area
            coords_buffered = np.array(list(zip(gdf_chunk_buffered.geometry.x, gdf_chunk_buffered.geometry.y)))

            # Extract the variable for analysis from the buffered chunk data
            # The variable values must also correspond to ALL points in the buffered area
            y_buffered = gdf_chunk_buffered['avg_summer_LST_Celsius'].values

            # Calculate KNN weights for the buffered chunk
            try:
                # Use the original indices from gdf_chunk_buffered to build the weight matrix
                # This is crucial so that the weight matrix indices match the data indices
                w_chunk_buffered = KNN.from_array(coords_buffered, k=k_neighbors, ids=gdf_chunk_buffered.index)
                w_chunk_buffered.transform = 'R' # Row standardize

                # Check for connectivity (optional but good practice)
                if w_chunk_buffered.n_components > 1:
                     print(f"      Warning: Weight matrix for buffered chunk {int(chunk_id)} is not fully connected ({w_chunk_buffered.n_components} components).")

                # Perform Gi* analysis on the buffered data using the buffered weight matrix
                # The results (Gi* values and p-values) will be calculated for all points in gdf_chunk_buffered
                gi_local_buffered = G_Local(y_buffered, w_chunk_buffered)

                # Add the Gi* results back to the buffered GeoDataFrame
                gdf_chunk_buffered['Gi_Star_buffered'] = gi_local_buffered.Gs
                gdf_chunk_buffered['Gi_Star_p_value_buffered'] = gi_local_buffered.p_sim

                # Now, extract the results ONLY for the points within the ORIGINAL chunk geometry
                # We need to join or map the results back to the original chunk data's index
                # The most reliable way is to merge based on the original index
                gi_results_for_original_chunk = gdf_chunk_buffered.loc[gdf_chunk_original.index, ['Gi_Star_buffered', 'Gi_Star_p_value_buffered']].copy()

                # Add these results as new columns to the original chunk GeoDataFrame
                gdf_chunk_original['Gi_Star'] = gi_results_for_original_chunk['Gi_Star_buffered']
                gdf_chunk_original['Gi_Star_p_value'] = gi_results_for_original_chunk['Gi_Star_p_value_buffered']


                # Determine significance for the original chunk points
                gdf_chunk_original['Gi_Star_sig'] = 'Nicht signifikant'
                gdf_chunk_original.loc[(gdf_chunk_original['Gi_Star_p_value'] < 0.05) & (gdf_chunk_original['Gi_Star'] < 0), 'Gi_Star_sig'] = 'Cold Spot (p<0.05)'
                gdf_chunk_original.loc[(gdf_chunk_original['Gi_Star_p_value'] < 0.05) & (gdf_chunk_original['Gi_Star'] > 0), 'Gi_Star_sig'] = 'Hot Spot (p<0.05)'
                # You can add more significance levels here

                # Append the results for the original chunk to the list
                city_chunk_results.append(gdf_chunk_original)

                print(f"      Gi* analysis successful for chunk {int(chunk_id)} ({len(gdf_chunk_original)} points in original chunk).")

            except Exception as gi_e:
                print(f"      Error during Gi* calculation for buffered chunk {int(chunk_id)}: {gi_e}. Skipping this chunk.")

        else:
            print(f"      Not enough data points ({len(gdf_chunk_buffered)}) in buffered chunk {int(chunk_id)} for KNN calculation (needs at least {min_points_for_knn}). Skipping.")


    # After processing all chunks for the city, concatenate the results
    if city_chunk_results:
        city_gi_results_chunked[city] = pd.concat(city_chunk_results)
        print(f"  Combined Gi* results for all chunks in {city}.")
        # Optional: Display head of combined results for the city
        # display(city_gi_results_chunked[city][['avg_summer_LST_Celsius', 'Gi_Star', 'Gi_Star_p_value', 'Gi_Star_sig']].head())
    else:
        print(f"  No Gi* results were generated for any chunk in {city}.")


print("\nGi* analysis with spatial chunking completed for all cities.")

# The dictionary 'city_gi_results_chunked' contains GeoDataFrames for each city
# with the Gi* results calculated using spatial chunking.
# Example: city_gi_results_chunked['Munich']

Processing each chunk and performing Gi* analysis with a buffer of 1000 meters...

✨ Processing chunks for city: Aschaffenburg...
  Found 90 chunks for Aschaffenburg.
    Processing chunk ID: 121 for Aschaffenburg...
      Gi* analysis successful for chunk 121 (319 points in original chunk).
    Processing chunk ID: 133 for Aschaffenburg...
      Gi* analysis successful for chunk 133 (76 points in original chunk).
    Processing chunk ID: 122 for Aschaffenburg...
      Gi* analysis successful for chunk 122 (784 points in original chunk).
    Processing chunk ID: 134 for Aschaffenburg...
      Gi* analysis successful for chunk 134 (58 points in original chunk).
    Processing chunk ID: 109 for Aschaffenburg...
      Gi* analysis successful for chunk 109 (634 points in original chunk).
    Processing chunk ID: 110 for Aschaffenburg...
      Gi* analysis successful for chunk 110 (1156 points in original chunk).
    Processing chunk ID: 98 for Aschaffenburg...
      Gi* analysis successful for chunk 98 (1122 points in original chunk).
    Processing chunk ID: 97 for Aschaffenburg...
      Gi* analysis successful for chunk 97 (1025 points in original chunk).
    Processing chunk ID: 96 for Aschaffenburg...
      Gi* analysis successful for chunk 96 (7 points in original chunk).
    Processing chunk ID: 85 for Aschaffenburg...
      Gi* analysis successful for chunk 85 (1090 points in original chunk).
    Processing chunk ID: 84 for Aschaffenburg...
      Gi* analysis successful for chunk 84 (311 points in original chunk).
    Processing chunk ID: 86 for Aschaffenburg...
      Gi* analysis successful for chunk 86 (1123 points in original chunk).
    Processing chunk ID: 74 for Aschaffenburg...
      Gi* analysis successful for chunk 74 (1157 points in original chunk).
    Processing chunk ID: 73 for Aschaffenburg...
      Gi* analysis successful for chunk 73 (1085 points in original chunk).
    Processing chunk ID: 62 for Aschaffenburg...
      Gi* analysis successful for chunk 62 (1122 points in original chunk).
    Processing chunk ID: 50 for Aschaffenburg...
      Gi* analysis successful for chunk 50 (1122 points in original chunk).
    Processing chunk ID: 61 for Aschaffenburg...
      Gi* analysis successful for chunk 61 (1089 points in original chunk).
    Processing chunk ID: 49 for Aschaffenburg...
      Gi* analysis successful for chunk 49 (1089 points in original chunk).
    Processing chunk ID: 60 for Aschaffenburg...
      Gi* analysis successful for chunk 60 (874 points in original chunk).
    Processing chunk ID: 72 for Aschaffenburg...
      Gi* analysis successful for chunk 72 (206 points in original chunk).
    Processing chunk ID: 48 for Aschaffenburg...
      Gi* analysis successful for chunk 48 (647 points in original chunk).
    Processing chunk ID: 37 for Aschaffenburg...
      Gi* analysis successful for chunk 37 (640 points in original chunk).
    Processing chunk ID: 38 for Aschaffenburg...
      Gi* analysis successful for chunk 38 (1157 points in original chunk).
    Processing chunk ID: 26 for Aschaffenburg...
      Gi* analysis successful for chunk 26 (1122 points in original chunk).
    Processing chunk ID: 25 for Aschaffenburg...
      Gi* analysis successful for chunk 25 (232 points in original chunk).
    Processing chunk ID: 14 for Aschaffenburg...
      Gi* analysis successful for chunk 14 (1086 points in original chunk).
    Processing chunk ID: 13 for Aschaffenburg...
      Gi* analysis successful for chunk 13 (553 points in original chunk).
    Processing chunk ID: 2 for Aschaffenburg...
      Gi* analysis successful for chunk 2 (161 points in original chunk).
    Processing chunk ID: 3 for Aschaffenburg...
      Gi* analysis successful for chunk 3 (727 points in original chunk).
    Processing chunk ID: 15 for Aschaffenburg...
      Gi* analysis successful for chunk 15 (1089 points in original chunk).
    Processing chunk ID: 27 for Aschaffenburg...
      Gi* analysis successful for chunk 27 (1089 points in original chunk).
    Processing chunk ID: 16 for Aschaffenburg...
      Gi* analysis successful for chunk 16 (1044 points in original chunk).
    Processing chunk ID: 28 for Aschaffenburg...
      Gi* analysis successful for chunk 28 (1089 points in original chunk).
    Processing chunk ID: 4 for Aschaffenburg...
      Gi* analysis successful for chunk 4 (205 points in original chunk).
    Processing chunk ID: 5 for Aschaffenburg...
      Warning: Weight matrix for buffered chunk 5 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 5 (645 points in original chunk).
    Processing chunk ID: 17 for Aschaffenburg...
      Warning: Weight matrix for buffered chunk 17 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 17 (1030 points in original chunk).
    Processing chunk ID: 6 for Aschaffenburg...
      Warning: Weight matrix for buffered chunk 6 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 6 (1 points in original chunk).
    Processing chunk ID: 30 for Aschaffenburg...
      Gi* analysis successful for chunk 30 (1021 points in original chunk).
    Processing chunk ID: 18 for Aschaffenburg...
      Gi* analysis successful for chunk 18 (33 points in original chunk).
    Processing chunk ID: 29 for Aschaffenburg...
      Gi* analysis successful for chunk 29 (1123 points in original chunk).
    Processing chunk ID: 41 for Aschaffenburg...
      Gi* analysis successful for chunk 41 (1156 points in original chunk).
    Processing chunk ID: 40 for Aschaffenburg...
      Gi* analysis successful for chunk 40 (1122 points in original chunk).
    Processing chunk ID: 42 for Aschaffenburg...
      Gi* analysis successful for chunk 42 (1122 points in original chunk).
    Processing chunk ID: 54 for Aschaffenburg...
      Gi* analysis successful for chunk 54 (1089 points in original chunk).
    Processing chunk ID: 53 for Aschaffenburg...
      Gi* analysis successful for chunk 53 (1122 points in original chunk).
    Processing chunk ID: 52 for Aschaffenburg...
      Gi* analysis successful for chunk 52 (1089 points in original chunk).
    Processing chunk ID: 51 for Aschaffenburg...
      Gi* analysis successful for chunk 51 (1089 points in original chunk).
    Processing chunk ID: 39 for Aschaffenburg...
      Gi* analysis successful for chunk 39 (1123 points in original chunk).
    Processing chunk ID: 63 for Aschaffenburg...
      Gi* analysis successful for chunk 63 (1089 points in original chunk).
    Processing chunk ID: 75 for Aschaffenburg...
      Gi* analysis successful for chunk 75 (1124 points in original chunk).
    Processing chunk ID: 64 for Aschaffenburg...
      Gi* analysis successful for chunk 64 (1089 points in original chunk).
    Processing chunk ID: 76 for Aschaffenburg...
      Gi* analysis successful for chunk 76 (1122 points in original chunk).
    Processing chunk ID: 88 for Aschaffenburg...
      Gi* analysis successful for chunk 88 (710 points in original chunk).
    Processing chunk ID: 87 for Aschaffenburg...
      Gi* analysis successful for chunk 87 (1089 points in original chunk).
    Processing chunk ID: 99 for Aschaffenburg...
      Gi* analysis successful for chunk 99 (890 points in original chunk).
    Processing chunk ID: 111 for Aschaffenburg...
      Gi* analysis successful for chunk 111 (571 points in original chunk).
    Processing chunk ID: 100 for Aschaffenburg...
      Gi* analysis successful for chunk 100 (252 points in original chunk).
    Processing chunk ID: 89 for Aschaffenburg...
      Gi* analysis successful for chunk 89 (796 points in original chunk).
    Processing chunk ID: 101 for Aschaffenburg...
      Gi* analysis successful for chunk 101 (30 points in original chunk).
    Processing chunk ID: 102 for Aschaffenburg...
      Gi* analysis successful for chunk 102 (98 points in original chunk).
    Processing chunk ID: 90 for Aschaffenburg...
      Gi* analysis successful for chunk 90 (940 points in original chunk).
    Processing chunk ID: 78 for Aschaffenburg...
      Gi* analysis successful for chunk 78 (1122 points in original chunk).
    Processing chunk ID: 77 for Aschaffenburg...
      Gi* analysis successful for chunk 77 (1156 points in original chunk).
    Processing chunk ID: 65 for Aschaffenburg...
      Gi* analysis successful for chunk 65 (1122 points in original chunk).
    Processing chunk ID: 66 for Aschaffenburg...
      Gi* analysis successful for chunk 66 (1089 points in original chunk).
    Processing chunk ID: 67 for Aschaffenburg...
      Gi* analysis successful for chunk 67 (1093 points in original chunk).
    Processing chunk ID: 55 for Aschaffenburg...
      Gi* analysis successful for chunk 55 (1089 points in original chunk).
    Processing chunk ID: 79 for Aschaffenburg...
      Gi* analysis successful for chunk 79 (737 points in original chunk).
    Processing chunk ID: 68 for Aschaffenburg...
      Gi* analysis successful for chunk 68 (695 points in original chunk).
    Processing chunk ID: 56 for Aschaffenburg...
      Gi* analysis successful for chunk 56 (1070 points in original chunk).
    Processing chunk ID: 80 for Aschaffenburg...
      Gi* analysis successful for chunk 80 (65 points in original chunk).
    Processing chunk ID: 91 for Aschaffenburg...
      Gi* analysis successful for chunk 91 (96 points in original chunk).
    Processing chunk ID: 46 for Aschaffenburg...
      Gi* analysis successful for chunk 46 (170 points in original chunk).
    Processing chunk ID: 34 for Aschaffenburg...
      Gi* analysis successful for chunk 34 (101 points in original chunk).
    Processing chunk ID: 45 for Aschaffenburg...
      Gi* analysis successful for chunk 45 (809 points in original chunk).
    Processing chunk ID: 33 for Aschaffenburg...
      Gi* analysis successful for chunk 33 (837 points in original chunk).
    Processing chunk ID: 32 for Aschaffenburg...
      Gi* analysis successful for chunk 32 (1122 points in original chunk).
    Processing chunk ID: 44 for Aschaffenburg...
      Gi* analysis successful for chunk 44 (1156 points in original chunk).
    Processing chunk ID: 57 for Aschaffenburg...
      Gi* analysis successful for chunk 57 (60 points in original chunk).
    Processing chunk ID: 43 for Aschaffenburg...
      Gi* analysis successful for chunk 43 (1123 points in original chunk).
    Processing chunk ID: 31 for Aschaffenburg...
      Gi* analysis successful for chunk 31 (1082 points in original chunk).
    Processing chunk ID: 20 for Aschaffenburg...
      Gi* analysis successful for chunk 20 (1116 points in original chunk).
    Processing chunk ID: 19 for Aschaffenburg...
      Gi* analysis successful for chunk 19 (342 points in original chunk).
    Processing chunk ID: 8 for Aschaffenburg...
      Gi* analysis successful for chunk 8 (417 points in original chunk).
    Processing chunk ID: 9 for Aschaffenburg...
      Gi* analysis successful for chunk 9 (911 points in original chunk).
    Processing chunk ID: 21 for Aschaffenburg...
      Gi* analysis successful for chunk 21 (1086 points in original chunk).
    Processing chunk ID: 22 for Aschaffenburg...
      Gi* analysis successful for chunk 22 (574 points in original chunk).
    Processing chunk ID: 23 for Aschaffenburg...
      Gi* analysis successful for chunk 23 (44 points in original chunk).
    Processing chunk ID: 10 for Aschaffenburg...
      Gi* analysis successful for chunk 10 (226 points in original chunk).
    Processing chunk ID: 123 for Aschaffenburg...
      Gi* analysis successful for chunk 123 (23 points in original chunk).
  Combined Gi* results for all chunks in Aschaffenburg.

✨ Processing chunks for city: Augsburg...
  Found 195 chunks for Augsburg.
    Processing chunk ID: 302 for Augsburg...
      Gi* analysis successful for chunk 302 (632 points in original chunk).
    Processing chunk ID: 303 for Augsburg...
      Gi* analysis successful for chunk 303 (814 points in original chunk).
    Processing chunk ID: 279 for Augsburg...
      Gi* analysis successful for chunk 279 (1135 points in original chunk).
    Processing chunk ID: 280 for Augsburg...
      Gi* analysis successful for chunk 280 (1133 points in original chunk).
    Processing chunk ID: 301 for Augsburg...
      Gi* analysis successful for chunk 301 (453 points in original chunk).
    Processing chunk ID: 278 for Augsburg...
      Gi* analysis successful for chunk 278 (1164 points in original chunk).
    Processing chunk ID: 255 for Augsburg...
      Gi* analysis successful for chunk 255 (1127 points in original chunk).
    Processing chunk ID: 254 for Augsburg...
      Gi* analysis successful for chunk 254 (1104 points in original chunk).
    Processing chunk ID: 256 for Augsburg...
      Gi* analysis successful for chunk 256 (1104 points in original chunk).
    Processing chunk ID: 257 for Augsburg...
      Gi* analysis successful for chunk 257 (1096 points in original chunk).
    Processing chunk ID: 234 for Augsburg...
      Gi* analysis successful for chunk 234 (1096 points in original chunk).
    Processing chunk ID: 233 for Augsburg...
      Gi* analysis successful for chunk 233 (945 points in original chunk).
    Processing chunk ID: 232 for Augsburg...
      Gi* analysis successful for chunk 232 (965 points in original chunk).
    Processing chunk ID: 210 for Augsburg...
      Gi* analysis successful for chunk 210 (189 points in original chunk).
    Processing chunk ID: 187 for Augsburg...
      Gi* analysis successful for chunk 187 (186 points in original chunk).
    Processing chunk ID: 209 for Augsburg...
      Gi* analysis successful for chunk 209 (1 points in original chunk).
    Processing chunk ID: 231 for Augsburg...
      Gi* analysis successful for chunk 231 (751 points in original chunk).
    Processing chunk ID: 253 for Augsburg...
      Gi* analysis successful for chunk 253 (785 points in original chunk).
    Processing chunk ID: 230 for Augsburg...
      Gi* analysis successful for chunk 230 (325 points in original chunk).
    Processing chunk ID: 277 for Augsburg...
      Gi* analysis successful for chunk 277 (1111 points in original chunk).
    Processing chunk ID: 300 for Augsburg...
      Gi* analysis successful for chunk 300 (252 points in original chunk).
    Processing chunk ID: 299 for Augsburg...
      Gi* analysis successful for chunk 299 (1 points in original chunk).
    Processing chunk ID: 164 for Augsburg...
      Gi* analysis successful for chunk 164 (347 points in original chunk).
    Processing chunk ID: 141 for Augsburg...
      Gi* analysis successful for chunk 141 (143 points in original chunk).
    Processing chunk ID: 118 for Augsburg...
      Gi* analysis successful for chunk 118 (254 points in original chunk).
    Processing chunk ID: 72 for Augsburg...
      Gi* analysis successful for chunk 72 (146 points in original chunk).
    Processing chunk ID: 49 for Augsburg...
      Gi* analysis successful for chunk 49 (314 points in original chunk).
    Processing chunk ID: 4 for Augsburg...
      Gi* analysis successful for chunk 4 (935 points in original chunk).
    Processing chunk ID: 27 for Augsburg...
      Gi* analysis successful for chunk 27 (999 points in original chunk).
    Processing chunk ID: 5 for Augsburg...
      Gi* analysis successful for chunk 5 (799 points in original chunk).
    Processing chunk ID: 28 for Augsburg...
      Gi* analysis successful for chunk 28 (1037 points in original chunk).
    Processing chunk ID: 7 for Augsburg...
      Warning: Weight matrix for buffered chunk 7 is not fully connected (3 components).
      Gi* analysis successful for chunk 7 (45 points in original chunk).
    Processing chunk ID: 6 for Augsburg...
      Warning: Weight matrix for buffered chunk 6 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)
/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 6 (18 points in original chunk).
    Processing chunk ID: 29 for Augsburg...
      Gi* analysis successful for chunk 29 (219 points in original chunk).
    Processing chunk ID: 51 for Augsburg...
      Gi* analysis successful for chunk 51 (1089 points in original chunk).
    Processing chunk ID: 52 for Augsburg...
      Gi* analysis successful for chunk 52 (1090 points in original chunk).
    Processing chunk ID: 30 for Augsburg...
      Gi* analysis successful for chunk 30 (247 points in original chunk).
    Processing chunk ID: 53 for Augsburg...
      Gi* analysis successful for chunk 53 (1033 points in original chunk).
    Processing chunk ID: 54 for Augsburg...
      Gi* analysis successful for chunk 54 (896 points in original chunk).
    Processing chunk ID: 76 for Augsburg...
      Gi* analysis successful for chunk 76 (1126 points in original chunk).
    Processing chunk ID: 77 for Augsburg...
      Gi* analysis successful for chunk 77 (1132 points in original chunk).
    Processing chunk ID: 75 for Augsburg...
      Gi* analysis successful for chunk 75 (1156 points in original chunk).
    Processing chunk ID: 74 for Augsburg...
      Gi* analysis successful for chunk 74 (1122 points in original chunk).
    Processing chunk ID: 73 for Augsburg...
      Gi* analysis successful for chunk 73 (927 points in original chunk).
    Processing chunk ID: 50 for Augsburg...
      Gi* analysis successful for chunk 50 (1096 points in original chunk).
    Processing chunk ID: 26 for Augsburg...
      Gi* analysis successful for chunk 26 (51 points in original chunk).
    Processing chunk ID: 96 for Augsburg...
      Gi* analysis successful for chunk 96 (944 points in original chunk).
    Processing chunk ID: 97 for Augsburg...
      Gi* analysis successful for chunk 97 (1089 points in original chunk).
    Processing chunk ID: 119 for Augsburg...
      Gi* analysis successful for chunk 119 (1084 points in original chunk).
    Processing chunk ID: 120 for Augsburg...
      Gi* analysis successful for chunk 120 (1089 points in original chunk).
    Processing chunk ID: 143 for Augsburg...
      Gi* analysis successful for chunk 143 (1122 points in original chunk).
    Processing chunk ID: 121 for Augsburg...
      Gi* analysis successful for chunk 121 (1122 points in original chunk).
    Processing chunk ID: 144 for Augsburg...
      Gi* analysis successful for chunk 144 (1156 points in original chunk).
    Processing chunk ID: 142 for Augsburg...
      Gi* analysis successful for chunk 142 (1102 points in original chunk).
    Processing chunk ID: 95 for Augsburg...
      Gi* analysis successful for chunk 95 (2 points in original chunk).
    Processing chunk ID: 165 for Augsburg...
      Gi* analysis successful for chunk 165 (1096 points in original chunk).
    Processing chunk ID: 188 for Augsburg...
      Gi* analysis successful for chunk 188 (1095 points in original chunk).
    Processing chunk ID: 189 for Augsburg...
      Gi* analysis successful for chunk 189 (1089 points in original chunk).
    Processing chunk ID: 166 for Augsburg...
      Gi* analysis successful for chunk 166 (1089 points in original chunk).
    Processing chunk ID: 190 for Augsburg...
      Gi* analysis successful for chunk 190 (1122 points in original chunk).
    Processing chunk ID: 167 for Augsburg...
      Gi* analysis successful for chunk 167 (1124 points in original chunk).
    Processing chunk ID: 145 for Augsburg...
      Gi* analysis successful for chunk 145 (1131 points in original chunk).
    Processing chunk ID: 168 for Augsburg...
      Gi* analysis successful for chunk 168 (1090 points in original chunk).
    Processing chunk ID: 191 for Augsburg...
      Gi* analysis successful for chunk 191 (1096 points in original chunk).
    Processing chunk ID: 192 for Augsburg...
      Gi* analysis successful for chunk 192 (1122 points in original chunk).
    Processing chunk ID: 169 for Augsburg...
      Gi* analysis successful for chunk 169 (1098 points in original chunk).
    Processing chunk ID: 146 for Augsburg...
      Gi* analysis successful for chunk 146 (1136 points in original chunk).
    Processing chunk ID: 122 for Augsburg...
      Gi* analysis successful for chunk 122 (1096 points in original chunk).
    Processing chunk ID: 123 for Augsburg...
      Gi* analysis successful for chunk 123 (1103 points in original chunk).
    Processing chunk ID: 100 for Augsburg...
      Gi* analysis successful for chunk 100 (1102 points in original chunk).
    Processing chunk ID: 99 for Augsburg...
      Gi* analysis successful for chunk 99 (1093 points in original chunk).
    Processing chunk ID: 98 for Augsburg...
      Gi* analysis successful for chunk 98 (1122 points in original chunk).
    Processing chunk ID: 101 for Augsburg...
      Gi* analysis successful for chunk 101 (241 points in original chunk).
    Processing chunk ID: 78 for Augsburg...
      Gi* analysis successful for chunk 78 (1107 points in original chunk).
    Processing chunk ID: 79 for Augsburg...
      Gi* analysis successful for chunk 79 (1 points in original chunk).
    Processing chunk ID: 102 for Augsburg...
      Gi* analysis successful for chunk 102 (5 points in original chunk).
    Processing chunk ID: 124 for Augsburg...
      Warning: Weight matrix for buffered chunk 124 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 124 (660 points in original chunk).
    Processing chunk ID: 147 for Augsburg...
      Gi* analysis successful for chunk 147 (726 points in original chunk).
    Processing chunk ID: 170 for Augsburg...
      Gi* analysis successful for chunk 170 (1173 points in original chunk).
    Processing chunk ID: 193 for Augsburg...
      Gi* analysis successful for chunk 193 (1142 points in original chunk).
    Processing chunk ID: 194 for Augsburg...
      Gi* analysis successful for chunk 194 (1089 points in original chunk).
    Processing chunk ID: 171 for Augsburg...
      Gi* analysis successful for chunk 171 (1089 points in original chunk).
    Processing chunk ID: 148 for Augsburg...
      Gi* analysis successful for chunk 148 (562 points in original chunk).
    Processing chunk ID: 149 for Augsburg...
      Gi* analysis successful for chunk 149 (443 points in original chunk).
    Processing chunk ID: 172 for Augsburg...
      Gi* analysis successful for chunk 172 (1122 points in original chunk).
    Processing chunk ID: 195 for Augsburg...
      Gi* analysis successful for chunk 195 (1122 points in original chunk).
    Processing chunk ID: 173 for Augsburg...
      Gi* analysis successful for chunk 173 (1105 points in original chunk).
    Processing chunk ID: 196 for Augsburg...
      Gi* analysis successful for chunk 196 (1097 points in original chunk).
    Processing chunk ID: 150 for Augsburg...
      Gi* analysis successful for chunk 150 (807 points in original chunk).
    Processing chunk ID: 55 for Augsburg...
      Gi* analysis successful for chunk 55 (506 points in original chunk).
    Processing chunk ID: 56 for Augsburg...
      Gi* analysis successful for chunk 56 (6 points in original chunk).
    Processing chunk ID: 31 for Augsburg...
      Gi* analysis successful for chunk 31 (408 points in original chunk).
    Processing chunk ID: 8 for Augsburg...
      Gi* analysis successful for chunk 8 (46 points in original chunk).
    Processing chunk ID: 154 for Augsburg...
      Gi* analysis successful for chunk 154 (459 points in original chunk).
    Processing chunk ID: 177 for Augsburg...
      Gi* analysis successful for chunk 177 (316 points in original chunk).
    Processing chunk ID: 200 for Augsburg...
      Gi* analysis successful for chunk 200 (705 points in original chunk).
    Processing chunk ID: 199 for Augsburg...
      Gi* analysis successful for chunk 199 (1101 points in original chunk).
    Processing chunk ID: 176 for Augsburg...
      Gi* analysis successful for chunk 176 (1101 points in original chunk).
    Processing chunk ID: 198 for Augsburg...
      Gi* analysis successful for chunk 198 (1134 points in original chunk).
    Processing chunk ID: 175 for Augsburg...
      Gi* analysis successful for chunk 175 (1137 points in original chunk).
    Processing chunk ID: 153 for Augsburg...
      Gi* analysis successful for chunk 153 (1123 points in original chunk).
    Processing chunk ID: 152 for Augsburg...
      Gi* analysis successful for chunk 152 (1163 points in original chunk).
    Processing chunk ID: 129 for Augsburg...
      Gi* analysis successful for chunk 129 (503 points in original chunk).
    Processing chunk ID: 130 for Augsburg...
      Gi* analysis successful for chunk 130 (188 points in original chunk).
    Processing chunk ID: 128 for Augsburg...
      Gi* analysis successful for chunk 128 (739 points in original chunk).
    Processing chunk ID: 105 for Augsburg...
      Gi* analysis successful for chunk 105 (167 points in original chunk).
    Processing chunk ID: 106 for Augsburg...
      Gi* analysis successful for chunk 106 (53 points in original chunk).
    Processing chunk ID: 151 for Augsburg...
      Gi* analysis successful for chunk 151 (1061 points in original chunk).
    Processing chunk ID: 174 for Augsburg...
      Gi* analysis successful for chunk 174 (1089 points in original chunk).
    Processing chunk ID: 197 for Augsburg...
      Gi* analysis successful for chunk 197 (1089 points in original chunk).
    Processing chunk ID: 219 for Augsburg...
      Gi* analysis successful for chunk 219 (1134 points in original chunk).
    Processing chunk ID: 220 for Augsburg...
      Gi* analysis successful for chunk 220 (1122 points in original chunk).
    Processing chunk ID: 221 for Augsburg...
      Gi* analysis successful for chunk 221 (1169 points in original chunk).
    Processing chunk ID: 243 for Augsburg...
      Gi* analysis successful for chunk 243 (1089 points in original chunk).
    Processing chunk ID: 244 for Augsburg...
      Gi* analysis successful for chunk 244 (1128 points in original chunk).
    Processing chunk ID: 267 for Augsburg...
      Gi* analysis successful for chunk 267 (1134 points in original chunk).
    Processing chunk ID: 266 for Augsburg...
      Gi* analysis successful for chunk 266 (1089 points in original chunk).
    Processing chunk ID: 265 for Augsburg...
      Gi* analysis successful for chunk 265 (1105 points in original chunk).
    Processing chunk ID: 242 for Augsburg...
      Gi* analysis successful for chunk 242 (1100 points in original chunk).
    Processing chunk ID: 288 for Augsburg...
      Gi* analysis successful for chunk 288 (1137 points in original chunk).
    Processing chunk ID: 289 for Augsburg...
      Gi* analysis successful for chunk 289 (1122 points in original chunk).
    Processing chunk ID: 311 for Augsburg...
      Gi* analysis successful for chunk 311 (985 points in original chunk).
    Processing chunk ID: 312 for Augsburg...
      Gi* analysis successful for chunk 312 (1087 points in original chunk).
    Processing chunk ID: 313 for Augsburg...
      Gi* analysis successful for chunk 313 (791 points in original chunk).
    Processing chunk ID: 290 for Augsburg...
      Gi* analysis successful for chunk 290 (1167 points in original chunk).
    Processing chunk ID: 268 for Augsburg...
      Gi* analysis successful for chunk 268 (1110 points in original chunk).
    Processing chunk ID: 291 for Augsburg...
      Gi* analysis successful for chunk 291 (1133 points in original chunk).
    Processing chunk ID: 314 for Augsburg...
      Gi* analysis successful for chunk 314 (230 points in original chunk).
    Processing chunk ID: 292 for Augsburg...
      Gi* analysis successful for chunk 292 (799 points in original chunk).
    Processing chunk ID: 269 for Augsburg...
      Gi* analysis successful for chunk 269 (1098 points in original chunk).
    Processing chunk ID: 246 for Augsburg...
      Gi* analysis successful for chunk 246 (1097 points in original chunk).
    Processing chunk ID: 223 for Augsburg...
      Gi* analysis successful for chunk 223 (1130 points in original chunk).
    Processing chunk ID: 245 for Augsburg...
      Gi* analysis successful for chunk 245 (1102 points in original chunk).
    Processing chunk ID: 222 for Augsburg...
      Gi* analysis successful for chunk 222 (1132 points in original chunk).
    Processing chunk ID: 224 for Augsburg...
      Gi* analysis successful for chunk 224 (1166 points in original chunk).
    Processing chunk ID: 201 for Augsburg...
      Warning: Weight matrix for buffered chunk 201 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 201 (89 points in original chunk).
    Processing chunk ID: 247 for Augsburg...
      Gi* analysis successful for chunk 247 (1136 points in original chunk).
    Processing chunk ID: 270 for Augsburg...
      Gi* analysis successful for chunk 270 (1129 points in original chunk).
    Processing chunk ID: 225 for Augsburg...
      Gi* analysis successful for chunk 225 (1108 points in original chunk).
    Processing chunk ID: 248 for Augsburg...
      Gi* analysis successful for chunk 248 (1092 points in original chunk).
    Processing chunk ID: 226 for Augsburg...
      Gi* analysis successful for chunk 226 (1110 points in original chunk).
    Processing chunk ID: 203 for Augsburg...
      Gi* analysis successful for chunk 203 (13 points in original chunk).
    Processing chunk ID: 227 for Augsburg...
      Gi* analysis successful for chunk 227 (1156 points in original chunk).
    Processing chunk ID: 204 for Augsburg...
      Gi* analysis successful for chunk 204 (182 points in original chunk).
    Processing chunk ID: 249 for Augsburg...
      Gi* analysis successful for chunk 249 (763 points in original chunk).
    Processing chunk ID: 250 for Augsburg...
      Gi* analysis successful for chunk 250 (102 points in original chunk).
    Processing chunk ID: 271 for Augsburg...
      Gi* analysis successful for chunk 271 (602 points in original chunk).
    Processing chunk ID: 272 for Augsburg...
      Gi* analysis successful for chunk 272 (54 points in original chunk).
    Processing chunk ID: 293 for Augsburg...
      Gi* analysis successful for chunk 293 (244 points in original chunk).
    Processing chunk ID: 335 for Augsburg...
      Gi* analysis successful for chunk 335 (153 points in original chunk).
    Processing chunk ID: 334 for Augsburg...
      Gi* analysis successful for chunk 334 (213 points in original chunk).
    Processing chunk ID: 330 for Augsburg...
      Gi* analysis successful for chunk 330 (108 points in original chunk).
    Processing chunk ID: 307 for Augsburg...
      Gi* analysis successful for chunk 307 (971 points in original chunk).
    Processing chunk ID: 308 for Augsburg...
      Gi* analysis successful for chunk 308 (1136 points in original chunk).
    Processing chunk ID: 331 for Augsburg...
      Gi* analysis successful for chunk 331 (99 points in original chunk).
    Processing chunk ID: 309 for Augsburg...
      Gi* analysis successful for chunk 309 (1015 points in original chunk).
    Processing chunk ID: 310 for Augsburg...
      Gi* analysis successful for chunk 310 (845 points in original chunk).
    Processing chunk ID: 287 for Augsburg...
      Gi* analysis successful for chunk 287 (1156 points in original chunk).
    Processing chunk ID: 286 for Augsburg...
      Gi* analysis successful for chunk 286 (1122 points in original chunk).
    Processing chunk ID: 264 for Augsburg...
      Gi* analysis successful for chunk 264 (1122 points in original chunk).
    Processing chunk ID: 263 for Augsburg...
      Gi* analysis successful for chunk 263 (1089 points in original chunk).
    Processing chunk ID: 241 for Augsburg...
      Gi* analysis successful for chunk 241 (1123 points in original chunk).
    Processing chunk ID: 218 for Augsburg...
      Gi* analysis successful for chunk 218 (1156 points in original chunk).
    Processing chunk ID: 217 for Augsburg...
      Gi* analysis successful for chunk 217 (1122 points in original chunk).
    Processing chunk ID: 240 for Augsburg...
      Gi* analysis successful for chunk 240 (1089 points in original chunk).
    Processing chunk ID: 239 for Augsburg...
      Gi* analysis successful for chunk 239 (1135 points in original chunk).
    Processing chunk ID: 262 for Augsburg...
      Gi* analysis successful for chunk 262 (1125 points in original chunk).
    Processing chunk ID: 216 for Augsburg...
      Gi* analysis successful for chunk 216 (1173 points in original chunk).
    Processing chunk ID: 215 for Augsburg...
      Gi* analysis successful for chunk 215 (1167 points in original chunk).
    Processing chunk ID: 238 for Augsburg...
      Gi* analysis successful for chunk 238 (1136 points in original chunk).
    Processing chunk ID: 261 for Augsburg...
      Gi* analysis successful for chunk 261 (1135 points in original chunk).
    Processing chunk ID: 284 for Augsburg...
      Gi* analysis successful for chunk 284 (1163 points in original chunk).
    Processing chunk ID: 285 for Augsburg...
      Gi* analysis successful for chunk 285 (1172 points in original chunk).
    Processing chunk ID: 306 for Augsburg...
      Gi* analysis successful for chunk 306 (877 points in original chunk).
    Processing chunk ID: 283 for Augsburg...
      Gi* analysis successful for chunk 283 (1128 points in original chunk).
    Processing chunk ID: 305 for Augsburg...
      Gi* analysis successful for chunk 305 (781 points in original chunk).
    Processing chunk ID: 282 for Augsburg...
      Gi* analysis successful for chunk 282 (1122 points in original chunk).
    Processing chunk ID: 260 for Augsburg...
      Gi* analysis successful for chunk 260 (1096 points in original chunk).
    Processing chunk ID: 259 for Augsburg...
      Gi* analysis successful for chunk 259 (1089 points in original chunk).
    Processing chunk ID: 237 for Augsburg...
      Gi* analysis successful for chunk 237 (1093 points in original chunk).
    Processing chunk ID: 214 for Augsburg...
      Gi* analysis successful for chunk 214 (1127 points in original chunk).
    Processing chunk ID: 213 for Augsburg...
      Gi* analysis successful for chunk 213 (1132 points in original chunk).
    Processing chunk ID: 236 for Augsburg...
      Gi* analysis successful for chunk 236 (1089 points in original chunk).
    Processing chunk ID: 258 for Augsburg...
      Gi* analysis successful for chunk 258 (1122 points in original chunk).
    Processing chunk ID: 235 for Augsburg...
      Gi* analysis successful for chunk 235 (1122 points in original chunk).
    Processing chunk ID: 212 for Augsburg...
      Gi* analysis successful for chunk 212 (1145 points in original chunk).
    Processing chunk ID: 211 for Augsburg...
      Gi* analysis successful for chunk 211 (1133 points in original chunk).
    Processing chunk ID: 281 for Augsburg...
      Gi* analysis successful for chunk 281 (1156 points in original chunk).
    Processing chunk ID: 304 for Augsburg...
      Gi* analysis successful for chunk 304 (1088 points in original chunk).
    Processing chunk ID: 326 for Augsburg...
      Gi* analysis successful for chunk 326 (30 points in original chunk).
    Processing chunk ID: 327 for Augsburg...
      Gi* analysis successful for chunk 327 (146 points in original chunk).
    Processing chunk ID: 228 for Augsburg...
      Gi* analysis successful for chunk 228 (819 points in original chunk).
    Processing chunk ID: 205 for Augsburg...
      Gi* analysis successful for chunk 205 (392 points in original chunk).
    Processing chunk ID: 206 for Augsburg...
      Gi* analysis successful for chunk 206 (109 points in original chunk).
    Processing chunk ID: 229 for Augsburg...
      Gi* analysis successful for chunk 229 (70 points in original chunk).
  Combined Gi* results for all chunks in Augsburg.

✨ Processing chunks for city: Bamberg...
  Found 75 chunks for Bamberg.
    Processing chunk ID: 22 for Bamberg...
      Gi* analysis successful for chunk 22 (473 points in original chunk).
    Processing chunk ID: 32 for Bamberg...
      Gi* analysis successful for chunk 32 (1921 points in original chunk).
    Processing chunk ID: 42 for Bamberg...
      Gi* analysis successful for chunk 42 (2212 points in original chunk).
    Processing chunk ID: 31 for Bamberg...
      Gi* analysis successful for chunk 31 (139 points in original chunk).
    Processing chunk ID: 41 for Bamberg...
      Gi* analysis successful for chunk 41 (1642 points in original chunk).
    Processing chunk ID: 90 for Bamberg...
      Gi* analysis successful for chunk 90 (110 points in original chunk).
    Processing chunk ID: 91 for Bamberg...
      Gi* analysis successful for chunk 91 (476 points in original chunk).
    Processing chunk ID: 92 for Bamberg...
      Gi* analysis successful for chunk 92 (11 points in original chunk).
    Processing chunk ID: 82 for Bamberg...
      Gi* analysis successful for chunk 82 (1910 points in original chunk).
    Processing chunk ID: 83 for Bamberg...
      Gi* analysis successful for chunk 83 (1629 points in original chunk).
    Processing chunk ID: 81 for Bamberg...
      Gi* analysis successful for chunk 81 (1393 points in original chunk).
    Processing chunk ID: 72 for Bamberg...
      Gi* analysis successful for chunk 72 (2238 points in original chunk).
    Processing chunk ID: 71 for Bamberg...
      Gi* analysis successful for chunk 71 (2097 points in original chunk).
    Processing chunk ID: 62 for Bamberg...
      Gi* analysis successful for chunk 62 (2259 points in original chunk).
    Processing chunk ID: 61 for Bamberg...
      Gi* analysis successful for chunk 61 (2248 points in original chunk).
    Processing chunk ID: 60 for Bamberg...
      Gi* analysis successful for chunk 60 (1572 points in original chunk).
    Processing chunk ID: 70 for Bamberg...
      Gi* analysis successful for chunk 70 (1121 points in original chunk).
    Processing chunk ID: 50 for Bamberg...
      Gi* analysis successful for chunk 50 (532 points in original chunk).
    Processing chunk ID: 51 for Bamberg...
      Gi* analysis successful for chunk 51 (2214 points in original chunk).
    Processing chunk ID: 40 for Bamberg...
      Gi* analysis successful for chunk 40 (7 points in original chunk).
    Processing chunk ID: 52 for Bamberg...
      Gi* analysis successful for chunk 52 (2204 points in original chunk).
    Processing chunk ID: 43 for Bamberg...
      Gi* analysis successful for chunk 43 (2230 points in original chunk).
    Processing chunk ID: 33 for Bamberg...
      Gi* analysis successful for chunk 33 (2270 points in original chunk).
    Processing chunk ID: 53 for Bamberg...
      Gi* analysis successful for chunk 53 (2237 points in original chunk).
    Processing chunk ID: 63 for Bamberg...
      Gi* analysis successful for chunk 63 (2257 points in original chunk).
    Processing chunk ID: 54 for Bamberg...
      Gi* analysis successful for chunk 54 (2207 points in original chunk).
    Processing chunk ID: 64 for Bamberg...
      Gi* analysis successful for chunk 64 (2237 points in original chunk).
    Processing chunk ID: 65 for Bamberg...
      Gi* analysis successful for chunk 65 (2271 points in original chunk).
    Processing chunk ID: 55 for Bamberg...
      Gi* analysis successful for chunk 55 (2214 points in original chunk).
    Processing chunk ID: 44 for Bamberg...
      Gi* analysis successful for chunk 44 (2210 points in original chunk).
    Processing chunk ID: 45 for Bamberg...
      Gi* analysis successful for chunk 45 (2210 points in original chunk).
    Processing chunk ID: 34 for Bamberg...
      Gi* analysis successful for chunk 34 (2243 points in original chunk).
    Processing chunk ID: 35 for Bamberg...
      Gi* analysis successful for chunk 35 (2241 points in original chunk).
    Processing chunk ID: 56 for Bamberg...
      Gi* analysis successful for chunk 56 (2228 points in original chunk).
    Processing chunk ID: 46 for Bamberg...
      Gi* analysis successful for chunk 46 (2232 points in original chunk).
    Processing chunk ID: 36 for Bamberg...
      Gi* analysis successful for chunk 36 (2270 points in original chunk).
    Processing chunk ID: 37 for Bamberg...
      Gi* analysis successful for chunk 37 (1837 points in original chunk).
    Processing chunk ID: 47 for Bamberg...
      Gi* analysis successful for chunk 47 (2201 points in original chunk).
    Processing chunk ID: 57 for Bamberg...
      Gi* analysis successful for chunk 57 (2202 points in original chunk).
    Processing chunk ID: 66 for Bamberg...
      Gi* analysis successful for chunk 66 (2237 points in original chunk).
    Processing chunk ID: 67 for Bamberg...
      Gi* analysis successful for chunk 67 (2235 points in original chunk).
    Processing chunk ID: 75 for Bamberg...
      Gi* analysis successful for chunk 75 (2245 points in original chunk).
    Processing chunk ID: 76 for Bamberg...
      Gi* analysis successful for chunk 76 (2203 points in original chunk).
    Processing chunk ID: 77 for Bamberg...
      Gi* analysis successful for chunk 77 (2186 points in original chunk).
    Processing chunk ID: 86 for Bamberg...
      Gi* analysis successful for chunk 86 (1415 points in original chunk).
    Processing chunk ID: 87 for Bamberg...
      Gi* analysis successful for chunk 87 (493 points in original chunk).
    Processing chunk ID: 85 for Bamberg...
      Gi* analysis successful for chunk 85 (1871 points in original chunk).
    Processing chunk ID: 84 for Bamberg...
      Gi* analysis successful for chunk 84 (1782 points in original chunk).
    Processing chunk ID: 74 for Bamberg...
      Gi* analysis successful for chunk 74 (2207 points in original chunk).
    Processing chunk ID: 73 for Bamberg...
      Gi* analysis successful for chunk 73 (2199 points in original chunk).
    Processing chunk ID: 69 for Bamberg...
      Gi* analysis successful for chunk 69 (599 points in original chunk).
    Processing chunk ID: 78 for Bamberg...
      Gi* analysis successful for chunk 78 (1022 points in original chunk).
    Processing chunk ID: 68 for Bamberg...
      Gi* analysis successful for chunk 68 (2262 points in original chunk).
    Processing chunk ID: 58 for Bamberg...
      Gi* analysis successful for chunk 58 (2059 points in original chunk).
    Processing chunk ID: 59 for Bamberg...
      Gi* analysis successful for chunk 59 (84 points in original chunk).
    Processing chunk ID: 48 for Bamberg...
      Gi* analysis successful for chunk 48 (1527 points in original chunk).
    Processing chunk ID: 38 for Bamberg...
      Gi* analysis successful for chunk 38 (86 points in original chunk).
    Processing chunk ID: 18 for Bamberg...
      Gi* analysis successful for chunk 18 (308 points in original chunk).
    Processing chunk ID: 7 for Bamberg...
      Gi* analysis successful for chunk 7 (713 points in original chunk).
    Processing chunk ID: 17 for Bamberg...
      Gi* analysis successful for chunk 17 (2071 points in original chunk).
    Processing chunk ID: 8 for Bamberg...
      Gi* analysis successful for chunk 8 (2 points in original chunk).
    Processing chunk ID: 27 for Bamberg...
      Gi* analysis successful for chunk 27 (1839 points in original chunk).
    Processing chunk ID: 28 for Bamberg...
      Gi* analysis successful for chunk 28 (119 points in original chunk).
    Processing chunk ID: 26 for Bamberg...
      Gi* analysis successful for chunk 26 (2235 points in original chunk).
    Processing chunk ID: 16 for Bamberg...
      Gi* analysis successful for chunk 16 (2060 points in original chunk).
    Processing chunk ID: 15 for Bamberg...
      Gi* analysis successful for chunk 15 (2207 points in original chunk).
    Processing chunk ID: 25 for Bamberg...
      Gi* analysis successful for chunk 25 (2208 points in original chunk).
    Processing chunk ID: 14 for Bamberg...
      Gi* analysis successful for chunk 14 (2122 points in original chunk).
    Processing chunk ID: 24 for Bamberg...
      Gi* analysis successful for chunk 24 (2211 points in original chunk).
    Processing chunk ID: 23 for Bamberg...
      Gi* analysis successful for chunk 23 (2150 points in original chunk).
    Processing chunk ID: 13 for Bamberg...
      Gi* analysis successful for chunk 13 (1235 points in original chunk).
    Processing chunk ID: 4 for Bamberg...
      Gi* analysis successful for chunk 4 (782 points in original chunk).
    Processing chunk ID: 3 for Bamberg...
      Gi* analysis successful for chunk 3 (112 points in original chunk).
    Processing chunk ID: 5 for Bamberg...
      Gi* analysis successful for chunk 5 (1486 points in original chunk).
    Processing chunk ID: 6 for Bamberg...
      Gi* analysis successful for chunk 6 (823 points in original chunk).
  Combined Gi* results for all chunks in Bamberg.

✨ Processing chunks for city: Bayreuth...
  Found 98 chunks for Bayreuth.
    Processing chunk ID: 70 for Bayreuth...
      Gi* analysis successful for chunk 70 (1714 points in original chunk).
    Processing chunk ID: 50 for Bayreuth...
      Gi* analysis successful for chunk 50 (118 points in original chunk).
    Processing chunk ID: 60 for Bayreuth...
      Gi* analysis successful for chunk 60 (1310 points in original chunk).
    Processing chunk ID: 71 for Bayreuth...
      Gi* analysis successful for chunk 71 (2216 points in original chunk).
    Processing chunk ID: 61 for Bayreuth...
      Gi* analysis successful for chunk 61 (1580 points in original chunk).
    Processing chunk ID: 72 for Bayreuth...
      Gi* analysis successful for chunk 72 (2231 points in original chunk).
    Processing chunk ID: 62 for Bayreuth...
      Gi* analysis successful for chunk 62 (1786 points in original chunk).
    Processing chunk ID: 51 for Bayreuth...
      Gi* analysis successful for chunk 51 (79 points in original chunk).
    Processing chunk ID: 43 for Bayreuth...
      Gi* analysis successful for chunk 43 (823 points in original chunk).
    Processing chunk ID: 33 for Bayreuth...
      Gi* analysis successful for chunk 33 (195 points in original chunk).
    Processing chunk ID: 34 for Bayreuth...
      Gi* analysis successful for chunk 34 (570 points in original chunk).
    Processing chunk ID: 44 for Bayreuth...
      Gi* analysis successful for chunk 44 (2200 points in original chunk).
    Processing chunk ID: 52 for Bayreuth...
      Warning: Weight matrix for buffered chunk 52 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 52 (377 points in original chunk).
    Processing chunk ID: 53 for Bayreuth...
      Gi* analysis successful for chunk 53 (1928 points in original chunk).
    Processing chunk ID: 63 for Bayreuth...
      Gi* analysis successful for chunk 63 (2287 points in original chunk).
    Processing chunk ID: 73 for Bayreuth...
      Gi* analysis successful for chunk 73 (2225 points in original chunk).
    Processing chunk ID: 64 for Bayreuth...
      Gi* analysis successful for chunk 64 (2248 points in original chunk).
    Processing chunk ID: 74 for Bayreuth...
      Gi* analysis successful for chunk 74 (2211 points in original chunk).
    Processing chunk ID: 54 for Bayreuth...
      Gi* analysis successful for chunk 54 (2206 points in original chunk).
    Processing chunk ID: 45 for Bayreuth...
      Gi* analysis successful for chunk 45 (2249 points in original chunk).
    Processing chunk ID: 55 for Bayreuth...
      Gi* analysis successful for chunk 55 (2260 points in original chunk).
    Processing chunk ID: 65 for Bayreuth...
      Gi* analysis successful for chunk 65 (2286 points in original chunk).
    Processing chunk ID: 75 for Bayreuth...
      Gi* analysis successful for chunk 75 (2280 points in original chunk).
    Processing chunk ID: 66 for Bayreuth...
      Gi* analysis successful for chunk 66 (2270 points in original chunk).
    Processing chunk ID: 76 for Bayreuth...
      Gi* analysis successful for chunk 76 (2211 points in original chunk).
    Processing chunk ID: 56 for Bayreuth...
      Gi* analysis successful for chunk 56 (2243 points in original chunk).
    Processing chunk ID: 46 for Bayreuth...
      Gi* analysis successful for chunk 46 (2232 points in original chunk).
    Processing chunk ID: 36 for Bayreuth...
      Gi* analysis successful for chunk 36 (2267 points in original chunk).
    Processing chunk ID: 35 for Bayreuth...
      Gi* analysis successful for chunk 35 (1507 points in original chunk).
    Processing chunk ID: 25 for Bayreuth...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Warning: Weight matrix for buffered chunk 25 is not fully connected (2 components).
      Gi* analysis successful for chunk 25 (175 points in original chunk).
    Processing chunk ID: 26 for Bayreuth...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Warning: Weight matrix for buffered chunk 26 is not fully connected (2 components).
      Gi* analysis successful for chunk 26 (1934 points in original chunk).
    Processing chunk ID: 18 for Bayreuth...
      Warning: Weight matrix for buffered chunk 18 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 18 (108 points in original chunk).
    Processing chunk ID: 6 for Bayreuth...
      Warning: Weight matrix for buffered chunk 6 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 6 (214 points in original chunk).
    Processing chunk ID: 7 for Bayreuth...
      Warning: Weight matrix for buffered chunk 7 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 7 (302 points in original chunk).
    Processing chunk ID: 17 for Bayreuth...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Warning: Weight matrix for buffered chunk 17 is not fully connected (2 components).
      Gi* analysis successful for chunk 17 (696 points in original chunk).
    Processing chunk ID: 8 for Bayreuth...
      Warning: Weight matrix for buffered chunk 8 is not fully connected (2 components).
      Gi* analysis successful for chunk 8 (7 points in original chunk).
    Processing chunk ID: 27 for Bayreuth...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Warning: Weight matrix for buffered chunk 27 is not fully connected (2 components).
      Gi* analysis successful for chunk 27 (1454 points in original chunk).
    Processing chunk ID: 16 for Bayreuth...
      Warning: Weight matrix for buffered chunk 16 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 16 (956 points in original chunk).
    Processing chunk ID: 37 for Bayreuth...
      Gi* analysis successful for chunk 37 (1492 points in original chunk).
    Processing chunk ID: 47 for Bayreuth...
      Gi* analysis successful for chunk 47 (1575 points in original chunk).
    Processing chunk ID: 48 for Bayreuth...
      Gi* analysis successful for chunk 48 (53 points in original chunk).
    Processing chunk ID: 58 for Bayreuth...
      Gi* analysis successful for chunk 58 (1810 points in original chunk).
    Processing chunk ID: 59 for Bayreuth...
      Gi* analysis successful for chunk 59 (230 points in original chunk).
    Processing chunk ID: 69 for Bayreuth...
      Gi* analysis successful for chunk 69 (1403 points in original chunk).
    Processing chunk ID: 79 for Bayreuth...
      Gi* analysis successful for chunk 79 (1722 points in original chunk).
    Processing chunk ID: 68 for Bayreuth...
      Gi* analysis successful for chunk 68 (2287 points in original chunk).
    Processing chunk ID: 78 for Bayreuth...
      Gi* analysis successful for chunk 78 (2265 points in original chunk).
    Processing chunk ID: 67 for Bayreuth...
      Gi* analysis successful for chunk 67 (2236 points in original chunk).
    Processing chunk ID: 77 for Bayreuth...
      Gi* analysis successful for chunk 77 (2203 points in original chunk).
    Processing chunk ID: 57 for Bayreuth...
      Gi* analysis successful for chunk 57 (2207 points in original chunk).
    Processing chunk ID: 86 for Bayreuth...
      Gi* analysis successful for chunk 86 (2211 points in original chunk).
    Processing chunk ID: 87 for Bayreuth...
      Gi* analysis successful for chunk 87 (2200 points in original chunk).
    Processing chunk ID: 96 for Bayreuth...
      Gi* analysis successful for chunk 96 (2241 points in original chunk).
    Processing chunk ID: 97 for Bayreuth...
      Gi* analysis successful for chunk 97 (2233 points in original chunk).
    Processing chunk ID: 98 for Bayreuth...
      Gi* analysis successful for chunk 98 (2297 points in original chunk).
    Processing chunk ID: 88 for Bayreuth...
      Gi* analysis successful for chunk 88 (2272 points in original chunk).
    Processing chunk ID: 89 for Bayreuth...
      Gi* analysis successful for chunk 89 (1087 points in original chunk).
    Processing chunk ID: 99 for Bayreuth...
      Gi* analysis successful for chunk 99 (322 points in original chunk).
    Processing chunk ID: 108 for Bayreuth...
      Gi* analysis successful for chunk 108 (2161 points in original chunk).
    Processing chunk ID: 109 for Bayreuth...
      Gi* analysis successful for chunk 109 (160 points in original chunk).
    Processing chunk ID: 129 for Bayreuth...
      Gi* analysis successful for chunk 129 (787 points in original chunk).
    Processing chunk ID: 119 for Bayreuth...
      Gi* analysis successful for chunk 119 (916 points in original chunk).
    Processing chunk ID: 118 for Bayreuth...
      Gi* analysis successful for chunk 118 (2130 points in original chunk).
    Processing chunk ID: 128 for Bayreuth...
      Gi* analysis successful for chunk 128 (1125 points in original chunk).
    Processing chunk ID: 117 for Bayreuth...
      Gi* analysis successful for chunk 117 (1995 points in original chunk).
    Processing chunk ID: 127 for Bayreuth...
      Gi* analysis successful for chunk 127 (515 points in original chunk).
    Processing chunk ID: 107 for Bayreuth...
      Gi* analysis successful for chunk 107 (2203 points in original chunk).
    Processing chunk ID: 106 for Bayreuth...
      Gi* analysis successful for chunk 106 (2222 points in original chunk).
    Processing chunk ID: 116 for Bayreuth...
      Gi* analysis successful for chunk 116 (2235 points in original chunk).
    Processing chunk ID: 126 for Bayreuth...
      Gi* analysis successful for chunk 126 (2138 points in original chunk).
    Processing chunk ID: 136 for Bayreuth...
      Gi* analysis successful for chunk 136 (594 points in original chunk).
    Processing chunk ID: 124 for Bayreuth...
      Gi* analysis successful for chunk 124 (27 points in original chunk).
    Processing chunk ID: 125 for Bayreuth...
      Gi* analysis successful for chunk 125 (1823 points in original chunk).
    Processing chunk ID: 135 for Bayreuth...
      Gi* analysis successful for chunk 135 (1594 points in original chunk).
    Processing chunk ID: 145 for Bayreuth...
      Gi* analysis successful for chunk 145 (166 points in original chunk).
    Processing chunk ID: 115 for Bayreuth...
      Gi* analysis successful for chunk 115 (2258 points in original chunk).
    Processing chunk ID: 105 for Bayreuth...
      Gi* analysis successful for chunk 105 (2263 points in original chunk).
    Processing chunk ID: 114 for Bayreuth...
      Gi* analysis successful for chunk 114 (1029 points in original chunk).
    Processing chunk ID: 104 for Bayreuth...
      Gi* analysis successful for chunk 104 (2210 points in original chunk).
    Processing chunk ID: 94 for Bayreuth...
      Gi* analysis successful for chunk 94 (2244 points in original chunk).
    Processing chunk ID: 95 for Bayreuth...
      Gi* analysis successful for chunk 95 (2319 points in original chunk).
    Processing chunk ID: 85 for Bayreuth...
      Gi* analysis successful for chunk 85 (2274 points in original chunk).
    Processing chunk ID: 84 for Bayreuth...
      Gi* analysis successful for chunk 84 (2214 points in original chunk).
    Processing chunk ID: 93 for Bayreuth...
      Gi* analysis successful for chunk 93 (2250 points in original chunk).
    Processing chunk ID: 83 for Bayreuth...
      Gi* analysis successful for chunk 83 (2218 points in original chunk).
    Processing chunk ID: 82 for Bayreuth...
      Gi* analysis successful for chunk 82 (2236 points in original chunk).
    Processing chunk ID: 92 for Bayreuth...
      Gi* analysis successful for chunk 92 (2266 points in original chunk).
    Processing chunk ID: 102 for Bayreuth...
      Gi* analysis successful for chunk 102 (1667 points in original chunk).
    Processing chunk ID: 103 for Bayreuth...
      Gi* analysis successful for chunk 103 (1584 points in original chunk).
    Processing chunk ID: 113 for Bayreuth...
      Gi* analysis successful for chunk 113 (1 points in original chunk).
    Processing chunk ID: 100 for Bayreuth...
      Gi* analysis successful for chunk 100 (198 points in original chunk).
    Processing chunk ID: 90 for Bayreuth...
      Gi* analysis successful for chunk 90 (791 points in original chunk).
    Processing chunk ID: 101 for Bayreuth...
      Gi* analysis successful for chunk 101 (1337 points in original chunk).
    Processing chunk ID: 91 for Bayreuth...
      Gi* analysis successful for chunk 91 (2246 points in original chunk).
    Processing chunk ID: 111 for Bayreuth...
      Gi* analysis successful for chunk 111 (1 points in original chunk).
    Processing chunk ID: 112 for Bayreuth...
      Gi* analysis successful for chunk 112 (2 points in original chunk).
    Processing chunk ID: 81 for Bayreuth...
      Gi* analysis successful for chunk 81 (2213 points in original chunk).
    Processing chunk ID: 80 for Bayreuth...
      Gi* analysis successful for chunk 80 (1008 points in original chunk).
  Combined Gi* results for all chunks in Bayreuth.

✨ Processing chunks for city: Erlangen...
  Found 90 chunks for Erlangen.
    Processing chunk ID: 12 for Erlangen...
      Gi* analysis successful for chunk 12 (10 points in original chunk).
    Processing chunk ID: 37 for Erlangen...
      Warning: Weight matrix for buffered chunk 37 is not fully connected (2 components).
      Gi* analysis successful for chunk 37 (211 points in original chunk).
    Processing chunk ID: 36 for Erlangen...
      Warning: Weight matrix for buffered chunk 36 is not fully connected (4 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)
/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 4 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 36 (370 points in original chunk).
    Processing chunk ID: 35 for Erlangen...
      Warning: Weight matrix for buffered chunk 35 is not fully connected (5 components).
      Gi* analysis successful for chunk 35 (13 points in original chunk).
    Processing chunk ID: 47 for Erlangen...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 5 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)
/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 4 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Warning: Weight matrix for buffered chunk 47 is not fully connected (4 components).
      Gi* analysis successful for chunk 47 (341 points in original chunk).
    Processing chunk ID: 60 for Erlangen...
      Gi* analysis successful for chunk 60 (2252 points in original chunk).
    Processing chunk ID: 48 for Erlangen...
      Warning: Weight matrix for buffered chunk 48 is not fully connected (4 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 4 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 48 (28 points in original chunk).
    Processing chunk ID: 61 for Erlangen...
      Gi* analysis successful for chunk 61 (274 points in original chunk).
    Processing chunk ID: 73 for Erlangen...
      Gi* analysis successful for chunk 73 (2223 points in original chunk).
    Processing chunk ID: 74 for Erlangen...
      Gi* analysis successful for chunk 74 (959 points in original chunk).
    Processing chunk ID: 100 for Erlangen...
      Gi* analysis successful for chunk 100 (577 points in original chunk).
    Processing chunk ID: 99 for Erlangen...
      Gi* analysis successful for chunk 99 (2244 points in original chunk).
    Processing chunk ID: 86 for Erlangen...
      Gi* analysis successful for chunk 86 (1943 points in original chunk).
    Processing chunk ID: 85 for Erlangen...
      Gi* analysis successful for chunk 85 (2245 points in original chunk).
    Processing chunk ID: 98 for Erlangen...
      Gi* analysis successful for chunk 98 (2207 points in original chunk).
    Processing chunk ID: 72 for Erlangen...
      Gi* analysis successful for chunk 72 (2212 points in original chunk).
    Processing chunk ID: 59 for Erlangen...
      Gi* analysis successful for chunk 59 (2213 points in original chunk).
    Processing chunk ID: 71 for Erlangen...
      Gi* analysis successful for chunk 71 (2238 points in original chunk).
    Processing chunk ID: 58 for Erlangen...
      Gi* analysis successful for chunk 58 (2221 points in original chunk).
    Processing chunk ID: 84 for Erlangen...
      Gi* analysis successful for chunk 84 (2268 points in original chunk).
    Processing chunk ID: 97 for Erlangen...
      Gi* analysis successful for chunk 97 (2232 points in original chunk).
    Processing chunk ID: 96 for Erlangen...
      Gi* analysis successful for chunk 96 (2233 points in original chunk).
    Processing chunk ID: 83 for Erlangen...
      Gi* analysis successful for chunk 83 (2272 points in original chunk).
    Processing chunk ID: 70 for Erlangen...
      Gi* analysis successful for chunk 70 (2235 points in original chunk).
    Processing chunk ID: 95 for Erlangen...
      Gi* analysis successful for chunk 95 (2050 points in original chunk).
    Processing chunk ID: 82 for Erlangen...
      Gi* analysis successful for chunk 82 (1814 points in original chunk).
    Processing chunk ID: 69 for Erlangen...
      Gi* analysis successful for chunk 69 (1528 points in original chunk).
    Processing chunk ID: 56 for Erlangen...
      Gi* analysis successful for chunk 56 (1270 points in original chunk).
    Processing chunk ID: 57 for Erlangen...
      Gi* analysis successful for chunk 57 (2234 points in original chunk).
    Processing chunk ID: 45 for Erlangen...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 4 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Warning: Weight matrix for buffered chunk 45 is not fully connected (4 components).
      Gi* analysis successful for chunk 45 (1333 points in original chunk).
    Processing chunk ID: 44 for Erlangen...
      Warning: Weight matrix for buffered chunk 44 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 44 (1697 points in original chunk).
    Processing chunk ID: 43 for Erlangen...
      Gi* analysis successful for chunk 43 (1130 points in original chunk).
    Processing chunk ID: 30 for Erlangen...
      Gi* analysis successful for chunk 30 (53 points in original chunk).
    Processing chunk ID: 31 for Erlangen...
      Gi* analysis successful for chunk 31 (8 points in original chunk).
    Processing chunk ID: 32 for Erlangen...
      Warning: Weight matrix for buffered chunk 32 is not fully connected (5 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 5 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 32 (18 points in original chunk).
    Processing chunk ID: 46 for Erlangen...
      Warning: Weight matrix for buffered chunk 46 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 46 (816 points in original chunk).
    Processing chunk ID: 33 for Erlangen...
      Warning: Weight matrix for buffered chunk 33 is not fully connected (6 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)
/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 8 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 33 (187 points in original chunk).
    Processing chunk ID: 21 for Erlangen...
      Warning: Weight matrix for buffered chunk 21 is not fully connected (8 components).
      Gi* analysis successful for chunk 21 (32 points in original chunk).
    Processing chunk ID: 20 for Erlangen...
      Warning: Weight matrix for buffered chunk 20 is not fully connected (7 components).
      Gi* analysis successful for chunk 20 (173 points in original chunk).
    Processing chunk ID: 8 for Erlangen...
      Warning: Weight matrix for buffered chunk 8 is not fully connected (5 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 7 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)
/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 5 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)
/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 4 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 8 (13 points in original chunk).
    Processing chunk ID: 7 for Erlangen...
      Warning: Weight matrix for buffered chunk 7 is not fully connected (4 components).
      Gi* analysis successful for chunk 7 (50 points in original chunk).
    Processing chunk ID: 18 for Erlangen...
      Gi* analysis successful for chunk 18 (4 points in original chunk).
    Processing chunk ID: 4 for Erlangen...
      Gi* analysis successful for chunk 4 (19 points in original chunk).
    Processing chunk ID: 23 for Erlangen...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)
/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 5 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Warning: Weight matrix for buffered chunk 23 is not fully connected (3 components).
      Gi* analysis successful for chunk 23 (50 points in original chunk).
    Processing chunk ID: 22 for Erlangen...
      Warning: Weight matrix for buffered chunk 22 is not fully connected (5 components).
      Gi* analysis successful for chunk 22 (13 points in original chunk).
    Processing chunk ID: 10 for Erlangen...
      Gi* analysis successful for chunk 10 (3 points in original chunk).
    Processing chunk ID: 9 for Erlangen...
      Warning: Weight matrix for buffered chunk 9 is not fully connected (2 components).
      Gi* analysis successful for chunk 9 (11 points in original chunk).
    Processing chunk ID: 11 for Erlangen...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)
/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 11 (29 points in original chunk).
    Processing chunk ID: 24 for Erlangen...
      Warning: Weight matrix for buffered chunk 24 is not fully connected (2 components).
      Gi* analysis successful for chunk 24 (171 points in original chunk).
    Processing chunk ID: 25 for Erlangen...
      Gi* analysis successful for chunk 25 (1 points in original chunk).
    Processing chunk ID: 3 for Erlangen...
      Gi* analysis successful for chunk 3 (1 points in original chunk).
    Processing chunk ID: 15 for Erlangen...
      Gi* analysis successful for chunk 15 (9 points in original chunk).
    Processing chunk ID: 27 for Erlangen...
      Gi* analysis successful for chunk 27 (765 points in original chunk).
    Processing chunk ID: 26 for Erlangen...
      Gi* analysis successful for chunk 26 (1033 points in original chunk).
    Processing chunk ID: 13 for Erlangen...
      Gi* analysis successful for chunk 13 (11 points in original chunk).
    Processing chunk ID: 39 for Erlangen...
      Gi* analysis successful for chunk 39 (968 points in original chunk).
    Processing chunk ID: 52 for Erlangen...
      Gi* analysis successful for chunk 52 (319 points in original chunk).
    Processing chunk ID: 40 for Erlangen...
      Gi* analysis successful for chunk 40 (1122 points in original chunk).
    Processing chunk ID: 53 for Erlangen...
      Gi* analysis successful for chunk 53 (1089 points in original chunk).
    Processing chunk ID: 54 for Erlangen...
      Gi* analysis successful for chunk 54 (1142 points in original chunk).
    Processing chunk ID: 41 for Erlangen...
      Gi* analysis successful for chunk 41 (1178 points in original chunk).
    Processing chunk ID: 28 for Erlangen...
      Gi* analysis successful for chunk 28 (553 points in original chunk).
    Processing chunk ID: 42 for Erlangen...
      Gi* analysis successful for chunk 42 (1122 points in original chunk).
    Processing chunk ID: 29 for Erlangen...
      Gi* analysis successful for chunk 29 (247 points in original chunk).
    Processing chunk ID: 55 for Erlangen...
      Gi* analysis successful for chunk 55 (1089 points in original chunk).
    Processing chunk ID: 67 for Erlangen...
      Gi* analysis successful for chunk 67 (1142 points in original chunk).
    Processing chunk ID: 80 for Erlangen...
      Gi* analysis successful for chunk 80 (1178 points in original chunk).
    Processing chunk ID: 68 for Erlangen...
      Gi* analysis successful for chunk 68 (1089 points in original chunk).
    Processing chunk ID: 81 for Erlangen...
      Gi* analysis successful for chunk 81 (1122 points in original chunk).
    Processing chunk ID: 94 for Erlangen...
      Gi* analysis successful for chunk 94 (1089 points in original chunk).
    Processing chunk ID: 93 for Erlangen...
      Gi* analysis successful for chunk 93 (1140 points in original chunk).
    Processing chunk ID: 92 for Erlangen...
      Gi* analysis successful for chunk 92 (1089 points in original chunk).
    Processing chunk ID: 79 for Erlangen...
      Gi* analysis successful for chunk 79 (1122 points in original chunk).
    Processing chunk ID: 66 for Erlangen...
      Gi* analysis successful for chunk 66 (1089 points in original chunk).
    Processing chunk ID: 78 for Erlangen...
      Gi* analysis successful for chunk 78 (354 points in original chunk).
    Processing chunk ID: 65 for Erlangen...
      Gi* analysis successful for chunk 65 (181 points in original chunk).
    Processing chunk ID: 91 for Erlangen...
      Gi* analysis successful for chunk 91 (517 points in original chunk).
    Processing chunk ID: 105 for Erlangen...
      Gi* analysis successful for chunk 105 (477 points in original chunk).
    Processing chunk ID: 104 for Erlangen...
      Gi* analysis successful for chunk 104 (99 points in original chunk).
    Processing chunk ID: 106 for Erlangen...
      Gi* analysis successful for chunk 106 (262 points in original chunk).
    Processing chunk ID: 107 for Erlangen...
      Gi* analysis successful for chunk 107 (226 points in original chunk).
    Processing chunk ID: 108 for Erlangen...
      Gi* analysis successful for chunk 108 (197 points in original chunk).
    Processing chunk ID: 109 for Erlangen...
      Gi* analysis successful for chunk 109 (414 points in original chunk).
    Processing chunk ID: 110 for Erlangen...
      Gi* analysis successful for chunk 110 (1376 points in original chunk).
    Processing chunk ID: 125 for Erlangen...
      Gi* analysis successful for chunk 125 (278 points in original chunk).
    Processing chunk ID: 124 for Erlangen...
      Gi* analysis successful for chunk 124 (485 points in original chunk).
    Processing chunk ID: 112 for Erlangen...
      Gi* analysis successful for chunk 112 (1910 points in original chunk).
    Processing chunk ID: 111 for Erlangen...
      Gi* analysis successful for chunk 111 (2217 points in original chunk).
    Processing chunk ID: 123 for Erlangen...
      Gi* analysis successful for chunk 123 (6 points in original chunk).
    Processing chunk ID: 113 for Erlangen...
      Gi* analysis successful for chunk 113 (266 points in original chunk).
  Combined Gi* results for all chunks in Erlangen.

✨ Processing chunks for city: Fürth...
  Found 74 chunks for Fürth.
    Processing chunk ID: 7 for Fürth...
      Gi* analysis successful for chunk 7 (14 points in original chunk).
    Processing chunk ID: 19 for Fürth...
      Gi* analysis successful for chunk 19 (1017 points in original chunk).
    Processing chunk ID: 6 for Fürth...
      Gi* analysis successful for chunk 6 (125 points in original chunk).
    Processing chunk ID: 18 for Fürth...
      Gi* analysis successful for chunk 18 (1126 points in original chunk).
    Processing chunk ID: 30 for Fürth...
      Gi* analysis successful for chunk 30 (1125 points in original chunk).
    Processing chunk ID: 31 for Fürth...
      Gi* analysis successful for chunk 31 (1094 points in original chunk).
    Processing chunk ID: 20 for Fürth...
      Gi* analysis successful for chunk 20 (712 points in original chunk).
    Processing chunk ID: 32 for Fürth...
      Gi* analysis successful for chunk 32 (1089 points in original chunk).
    Processing chunk ID: 21 for Fürth...
      Gi* analysis successful for chunk 21 (509 points in original chunk).
    Processing chunk ID: 33 for Fürth...
      Gi* analysis successful for chunk 33 (1127 points in original chunk).
    Processing chunk ID: 34 for Fürth...
      Gi* analysis successful for chunk 34 (794 points in original chunk).
    Processing chunk ID: 22 for Fürth...
      Gi* analysis successful for chunk 22 (178 points in original chunk).
    Processing chunk ID: 46 for Fürth...
      Gi* analysis successful for chunk 46 (950 points in original chunk).
    Processing chunk ID: 47 for Fürth...
      Gi* analysis successful for chunk 47 (105 points in original chunk).
    Processing chunk ID: 59 for Fürth...
      Gi* analysis successful for chunk 59 (429 points in original chunk).
    Processing chunk ID: 58 for Fürth...
      Gi* analysis successful for chunk 58 (1089 points in original chunk).
    Processing chunk ID: 71 for Fürth...
      Gi* analysis successful for chunk 71 (37 points in original chunk).
    Processing chunk ID: 70 for Fürth...
      Gi* analysis successful for chunk 70 (378 points in original chunk).
    Processing chunk ID: 81 for Fürth...
      Warning: Weight matrix for buffered chunk 81 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 81 (16 points in original chunk).
    Processing chunk ID: 69 for Fürth...
      Gi* analysis successful for chunk 69 (900 points in original chunk).
    Processing chunk ID: 68 for Fürth...
      Gi* analysis successful for chunk 68 (1028 points in original chunk).
    Processing chunk ID: 56 for Fürth...
      Gi* analysis successful for chunk 56 (1122 points in original chunk).
    Processing chunk ID: 57 for Fürth...
      Gi* analysis successful for chunk 57 (1100 points in original chunk).
    Processing chunk ID: 45 for Fürth...
      Gi* analysis successful for chunk 45 (1131 points in original chunk).
    Processing chunk ID: 44 for Fürth...
      Gi* analysis successful for chunk 44 (1149 points in original chunk).
    Processing chunk ID: 55 for Fürth...
      Gi* analysis successful for chunk 55 (1095 points in original chunk).
    Processing chunk ID: 43 for Fürth...
      Gi* analysis successful for chunk 43 (1126 points in original chunk).
    Processing chunk ID: 42 for Fürth...
      Gi* analysis successful for chunk 42 (1164 points in original chunk).
    Processing chunk ID: 54 for Fürth...
      Gi* analysis successful for chunk 54 (1098 points in original chunk).
    Processing chunk ID: 66 for Fürth...
      Gi* analysis successful for chunk 66 (1099 points in original chunk).
    Processing chunk ID: 67 for Fürth...
      Gi* analysis successful for chunk 67 (1093 points in original chunk).
    Processing chunk ID: 78 for Fürth...
      Gi* analysis successful for chunk 78 (1127 points in original chunk).
    Processing chunk ID: 79 for Fürth...
      Gi* analysis successful for chunk 79 (1123 points in original chunk).
    Processing chunk ID: 80 for Fürth...
      Gi* analysis successful for chunk 80 (272 points in original chunk).
    Processing chunk ID: 92 for Fürth...
      Gi* analysis successful for chunk 92 (161 points in original chunk).
    Processing chunk ID: 91 for Fürth...
      Gi* analysis successful for chunk 91 (690 points in original chunk).
    Processing chunk ID: 90 for Fürth...
      Gi* analysis successful for chunk 90 (180 points in original chunk).
    Processing chunk ID: 89 for Fürth...
      Gi* analysis successful for chunk 89 (528 points in original chunk).
    Processing chunk ID: 88 for Fürth...
      Gi* analysis successful for chunk 88 (924 points in original chunk).
    Processing chunk ID: 60 for Fürth...
      Gi* analysis successful for chunk 60 (709 points in original chunk).
    Processing chunk ID: 61 for Fürth...
      Gi* analysis successful for chunk 61 (1013 points in original chunk).
    Processing chunk ID: 72 for Fürth...
      Gi* analysis successful for chunk 72 (3 points in original chunk).
    Processing chunk ID: 73 for Fürth...
      Gi* analysis successful for chunk 73 (236 points in original chunk).
    Processing chunk ID: 74 for Fürth...
      Gi* analysis successful for chunk 74 (872 points in original chunk).
    Processing chunk ID: 62 for Fürth...
      Gi* analysis successful for chunk 62 (1126 points in original chunk).
    Processing chunk ID: 50 for Fürth...
      Gi* analysis successful for chunk 50 (1102 points in original chunk).
    Processing chunk ID: 49 for Fürth...
      Gi* analysis successful for chunk 49 (382 points in original chunk).
    Processing chunk ID: 38 for Fürth...
      Gi* analysis successful for chunk 38 (771 points in original chunk).
    Processing chunk ID: 37 for Fürth...
      Gi* analysis successful for chunk 37 (17 points in original chunk).
    Processing chunk ID: 26 for Fürth...
      Gi* analysis successful for chunk 26 (671 points in original chunk).
    Processing chunk ID: 39 for Fürth...
      Gi* analysis successful for chunk 39 (1190 points in original chunk).
    Processing chunk ID: 27 for Fürth...
      Gi* analysis successful for chunk 27 (1158 points in original chunk).
    Processing chunk ID: 28 for Fürth...
      Gi* analysis successful for chunk 28 (1110 points in original chunk).
    Processing chunk ID: 40 for Fürth...
      Gi* analysis successful for chunk 40 (1136 points in original chunk).
    Processing chunk ID: 51 for Fürth...
      Gi* analysis successful for chunk 51 (1144 points in original chunk).
    Processing chunk ID: 52 for Fürth...
      Gi* analysis successful for chunk 52 (1110 points in original chunk).
    Processing chunk ID: 63 for Fürth...
      Gi* analysis successful for chunk 63 (1128 points in original chunk).
    Processing chunk ID: 75 for Fürth...
      Gi* analysis successful for chunk 75 (1102 points in original chunk).
    Processing chunk ID: 87 for Fürth...
      Gi* analysis successful for chunk 87 (133 points in original chunk).
    Processing chunk ID: 76 for Fürth...
      Gi* analysis successful for chunk 76 (1143 points in original chunk).
    Processing chunk ID: 64 for Fürth...
      Gi* analysis successful for chunk 64 (1115 points in original chunk).
    Processing chunk ID: 53 for Fürth...
      Gi* analysis successful for chunk 53 (1125 points in original chunk).
    Processing chunk ID: 65 for Fürth...
      Gi* analysis successful for chunk 65 (1127 points in original chunk).
    Processing chunk ID: 77 for Fürth...
      Gi* analysis successful for chunk 77 (1165 points in original chunk).
    Processing chunk ID: 41 for Fürth...
      Gi* analysis successful for chunk 41 (1132 points in original chunk).
    Processing chunk ID: 29 for Fürth...
      Gi* analysis successful for chunk 29 (1094 points in original chunk).
    Processing chunk ID: 17 for Fürth...
      Gi* analysis successful for chunk 17 (1102 points in original chunk).
    Processing chunk ID: 5 for Fürth...
      Gi* analysis successful for chunk 5 (417 points in original chunk).
    Processing chunk ID: 16 for Fürth...
      Gi* analysis successful for chunk 16 (1107 points in original chunk).
    Processing chunk ID: 4 for Fürth...
      Gi* analysis successful for chunk 4 (645 points in original chunk).
    Processing chunk ID: 15 for Fürth...
      Gi* analysis successful for chunk 15 (1155 points in original chunk).
    Processing chunk ID: 14 for Fürth...
      Gi* analysis successful for chunk 14 (623 points in original chunk).
    Processing chunk ID: 3 for Fürth...
      Gi* analysis successful for chunk 3 (974 points in original chunk).
    Processing chunk ID: 2 for Fürth...
      Gi* analysis successful for chunk 2 (284 points in original chunk).
  Combined Gi* results for all chunks in Fürth.

✨ Processing chunks for city: Ingolstadt...
  Found 167 chunks for Ingolstadt.
    Processing chunk ID: 55 for Ingolstadt...
      Gi* analysis successful for chunk 55 (985 points in original chunk).
    Processing chunk ID: 39 for Ingolstadt...
      Gi* analysis successful for chunk 39 (300 points in original chunk).
    Processing chunk ID: 24 for Ingolstadt...
      Gi* analysis successful for chunk 24 (625 points in original chunk).
    Processing chunk ID: 40 for Ingolstadt...
      Gi* analysis successful for chunk 40 (1079 points in original chunk).
    Processing chunk ID: 56 for Ingolstadt...
      Gi* analysis successful for chunk 56 (1127 points in original chunk).
    Processing chunk ID: 25 for Ingolstadt...
      Gi* analysis successful for chunk 25 (1144 points in original chunk).
    Processing chunk ID: 9 for Ingolstadt...
      Gi* analysis successful for chunk 9 (322 points in original chunk).
    Processing chunk ID: 41 for Ingolstadt...
      Gi* analysis successful for chunk 41 (1141 points in original chunk).
    Processing chunk ID: 57 for Ingolstadt...
      Gi* analysis successful for chunk 57 (1178 points in original chunk).
    Processing chunk ID: 26 for Ingolstadt...
      Gi* analysis successful for chunk 26 (1089 points in original chunk).
    Processing chunk ID: 42 for Ingolstadt...
      Gi* analysis successful for chunk 42 (1089 points in original chunk).
    Processing chunk ID: 58 for Ingolstadt...
      Gi* analysis successful for chunk 58 (923 points in original chunk).
    Processing chunk ID: 10 for Ingolstadt...
      Gi* analysis successful for chunk 10 (805 points in original chunk).
    Processing chunk ID: 11 for Ingolstadt...
      Gi* analysis successful for chunk 11 (303 points in original chunk).
    Processing chunk ID: 27 for Ingolstadt...
      Gi* analysis successful for chunk 27 (502 points in original chunk).
    Processing chunk ID: 43 for Ingolstadt...
      Gi* analysis successful for chunk 43 (130 points in original chunk).
    Processing chunk ID: 159 for Ingolstadt...
      Gi* analysis successful for chunk 159 (4 points in original chunk).
    Processing chunk ID: 175 for Ingolstadt...
      Gi* analysis successful for chunk 175 (244 points in original chunk).
    Processing chunk ID: 206 for Ingolstadt...
      Gi* analysis successful for chunk 206 (240 points in original chunk).
    Processing chunk ID: 190 for Ingolstadt...
      Gi* analysis successful for chunk 190 (682 points in original chunk).
    Processing chunk ID: 174 for Ingolstadt...
      Gi* analysis successful for chunk 174 (1102 points in original chunk).
    Processing chunk ID: 189 for Ingolstadt...
      Gi* analysis successful for chunk 189 (1093 points in original chunk).
    Processing chunk ID: 173 for Ingolstadt...
      Gi* analysis successful for chunk 173 (1100 points in original chunk).
    Processing chunk ID: 205 for Ingolstadt...
      Gi* analysis successful for chunk 205 (941 points in original chunk).
    Processing chunk ID: 221 for Ingolstadt...
      Gi* analysis successful for chunk 221 (283 points in original chunk).
    Processing chunk ID: 220 for Ingolstadt...
      Gi* analysis successful for chunk 220 (1129 points in original chunk).
    Processing chunk ID: 204 for Ingolstadt...
      Gi* analysis successful for chunk 204 (1146 points in original chunk).
    Processing chunk ID: 188 for Ingolstadt...
      Gi* analysis successful for chunk 188 (1124 points in original chunk).
    Processing chunk ID: 219 for Ingolstadt...
      Gi* analysis successful for chunk 219 (1154 points in original chunk).
    Processing chunk ID: 203 for Ingolstadt...
      Gi* analysis successful for chunk 203 (1180 points in original chunk).
    Processing chunk ID: 187 for Ingolstadt...
      Gi* analysis successful for chunk 187 (1146 points in original chunk).
    Processing chunk ID: 186 for Ingolstadt...
      Gi* analysis successful for chunk 186 (1089 points in original chunk).
    Processing chunk ID: 171 for Ingolstadt...
      Gi* analysis successful for chunk 171 (1149 points in original chunk).
    Processing chunk ID: 170 for Ingolstadt...
      Gi* analysis successful for chunk 170 (1089 points in original chunk).
    Processing chunk ID: 172 for Ingolstadt...
      Gi* analysis successful for chunk 172 (1118 points in original chunk).
    Processing chunk ID: 156 for Ingolstadt...
      Gi* analysis successful for chunk 156 (655 points in original chunk).
    Processing chunk ID: 155 for Ingolstadt...
      Gi* analysis successful for chunk 155 (294 points in original chunk).
    Processing chunk ID: 154 for Ingolstadt...
      Gi* analysis successful for chunk 154 (929 points in original chunk).
    Processing chunk ID: 157 for Ingolstadt...
      Gi* analysis successful for chunk 157 (184 points in original chunk).
    Processing chunk ID: 158 for Ingolstadt...
      Gi* analysis successful for chunk 158 (255 points in original chunk).
    Processing chunk ID: 74 for Ingolstadt...
      Gi* analysis successful for chunk 74 (893 points in original chunk).
    Processing chunk ID: 75 for Ingolstadt...
      Gi* analysis successful for chunk 75 (39 points in original chunk).
    Processing chunk ID: 91 for Ingolstadt...
      Gi* analysis successful for chunk 91 (74 points in original chunk).
    Processing chunk ID: 90 for Ingolstadt...
      Gi* analysis successful for chunk 90 (1049 points in original chunk).
    Processing chunk ID: 107 for Ingolstadt...
      Gi* analysis successful for chunk 107 (37 points in original chunk).
    Processing chunk ID: 106 for Ingolstadt...
      Gi* analysis successful for chunk 106 (980 points in original chunk).
    Processing chunk ID: 138 for Ingolstadt...
      Gi* analysis successful for chunk 138 (819 points in original chunk).
    Processing chunk ID: 122 for Ingolstadt...
      Gi* analysis successful for chunk 122 (647 points in original chunk).
    Processing chunk ID: 121 for Ingolstadt...
      Gi* analysis successful for chunk 121 (1148 points in original chunk).
    Processing chunk ID: 105 for Ingolstadt...
      Gi* analysis successful for chunk 105 (1178 points in original chunk).
    Processing chunk ID: 137 for Ingolstadt...
      Gi* analysis successful for chunk 137 (1149 points in original chunk).
    Processing chunk ID: 136 for Ingolstadt...
      Gi* analysis successful for chunk 136 (1091 points in original chunk).
    Processing chunk ID: 120 for Ingolstadt...
      Gi* analysis successful for chunk 120 (1097 points in original chunk).
    Processing chunk ID: 104 for Ingolstadt...
      Gi* analysis successful for chunk 104 (1129 points in original chunk).
    Processing chunk ID: 89 for Ingolstadt...
      Gi* analysis successful for chunk 89 (1137 points in original chunk).
    Processing chunk ID: 88 for Ingolstadt...
      Gi* analysis successful for chunk 88 (1097 points in original chunk).
    Processing chunk ID: 73 for Ingolstadt...
      Gi* analysis successful for chunk 73 (1142 points in original chunk).
    Processing chunk ID: 72 for Ingolstadt...
      Gi* analysis successful for chunk 72 (1096 points in original chunk).
    Processing chunk ID: 87 for Ingolstadt...
      Gi* analysis successful for chunk 87 (1089 points in original chunk).
    Processing chunk ID: 71 for Ingolstadt...
      Gi* analysis successful for chunk 71 (1089 points in original chunk).
    Processing chunk ID: 54 for Ingolstadt...
      Gi* analysis successful for chunk 54 (198 points in original chunk).
    Processing chunk ID: 70 for Ingolstadt...
      Gi* analysis successful for chunk 70 (1090 points in original chunk).
    Processing chunk ID: 86 for Ingolstadt...
      Gi* analysis successful for chunk 86 (1148 points in original chunk).
    Processing chunk ID: 102 for Ingolstadt...
      Gi* analysis successful for chunk 102 (1193 points in original chunk).
    Processing chunk ID: 103 for Ingolstadt...
      Gi* analysis successful for chunk 103 (1122 points in original chunk).
    Processing chunk ID: 119 for Ingolstadt...
      Gi* analysis successful for chunk 119 (1089 points in original chunk).
    Processing chunk ID: 135 for Ingolstadt...
      Gi* analysis successful for chunk 135 (1089 points in original chunk).
    Processing chunk ID: 118 for Ingolstadt...
      Gi* analysis successful for chunk 118 (1160 points in original chunk).
    Processing chunk ID: 134 for Ingolstadt...
      Gi* analysis successful for chunk 134 (1154 points in original chunk).
    Processing chunk ID: 151 for Ingolstadt...
      Gi* analysis successful for chunk 151 (1123 points in original chunk).
    Processing chunk ID: 150 for Ingolstadt...
      Gi* analysis successful for chunk 150 (1165 points in original chunk).
    Processing chunk ID: 167 for Ingolstadt...
      Gi* analysis successful for chunk 167 (1089 points in original chunk).
    Processing chunk ID: 166 for Ingolstadt...
      Gi* analysis successful for chunk 166 (1113 points in original chunk).
    Processing chunk ID: 152 for Ingolstadt...
      Gi* analysis successful for chunk 152 (1164 points in original chunk).
    Processing chunk ID: 168 for Ingolstadt...
      Gi* analysis successful for chunk 168 (1132 points in original chunk).
    Processing chunk ID: 153 for Ingolstadt...
      Gi* analysis successful for chunk 153 (1149 points in original chunk).
    Processing chunk ID: 169 for Ingolstadt...
      Gi* analysis successful for chunk 169 (1108 points in original chunk).
    Processing chunk ID: 184 for Ingolstadt...
      Gi* analysis successful for chunk 184 (1128 points in original chunk).
    Processing chunk ID: 185 for Ingolstadt...
      Gi* analysis successful for chunk 185 (1100 points in original chunk).
    Processing chunk ID: 201 for Ingolstadt...
      Gi* analysis successful for chunk 201 (1143 points in original chunk).
    Processing chunk ID: 202 for Ingolstadt...
      Gi* analysis successful for chunk 202 (1122 points in original chunk).
    Processing chunk ID: 218 for Ingolstadt...
      Gi* analysis successful for chunk 218 (1089 points in original chunk).
    Processing chunk ID: 217 for Ingolstadt...
      Gi* analysis successful for chunk 217 (1114 points in original chunk).
    Processing chunk ID: 200 for Ingolstadt...
      Gi* analysis successful for chunk 200 (1165 points in original chunk).
    Processing chunk ID: 216 for Ingolstadt...
      Gi* analysis successful for chunk 216 (1134 points in original chunk).
    Processing chunk ID: 215 for Ingolstadt...
      Gi* analysis successful for chunk 215 (1089 points in original chunk).
    Processing chunk ID: 199 for Ingolstadt...
      Gi* analysis successful for chunk 199 (1122 points in original chunk).
    Processing chunk ID: 183 for Ingolstadt...
      Gi* analysis successful for chunk 183 (1089 points in original chunk).
    Processing chunk ID: 182 for Ingolstadt...
      Gi* analysis successful for chunk 182 (1127 points in original chunk).
    Processing chunk ID: 198 for Ingolstadt...
      Gi* analysis successful for chunk 198 (1155 points in original chunk).
    Processing chunk ID: 214 for Ingolstadt...
      Gi* analysis successful for chunk 214 (1116 points in original chunk).
    Processing chunk ID: 230 for Ingolstadt...
      Gi* analysis successful for chunk 230 (1123 points in original chunk).
    Processing chunk ID: 231 for Ingolstadt...
      Gi* analysis successful for chunk 231 (1089 points in original chunk).
    Processing chunk ID: 232 for Ingolstadt...
      Gi* analysis successful for chunk 232 (1126 points in original chunk).
    Processing chunk ID: 248 for Ingolstadt...
      Gi* analysis successful for chunk 248 (1165 points in original chunk).
    Processing chunk ID: 247 for Ingolstadt...
      Gi* analysis successful for chunk 247 (1122 points in original chunk).
    Processing chunk ID: 246 for Ingolstadt...
      Gi* analysis successful for chunk 246 (1149 points in original chunk).
    Processing chunk ID: 262 for Ingolstadt...
      Gi* analysis successful for chunk 262 (1122 points in original chunk).
    Processing chunk ID: 263 for Ingolstadt...
      Gi* analysis successful for chunk 263 (1089 points in original chunk).
    Processing chunk ID: 264 for Ingolstadt...
      Gi* analysis successful for chunk 264 (1132 points in original chunk).
    Processing chunk ID: 279 for Ingolstadt...
      Gi* analysis successful for chunk 279 (688 points in original chunk).
    Processing chunk ID: 280 for Ingolstadt...
      Gi* analysis successful for chunk 280 (812 points in original chunk).
    Processing chunk ID: 278 for Ingolstadt...
      Gi* analysis successful for chunk 278 (273 points in original chunk).
    Processing chunk ID: 296 for Ingolstadt...
      Gi* analysis successful for chunk 296 (44 points in original chunk).
    Processing chunk ID: 297 for Ingolstadt...
      Gi* analysis successful for chunk 297 (98 points in original chunk).
    Processing chunk ID: 281 for Ingolstadt...
      Gi* analysis successful for chunk 281 (1096 points in original chunk).
    Processing chunk ID: 265 for Ingolstadt...
      Gi* analysis successful for chunk 265 (1113 points in original chunk).
    Processing chunk ID: 249 for Ingolstadt...
      Gi* analysis successful for chunk 249 (1149 points in original chunk).
    Processing chunk ID: 250 for Ingolstadt...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 100 (458 points in original chunk).
    Processing chunk ID: 84 for Ingolstadt...
      Gi* analysis successful for chunk 84 (836 points in original chunk).
    Processing chunk ID: 85 for Ingolstadt...
      Gi* analysis successful for chunk 85 (1126 points in original chunk).
    Processing chunk ID: 69 for Ingolstadt...
      Gi* analysis successful for chunk 69 (764 points in original chunk).
    Processing chunk ID: 68 for Ingolstadt...
      Gi* analysis successful for chunk 68 (127 points in original chunk).
    Processing chunk ID: 115 for Ingolstadt...
      Warning: Weight matrix for buffered chunk 115 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 115 (480 points in original chunk).
    Processing chunk ID: 114 for Ingolstadt...
      Gi* analysis successful for chunk 114 (140 points in original chunk).
    Processing chunk ID: 160 for Ingolstadt...
      Gi* analysis successful for chunk 160 (598 points in original chunk).
    Processing chunk ID: 144 for Ingolstadt...
      Gi* analysis successful for chunk 144 (735 points in original chunk).
    Processing chunk ID: 145 for Ingolstadt...
      Gi* analysis successful for chunk 145 (1124 points in original chunk).
    Processing chunk ID: 129 for Ingolstadt...
      Gi* analysis successful for chunk 129 (167 points in original chunk).
    Processing chunk ID: 161 for Ingolstadt...
      Gi* analysis successful for chunk 161 (1048 points in original chunk).
    Processing chunk ID: 177 for Ingolstadt...
      Gi* analysis successful for chunk 177 (958 points in original chunk).
    Processing chunk ID: 193 for Ingolstadt...
      Gi* analysis successful for chunk 193 (597 points in original chunk).
    Processing chunk ID: 209 for Ingolstadt...
      Gi* analysis successful for chunk 209 (103 points in original chunk).
  Combined Gi* results for all chunks in Ingolstadt.

✨ Processing chunks for city: Kempten (Allgäu)...
  Found 87 chunks for Kempten (Allgäu).
    Processing chunk ID: 11 for Kempten (Allgäu)...
      Warning: Weight matrix for buffered chunk 11 is not fully connected (2 components).
      Gi* analysis successful for chunk 11 (255 points in original chunk).
    Processing chunk ID: 12 for Kempten (Allgäu)...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 12 (416 points in original chunk).
    Processing chunk ID: 13 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 13 (5 points in original chunk).
    Processing chunk ID: 14 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 14 (6 points in original chunk).
    Processing chunk ID: 6 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 6 (226 points in original chunk).
    Processing chunk ID: 7 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 7 (815 points in original chunk).
    Processing chunk ID: 8 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 8 (332 points in original chunk).
    Processing chunk ID: 17 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 17 (1088 points in original chunk).
    Processing chunk ID: 18 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 18 (504 points in original chunk).
    Processing chunk ID: 16 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 16 (335 points in original chunk).
    Processing chunk ID: 25 for Kempten (Allgäu)...
      Warning: Weight matrix for buffered chunk 25 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 25 (946 points in original chunk).
    Processing chunk ID: 24 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 24 (366 points in original chunk).
    Processing chunk ID: 34 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 34 (1122 points in original chunk).
    Processing chunk ID: 35 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 35 (1156 points in original chunk).
    Processing chunk ID: 44 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 44 (1089 points in original chunk).
    Processing chunk ID: 45 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 45 (1122 points in original chunk).
    Processing chunk ID: 46 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 46 (1089 points in original chunk).
    Processing chunk ID: 36 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 36 (1122 points in original chunk).
    Processing chunk ID: 26 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 26 (1035 points in original chunk).
    Processing chunk ID: 27 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 27 (1089 points in original chunk).
    Processing chunk ID: 37 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 37 (1122 points in original chunk).
    Processing chunk ID: 28 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 28 (626 points in original chunk).
    Processing chunk ID: 38 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 38 (1024 points in original chunk).
    Processing chunk ID: 47 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 47 (1089 points in original chunk).
    Processing chunk ID: 48 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 48 (536 points in original chunk).
    Processing chunk ID: 56 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 56 (1089 points in original chunk).
    Processing chunk ID: 57 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 57 (1089 points in original chunk).
    Processing chunk ID: 58 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 58 (155 points in original chunk).
    Processing chunk ID: 67 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 67 (1122 points in original chunk).
    Processing chunk ID: 68 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 68 (567 points in original chunk).
    Processing chunk ID: 78 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 78 (157 points in original chunk).
    Processing chunk ID: 77 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 77 (1089 points in original chunk).
    Processing chunk ID: 76 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 76 (1089 points in original chunk).
    Processing chunk ID: 66 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 66 (1115 points in original chunk).
    Processing chunk ID: 65 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 65 (1036 points in original chunk).
    Processing chunk ID: 75 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 75 (1122 points in original chunk).
    Processing chunk ID: 55 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 55 (1122 points in original chunk).
    Processing chunk ID: 54 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 54 (1089 points in original chunk).
    Processing chunk ID: 64 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 64 (1122 points in original chunk).
    Processing chunk ID: 74 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 74 (1089 points in original chunk).
    Processing chunk ID: 63 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 63 (1122 points in original chunk).
    Processing chunk ID: 73 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 73 (1089 points in original chunk).
    Processing chunk ID: 53 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 53 (1089 points in original chunk).
    Processing chunk ID: 72 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 72 (1122 points in original chunk).
    Processing chunk ID: 62 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 62 (1156 points in original chunk).
    Processing chunk ID: 52 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 52 (1122 points in original chunk).
    Processing chunk ID: 42 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 42 (1122 points in original chunk).
    Processing chunk ID: 43 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 43 (1089 points in original chunk).
    Processing chunk ID: 33 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 33 (1122 points in original chunk).
    Processing chunk ID: 23 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 23 (671 points in original chunk).
    Processing chunk ID: 32 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 32 (1156 points in original chunk).
    Processing chunk ID: 22 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 22 (1020 points in original chunk).
    Processing chunk ID: 41 for Kempten (Allgäu)...
      Warning: Weight matrix for buffered chunk 41 is not fully connected (3 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 41 (1001 points in original chunk).
    Processing chunk ID: 31 for Kempten (Allgäu)...
      Warning: Weight matrix for buffered chunk 31 is not fully connected (3 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 31 (525 points in original chunk).
    Processing chunk ID: 21 for Kempten (Allgäu)...
      Warning: Weight matrix for buffered chunk 21 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 21 (125 points in original chunk).
    Processing chunk ID: 30 for Kempten (Allgäu)...
      Warning: Weight matrix for buffered chunk 30 is not fully connected (3 components).
      Gi* analysis successful for chunk 30 (67 points in original chunk).
    Processing chunk ID: 20 for Kempten (Allgäu)...
      Warning: Weight matrix for buffered chunk 20 is not fully connected (3 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)
/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 20 (36 points in original chunk).
    Processing chunk ID: 40 for Kempten (Allgäu)...
      Warning: Weight matrix for buffered chunk 40 is not fully connected (3 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 40 (271 points in original chunk).
    Processing chunk ID: 50 for Kempten (Allgäu)...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Warning: Weight matrix for buffered chunk 50 is not fully connected (2 components).
      Gi* analysis successful for chunk 50 (678 points in original chunk).
    Processing chunk ID: 51 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 51 (1089 points in original chunk).
    Processing chunk ID: 61 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 61 (1122 points in original chunk).
    Processing chunk ID: 71 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 71 (842 points in original chunk).
    Processing chunk ID: 70 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 70 (50 points in original chunk).
    Processing chunk ID: 60 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 60 (861 points in original chunk).
    Processing chunk ID: 92 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 92 (1036 points in original chunk).
    Processing chunk ID: 82 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 82 (1111 points in original chunk).
    Processing chunk ID: 81 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 81 (92 points in original chunk).
    Processing chunk ID: 83 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 83 (1089 points in original chunk).
    Processing chunk ID: 84 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 84 (1089 points in original chunk).
    Processing chunk ID: 93 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 93 (965 points in original chunk).
    Processing chunk ID: 94 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 94 (923 points in original chunk).
    Processing chunk ID: 102 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 102 (457 points in original chunk).
    Processing chunk ID: 103 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 103 (33 points in original chunk).
    Processing chunk ID: 101 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 101 (9 points in original chunk).
    Processing chunk ID: 107 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 107 (354 points in original chunk).
    Processing chunk ID: 97 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 97 (885 points in original chunk).
    Processing chunk ID: 106 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 106 (876 points in original chunk).
    Processing chunk ID: 96 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 96 (1122 points in original chunk).
    Processing chunk ID: 104 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 104 (59 points in original chunk).
    Processing chunk ID: 95 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 95 (1156 points in original chunk).
    Processing chunk ID: 105 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 105 (477 points in original chunk).
    Processing chunk ID: 86 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 86 (1089 points in original chunk).
    Processing chunk ID: 85 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 85 (1122 points in original chunk).
    Processing chunk ID: 87 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 87 (1044 points in original chunk).
    Processing chunk ID: 88 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 88 (187 points in original chunk).
    Processing chunk ID: 49 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 49 (110 points in original chunk).
    Processing chunk ID: 39 for Kempten (Allgäu)...
      Gi* analysis successful for chunk 39 (40 points in original chunk).
  Combined Gi* results for all chunks in Kempten (Allgäu).

✨ Processing chunks for city: Landshut...
  Found 102 chunks for Landshut.
    Processing chunk ID: 208 for Landshut...
      Gi* analysis successful for chunk 208 (932 points in original chunk).
    Processing chunk ID: 197 for Landshut...
      Gi* analysis successful for chunk 197 (1013 points in original chunk).
    Processing chunk ID: 1 for Landshut...
      Gi* analysis successful for chunk 1 (1058 points in original chunk).
    Processing chunk ID: 12 for Landshut...
      Gi* analysis successful for chunk 12 (1595 points in original chunk).
    Processing chunk ID: 13 for Landshut...
      Gi* analysis successful for chunk 13 (152 points in original chunk).
    Processing chunk ID: 23 for Landshut...
      Gi* analysis successful for chunk 23 (2250 points in original chunk).
    Processing chunk ID: 24 for Landshut...
      Gi* analysis successful for chunk 24 (957 points in original chunk).
    Processing chunk ID: 84 for Landshut...
      Gi* analysis successful for chunk 84 (617 points in original chunk).
    Processing chunk ID: 83 for Landshut...
      Gi* analysis successful for chunk 83 (776 points in original chunk).
    Processing chunk ID: 82 for Landshut...
      Gi* analysis successful for chunk 82 (1864 points in original chunk).
    Processing chunk ID: 81 for Landshut...
      Gi* analysis successful for chunk 81 (2071 points in original chunk).
    Processing chunk ID: 92 for Landshut...
      Gi* analysis successful for chunk 92 (2246 points in original chunk).
    Processing chunk ID: 80 for Landshut...
      Gi* analysis successful for chunk 80 (2213 points in original chunk).
    Processing chunk ID: 91 for Landshut...
      Gi* analysis successful for chunk 91 (2239 points in original chunk).
    Processing chunk ID: 69 for Landshut...
      Gi* analysis successful for chunk 69 (2219 points in original chunk).
    Processing chunk ID: 70 for Landshut...
      Gi* analysis successful for chunk 70 (1266 points in original chunk).
    Processing chunk ID: 59 for Landshut...
      Gi* analysis successful for chunk 59 (419 points in original chunk).
    Processing chunk ID: 58 for Landshut...
      Gi* analysis successful for chunk 58 (2250 points in original chunk).
    Processing chunk ID: 47 for Landshut...
      Gi* analysis successful for chunk 47 (1640 points in original chunk).
    Processing chunk ID: 57 for Landshut...
      Gi* analysis successful for chunk 57 (2273 points in original chunk).
    Processing chunk ID: 46 for Landshut...
      Gi* analysis successful for chunk 46 (2242 points in original chunk).
    Processing chunk ID: 36 for Landshut...
      Gi* analysis successful for chunk 36 (573 points in original chunk).
    Processing chunk ID: 35 for Landshut...
      Gi* analysis successful for chunk 35 (1869 points in original chunk).
    Processing chunk ID: 34 for Landshut...
      Gi* analysis successful for chunk 34 (2211 points in original chunk).
    Processing chunk ID: 45 for Landshut...
      Gi* analysis successful for chunk 45 (1990 points in original chunk).
    Processing chunk ID: 56 for Landshut...
      Gi* analysis successful for chunk 56 (2089 points in original chunk).
    Processing chunk ID: 67 for Landshut...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Warning: Weight matrix for buffered chunk 67 is not fully connected (2 components).
      Gi* analysis successful for chunk 67 (1432 points in original chunk).
    Processing chunk ID: 68 for Landshut...
      Gi* analysis successful for chunk 68 (2245 points in original chunk).
    Processing chunk ID: 79 for Landshut...
      Gi* analysis successful for chunk 79 (2224 points in original chunk).
    Processing chunk ID: 90 for Landshut...
      Gi* analysis successful for chunk 90 (2264 points in original chunk).
    Processing chunk ID: 78 for Landshut...
      Gi* analysis successful for chunk 78 (641 points in original chunk).
    Processing chunk ID: 89 for Landshut...
      Gi* analysis successful for chunk 89 (1942 points in original chunk).
    Processing chunk ID: 77 for Landshut...
      Warning: Weight matrix for buffered chunk 77 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 77 (11 points in original chunk).
    Processing chunk ID: 88 for Landshut...
      Warning: Weight matrix for buffered chunk 88 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 88 (202 points in original chunk).
    Processing chunk ID: 55 for Landshut...
      Gi* analysis successful for chunk 55 (18 points in original chunk).
    Processing chunk ID: 44 for Landshut...
      Gi* analysis successful for chunk 44 (3 points in original chunk).
    Processing chunk ID: 33 for Landshut...
      Gi* analysis successful for chunk 33 (612 points in original chunk).
    Processing chunk ID: 22 for Landshut...
      Gi* analysis successful for chunk 22 (1048 points in original chunk).
    Processing chunk ID: 11 for Landshut...
      Gi* analysis successful for chunk 11 (962 points in original chunk).
    Processing chunk ID: 0 for Landshut...
      Gi* analysis successful for chunk 0 (1224 points in original chunk).
    Processing chunk ID: 122 for Landshut...
      Gi* analysis successful for chunk 122 (907 points in original chunk).
    Processing chunk ID: 133 for Landshut...
      Gi* analysis successful for chunk 133 (118 points in original chunk).
    Processing chunk ID: 111 for Landshut...
      Gi* analysis successful for chunk 111 (1618 points in original chunk).
    Processing chunk ID: 99 for Landshut...
      Gi* analysis successful for chunk 99 (189 points in original chunk).
    Processing chunk ID: 100 for Landshut...
      Gi* analysis successful for chunk 100 (2119 points in original chunk).
    Processing chunk ID: 101 for Landshut...
      Gi* analysis successful for chunk 101 (2254 points in original chunk).
    Processing chunk ID: 102 for Landshut...
      Gi* analysis successful for chunk 102 (2209 points in original chunk).
    Processing chunk ID: 113 for Landshut...
      Gi* analysis successful for chunk 113 (2212 points in original chunk).
    Processing chunk ID: 112 for Landshut...
      Gi* analysis successful for chunk 112 (2253 points in original chunk).
    Processing chunk ID: 123 for Landshut...
      Gi* analysis successful for chunk 123 (2287 points in original chunk).
    Processing chunk ID: 134 for Landshut...
      Gi* analysis successful for chunk 134 (1283 points in original chunk).
    Processing chunk ID: 124 for Landshut...
      Gi* analysis successful for chunk 124 (2238 points in original chunk).
    Processing chunk ID: 135 for Landshut...
      Gi* analysis successful for chunk 135 (1774 points in original chunk).
    Processing chunk ID: 146 for Landshut...
      Gi* analysis successful for chunk 146 (1414 points in original chunk).
    Processing chunk ID: 114 for Landshut...
      Gi* analysis successful for chunk 114 (2220 points in original chunk).
    Processing chunk ID: 125 for Landshut...
      Gi* analysis successful for chunk 125 (2251 points in original chunk).
    Processing chunk ID: 136 for Landshut...
      Gi* analysis successful for chunk 136 (2234 points in original chunk).
    Processing chunk ID: 147 for Landshut...
      Gi* analysis successful for chunk 147 (2216 points in original chunk).
    Processing chunk ID: 148 for Landshut...
      Gi* analysis successful for chunk 148 (2233 points in original chunk).
    Processing chunk ID: 137 for Landshut...
      Gi* analysis successful for chunk 137 (2236 points in original chunk).
    Processing chunk ID: 126 for Landshut...
      Gi* analysis successful for chunk 126 (1873 points in original chunk).
    Processing chunk ID: 138 for Landshut...
      Gi* analysis successful for chunk 138 (1998 points in original chunk).
    Processing chunk ID: 149 for Landshut...
      Gi* analysis successful for chunk 149 (2206 points in original chunk).
    Processing chunk ID: 127 for Landshut...
      Warning: Weight matrix for buffered chunk 127 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 127 (144 points in original chunk).
    Processing chunk ID: 115 for Landshut...
      Gi* analysis successful for chunk 115 (635 points in original chunk).
    Processing chunk ID: 104 for Landshut...
      Gi* analysis successful for chunk 104 (2222 points in original chunk).
    Processing chunk ID: 103 for Landshut...
      Gi* analysis successful for chunk 103 (2212 points in original chunk).
    Processing chunk ID: 93 for Landshut...
      Gi* analysis successful for chunk 93 (2267 points in original chunk).
    Processing chunk ID: 94 for Landshut...
      Gi* analysis successful for chunk 94 (2211 points in original chunk).
    Processing chunk ID: 105 for Landshut...
      Gi* analysis successful for chunk 105 (765 points in original chunk).
    Processing chunk ID: 95 for Landshut...
      Gi* analysis successful for chunk 95 (1087 points in original chunk).
    Processing chunk ID: 139 for Landshut...
      Gi* analysis successful for chunk 139 (69 points in original chunk).
    Processing chunk ID: 150 for Landshut...
      Gi* analysis successful for chunk 150 (1289 points in original chunk).
    Processing chunk ID: 160 for Landshut...
      Gi* analysis successful for chunk 160 (2244 points in original chunk).
    Processing chunk ID: 161 for Landshut...
      Gi* analysis successful for chunk 161 (2209 points in original chunk).
    Processing chunk ID: 171 for Landshut...
      Gi* analysis successful for chunk 171 (2207 points in original chunk).
    Processing chunk ID: 172 for Landshut...
      Gi* analysis successful for chunk 172 (2198 points in original chunk).
    Processing chunk ID: 173 for Landshut...
      Gi* analysis successful for chunk 173 (2262 points in original chunk).
    Processing chunk ID: 162 for Landshut...
      Gi* analysis successful for chunk 162 (1335 points in original chunk).
    Processing chunk ID: 174 for Landshut...
      Gi* analysis successful for chunk 174 (1148 points in original chunk).
    Processing chunk ID: 163 for Landshut...
      Gi* analysis successful for chunk 163 (102 points in original chunk).
    Processing chunk ID: 184 for Landshut...
      Gi* analysis successful for chunk 184 (2250 points in original chunk).
    Processing chunk ID: 185 for Landshut...
      Gi* analysis successful for chunk 185 (2200 points in original chunk).
    Processing chunk ID: 186 for Landshut...
      Gi* analysis successful for chunk 186 (471 points in original chunk).
    Processing chunk ID: 196 for Landshut...
      Gi* analysis successful for chunk 196 (2243 points in original chunk).
    Processing chunk ID: 207 for Landshut...
      Gi* analysis successful for chunk 207 (1789 points in original chunk).
    Processing chunk ID: 195 for Landshut...
      Gi* analysis successful for chunk 195 (1596 points in original chunk).
    Processing chunk ID: 206 for Landshut...
      Gi* analysis successful for chunk 206 (37 points in original chunk).
    Processing chunk ID: 183 for Landshut...
      Gi* analysis successful for chunk 183 (2054 points in original chunk).
    Processing chunk ID: 194 for Landshut...
      Gi* analysis successful for chunk 194 (124 points in original chunk).
    Processing chunk ID: 182 for Landshut...
      Gi* analysis successful for chunk 182 (1589 points in original chunk).
    Processing chunk ID: 193 for Landshut...
      Gi* analysis successful for chunk 193 (37 points in original chunk).
    Processing chunk ID: 170 for Landshut...
      Gi* analysis successful for chunk 170 (1070 points in original chunk).
    Processing chunk ID: 181 for Landshut...
      Gi* analysis successful for chunk 181 (11 points in original chunk).
    Processing chunk ID: 159 for Landshut...
      Gi* analysis successful for chunk 159 (1837 points in original chunk).
    Processing chunk ID: 158 for Landshut...
      Gi* analysis successful for chunk 158 (1730 points in original chunk).
    Processing chunk ID: 168 for Landshut...
      Gi* analysis successful for chunk 168 (217 points in original chunk).
    Processing chunk ID: 157 for Landshut...
      Gi* analysis successful for chunk 157 (1885 points in original chunk).
    Processing chunk ID: 156 for Landshut...
      Gi* analysis successful for chunk 156 (342 points in original chunk).
    Processing chunk ID: 167 for Landshut...
      Gi* analysis successful for chunk 167 (9 points in original chunk).
    Processing chunk ID: 219 for Landshut...
      Gi* analysis successful for chunk 219 (82 points in original chunk).
    Processing chunk ID: 218 for Landshut...
      Gi* analysis successful for chunk 218 (23 points in original chunk).
  Combined Gi* results for all chunks in Landshut.

✨ Processing chunks for city: Munich...
  Found 367 chunks for Munich.
    Processing chunk ID: 555 for Munich...
      Warning: Weight matrix for buffered chunk 555 is not fully connected (3 components).
      Gi* analysis successful for chunk 555 (136 points in original chunk).
    Processing chunk ID: 458 for Munich...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 458 (357 points in original chunk).
    Processing chunk ID: 437 for Munich...
      Gi* analysis successful for chunk 437 (1545 points in original chunk).
    Processing chunk ID: 436 for Munich...
      Gi* analysis successful for chunk 436 (875 points in original chunk).
    Processing chunk ID: 457 for Munich...
      Gi* analysis successful for chunk 457 (66 points in original chunk).
    Processing chunk ID: 475 for Munich...
      Gi* analysis successful for chunk 475 (626 points in original chunk).
    Processing chunk ID: 517 for Munich...
      Gi* analysis successful for chunk 517 (589 points in original chunk).
    Processing chunk ID: 516 for Munich...
      Gi* analysis successful for chunk 516 (426 points in original chunk).
    Processing chunk ID: 496 for Munich...
      Gi* analysis successful for chunk 496 (841 points in original chunk).
    Processing chunk ID: 495 for Munich...
      Gi* analysis successful for chunk 495 (1120 points in original chunk).
    Processing chunk ID: 494 for Munich...
      Gi* analysis successful for chunk 494 (764 points in original chunk).
    Processing chunk ID: 534 for Munich...
      Warning: Weight matrix for buffered chunk 534 is not fully connected (4 components).
      Gi* analysis successful for chunk 534 (239 points in original chunk).
    Processing chunk ID: 513 for Munich...

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 4 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)
/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 3 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Warning: Weight matrix for buffered chunk 513 is not fully connected (3 components).
      Gi* analysis successful for chunk 513 (484 points in original chunk).
    Processing chunk ID: 492 for Munich...
      Gi* analysis successful for chunk 492 (968 points in original chunk).
    Processing chunk ID: 493 for Munich...
      Gi* analysis successful for chunk 493 (694 points in original chunk).
    Processing chunk ID: 473 for Munich...
      Gi* analysis successful for chunk 473 (1144 points in original chunk).
    Processing chunk ID: 472 for Munich...
      Gi* analysis successful for chunk 472 (1110 points in original chunk).
    Processing chunk ID: 471 for Munich...
      Gi* analysis successful for chunk 471 (1100 points in original chunk).
    Processing chunk ID: 451 for Munich...
      Gi* analysis successful for chunk 451 (1148 points in original chunk).
    Processing chunk ID: 450 for Munich...
      Gi* analysis successful for chunk 450 (1128 points in original chunk).
    Processing chunk ID: 452 for Munich...
      Gi* analysis successful for chunk 452 (1173 points in original chunk).
    Processing chunk ID: 453 for Munich...
      Gi* analysis successful for chunk 453 (1059 points in original chunk).
    Processing chunk ID: 474 for Munich...
      Gi* analysis successful for chunk 474 (1122 points in original chunk).
    Processing chunk ID: 454 for Munich...
      Gi* analysis successful for chunk 454 (2 points in original chunk).
    Processing chunk ID: 432 for Munich...
      Gi* analysis successful for chunk 432 (985 points in original chunk).
    Processing chunk ID: 433 for Munich...
      Gi* analysis successful for chunk 433 (77 points in original chunk).
    Processing chunk ID: 411 for Munich...
      Gi* analysis successful for chunk 411 (1119 points in original chunk).
    Processing chunk ID: 412 for Munich...
      Gi* analysis successful for chunk 412 (986 points in original chunk).
    Processing chunk ID: 391 for Munich...
      Gi* analysis successful for chunk 391 (1150 points in original chunk).
    Processing chunk ID: 390 for Munich...
      Gi* analysis successful for chunk 390 (1155 points in original chunk).
    Processing chunk ID: 389 for Munich...
      Gi* analysis successful for chunk 389 (1171 points in original chunk).
    Processing chunk ID: 410 for Munich...
      Gi* analysis successful for chunk 410 (1138 points in original chunk).
    Processing chunk ID: 431 for Munich...
      Gi* analysis successful for chunk 431 (1135 points in original chunk).
    Processing chunk ID: 430 for Munich...
      Gi* analysis successful for chunk 430 (1111 points in original chunk).
    Processing chunk ID: 409 for Munich...
      Gi* analysis successful for chunk 409 (1113 points in original chunk).
    Processing chunk ID: 429 for Munich...
      Gi* analysis successful for chunk 429 (1098 points in original chunk).
    Processing chunk ID: 408 for Munich...
      Gi* analysis successful for chunk 408 (1097 points in original chunk).
    Processing chunk ID: 387 for Munich...
      Gi* analysis successful for chunk 387 (1129 points in original chunk).
    Processing chunk ID: 388 for Munich...
      Gi* analysis successful for chunk 388 (1146 points in original chunk).
    Processing chunk ID: 368 for Munich...
      Gi* analysis successful for chunk 368 (1148 points in original chunk).
    Processing chunk ID: 367 for Munich...
      Gi* analysis successful for chunk 367 (1112 points in original chunk).
    Processing chunk ID: 366 for Munich...
      Gi* analysis successful for chunk 366 (1097 points in original chunk).
    Processing chunk ID: 346 for Munich...
      Gi* analysis successful for chunk 346 (1110 points in original chunk).
    Processing chunk ID: 345 for Munich...
      Gi* analysis successful for chunk 345 (1098 points in original chunk).
    Processing chunk ID: 324 for Munich...
      Gi* analysis successful for chunk 324 (1127 points in original chunk).
    Processing chunk ID: 325 for Munich...
      Gi* analysis successful for chunk 325 (1146 points in original chunk).
    Processing chunk ID: 347 for Munich...
      Gi* analysis successful for chunk 347 (1139 points in original chunk).
    Processing chunk ID: 326 for Munich...
      Gi* analysis successful for chunk 326 (1179 points in original chunk).
    Processing chunk ID: 327 for Munich...
      Gi* analysis successful for chunk 327 (1158 points in original chunk).
    Processing chunk ID: 348 for Munich...
      Gi* analysis successful for chunk 348 (1129 points in original chunk).
    Processing chunk ID: 369 for Munich...
      Gi* analysis successful for chunk 369 (1111 points in original chunk).
    Processing chunk ID: 370 for Munich...
      Gi* analysis successful for chunk 370 (1102 points in original chunk).
    Processing chunk ID: 349 for Munich...
      Gi* analysis successful for chunk 349 (1112 points in original chunk).
    Processing chunk ID: 328 for Munich...
      Gi* analysis successful for chunk 328 (1143 points in original chunk).
    Processing chunk ID: 329 for Munich...
      Gi* analysis successful for chunk 329 (1188 points in original chunk).
    Processing chunk ID: 350 for Munich...
      Gi* analysis successful for chunk 350 (1157 points in original chunk).
    Processing chunk ID: 371 for Munich...
      Gi* analysis successful for chunk 371 (1154 points in original chunk).
    Processing chunk ID: 351 for Munich...
      Gi* analysis successful for chunk 351 (1117 points in original chunk).
    Processing chunk ID: 330 for Munich...
      Gi* analysis successful for chunk 330 (1143 points in original chunk).
    Processing chunk ID: 372 for Munich...
      Gi* analysis successful for chunk 372 (1127 points in original chunk).
    Processing chunk ID: 393 for Munich...
      Gi* analysis successful for chunk 393 (982 points in original chunk).
    Processing chunk ID: 392 for Munich...
      Gi* analysis successful for chunk 392 (1188 points in original chunk).
    Processing chunk ID: 413 for Munich...
      Gi* analysis successful for chunk 413 (1147 points in original chunk).
    Processing chunk ID: 434 for Munich...
      Gi* analysis successful for chunk 434 (137 points in original chunk).
    Processing chunk ID: 414 for Munich...
      Gi* analysis successful for chunk 414 (1119 points in original chunk).
    Processing chunk ID: 435 for Munich...
      Gi* analysis successful for chunk 435 (476 points in original chunk).
    Processing chunk ID: 394 for Munich...
      Gi* analysis successful for chunk 394 (1130 points in original chunk).
    Processing chunk ID: 415 for Munich...
      Gi* analysis successful for chunk 415 (1108 points in original chunk).
    Processing chunk ID: 416 for Munich...
      Gi* analysis successful for chunk 416 (1393 points in original chunk).
    Processing chunk ID: 395 for Munich...
      Gi* analysis successful for chunk 395 (1107 points in original chunk).
    Processing chunk ID: 374 for Munich...
      Gi* analysis successful for chunk 374 (245 points in original chunk).
    Processing chunk ID: 353 for Munich...
      Gi* analysis successful for chunk 353 (756 points in original chunk).
    Processing chunk ID: 373 for Munich...
      Gi* analysis successful for chunk 373 (1101 points in original chunk).
    Processing chunk ID: 352 for Munich...
      Gi* analysis successful for chunk 352 (1103 points in original chunk).
    Processing chunk ID: 331 for Munich...
      Gi* analysis successful for chunk 331 (1131 points in original chunk).
    Processing chunk ID: 332 for Munich...
      Gi* analysis successful for chunk 332 (1198 points in original chunk).
    Processing chunk ID: 354 for Munich...
      Warning: Weight matrix for buffered chunk 354 is not fully connected (2 components).

/usr/local/lib/python3.11/dist-packages/libpysal/weights/distance.py:153: UserWarning: The weights matrix is not fully connected:
 There are 2 disconnected components.
  W.__init__(self, neighbors, id_order=ids, **kwargs)

      Gi* analysis successful for chunk 354 (349 points in original chunk).
    Processing chunk ID: 333 for Munich...
      Gi* analysis successful for chunk 333 (678 points in original chunk).
    Processing chunk ID: 396 for Munich...
      Gi* analysis successful for chunk 396 (1204 points in original chunk).
    Processing chunk ID: 375 for Munich...
      Gi* analysis successful for chunk 375 (6 points in original chunk).
    Processing chunk ID: 417 for Munich...
      Gi* analysis successful for chunk 417 (1731 points in original chunk).
    Processing chunk ID: 438 for Munich...
      Gi* analysis successful for chunk 438 (605 points in original chunk).
    Processing chunk ID: 312 for Munich...
      Gi* analysis successful for chunk 312 (543 points in original chunk).
    Processing chunk ID: 311 for Munich...
      Gi* analysis successful for chunk 311 (1156 points in original chunk).
    Processing chunk ID: 291 for Munich...
      Gi* analysis successful for chunk 291 (605 points in original chunk).
    Processing chunk ID: 290 for Munich...
      Gi* analysis successful for chunk 290 (1157 points in original chunk).
    Processing chunk ID: 271 for Munich...
      Gi* analysis successful for chunk 271 (148 points in original chunk).
    Processing chunk ID: 250 for Munich...
      Gi* analysis successful for chunk 250 (1093 points in original chunk).
    Processing chunk ID: 270 for Munich...
      Gi* analysis successful for chunk 270 (1001 points in original chunk).
    Processing chunk ID: 249 for Munich...
      Gi* analysis successful for chunk 249 (1089 points in original chunk).
    Processing chunk ID: 269 for Munich...
      Gi* analysis successful for chunk 269 (1196 points in original chunk).
    Processing chunk ID: 248 for Munich...
      Gi* analysis successful for chunk 248 (1167 points in original chunk).
    Processing chunk ID: 227 for Munich...
      Gi* analysis successful for chunk 227 (1163 points in original chunk).
    Processing chunk ID: 228 for Munich...
      Gi* analysis successful for chunk 228 (1089 points in original chunk).
    Processing chunk ID: 229 for Munich...
      Gi* analysis successful for chunk 229 (1109 points in original chunk).
    Processing chunk ID: 230 for Munich...
      Gi* analysis successful for chunk 230 (683 points in original chunk).
    Processing chunk ID: 251 for Munich...
      Gi* analysis successful for chunk 251 (258 points in original chunk).
    Processing chunk ID: 208 for Munich...
      Gi* analysis successful for chunk 208 (731 points in original chunk).
    Processing chunk ID: 209 for Munich...
      Gi* analysis successful for chunk 209 (401 points in original chunk).
    Processing chunk ID: 207 for Munich...
      Gi* analysis successful for chunk 207 (870 points in original chunk).
    Processing chunk ID: 206 for Munich...
      Gi* analysis successful for chunk 206 (1104 points in original chunk).
    Processing chunk ID: 185 for Munich...
      Gi* analysis successful for chunk 185 (602 points in original chunk).
    Processing chunk ID: 57 for Munich...
      Gi* analysis successful for chunk 57 (239 points in original chunk).
    Processing chunk ID: 78 for Munich...
      Gi* analysis successful for chunk 78 (473 points in original chunk).
    Processing chunk ID: 99 for Munich...
      Gi* analysis successful for chunk 99 (711 points in original chunk).
    Processing chunk ID: 120 for Munich...
      Gi* analysis successful for chunk 120 (974 points in original chunk).
    Processing chunk ID: 119 for Munich...
      Gi* analysis successful for chunk 119 (1133 points in original chunk).
    Processing chunk ID: 98 for Munich...
      Gi* analysis successful for chunk 98 (1123 points in original chunk).
    Processing chunk ID: 118 for Munich...
      Gi* analysis successful for chunk 118 (1121 points in original chunk).
    Processing chunk ID: 97 for Munich...
      Gi* analysis successful for chunk 97 (1109 points in original chunk).
    Processing chunk ID: 77 for Munich...
      Gi* analysis successful for chunk 77 (1162 points in original chunk).
    Processing chunk ID: 76 for Munich...
      Gi* analysis successful for chunk 76 (1147 points in original chunk).
    Processing chunk ID: 55 for Munich...
      Gi* analysis successful for chunk 55 (857 points in original chunk).
    Processing chunk ID: 56 for Munich...
      Gi* analysis successful for chunk 56 (1098 points in original chunk).
    Processing chunk ID: 35 for Munich...
      Gi* analysis successful for chunk 35 (19 points in original chunk).
    Processing chunk ID: 11 for Munich...
      Gi* analysis successful for chunk 11 (627 points in original chunk).
    Processing chunk ID: 10 for Munich...
      Gi* analysis successful for chunk 10 (686 points in original chunk).
    Processing chunk ID: 9 for Munich...
      Gi* analysis successful for chunk 9 (3 points in original chunk).
    Processing chunk ID: 30 for Munich...
      Gi* analysis successful for chunk 30 (290 points in original chunk).
    Processing chunk ID: 51 for Munich...
      Gi* analysis successful for chunk 51 (1065 points in original chunk).
    Processing chunk ID: 50 for Munich...
      Gi* analysis successful for chunk 50 (794 points in original chunk).
    Processing chunk ID: 72 for Munich...
      Gi* analysis successful for chunk 72 (1164 points in original chunk).
    Processing chunk ID: 31 for Munich...
      Gi* analysis successful for chunk 31 (1108 points in original chunk).
    Processing chunk ID: 52 for Munich...
      Gi* analysis successful for chunk 52 (1113 points in original chunk).
    Processing chunk ID: 73 for Munich...
      Gi* analysis successful for chunk 73 (1149 points in original chunk).
    Processing chunk ID: 53 for Munich...
      Gi* analysis successful for chunk 53 (1104 points in original chunk).
    Processing chunk ID: 32 for Munich...
      Gi* analysis successful for chunk 32 (1109 points in original chunk).
    Processing chunk ID: 33 for Munich...
      Gi* analysis successful for chunk 33 (820 points in original chunk).
    Processing chunk ID: 12 for Munich...
      Gi* analysis successful for chunk 12 (328 points in original chunk).
    Processing chunk ID: 54 for Munich...
      Gi* analysis successful for chunk 54 (1160 points in original chunk).
    Processing chunk ID: 74 for Munich...
      Gi* analysis successful for chunk 74 (1139 points in original chunk).
    Processing chunk ID: 95 for Munich...
      Gi* analysis successful for chunk 95 (1103 points in original chunk).
    Processing chunk ID: 96 for Munich...
      Gi* analysis successful for chunk 96 (1149 points in original chunk).
    Processing chunk ID: 75 for Munich...
      Gi* analysis successful for chunk 75 (1179 points in original chunk).
    Processing chunk ID: 117 for Munich...
      Gi* analysis successful for chunk 117 (1158 points in original chunk).
    Processing chunk ID: 116 for Munich...
      Gi* analysis successful for chunk 116 (1106 points in original chunk).
    Processing chunk ID: 115 for Munich...
      Gi* analysis successful for chunk 115 (1116 points in original chunk).
    Processing chunk ID: 94 for Munich...
      Gi* analysis successful for chunk 94 (1116 points in original chunk).
    Processing chunk ID: 93 for Munich...
      Gi* analysis successful for chunk 93 (1132 points in original chunk).
    Processing chunk ID: 114 for Munich...
      Gi* analysis successful for chunk 114 (1129 points in original chunk).
    Processing chunk ID: 135 for Munich...
      Gi* analysis successful for chunk 135 (1161 points in original chunk).
    Processing chunk ID: 136 for Munich...
      Gi* analysis successful for chunk 136 (1146 points in original chunk).
    Processing chunk ID: 137 for Munich...
      Gi* analysis successful for chunk 137 (1132 points in original chunk).
    Processing chunk ID: 157 for Munich...
      Gi* analysis successful for chunk 157 (1113 points in original chunk).
    Processing chunk ID: 158 for Munich...
      Gi* analysis successful for chunk 158 (1098 points in original chunk).
    Processing chunk ID: 179 for Munich...
      Gi* analysis successful for chunk 179 (1101 points in original chunk).
    Processing chunk ID: 178 for Munich...
      Gi* analysis successful for chunk 178 (1109 points in original chunk).
    Processing chunk ID: 156 for Munich...
      Gi* analysis successful for chunk 156 (1132 points in original chunk).
    Processing chunk ID: 177 for Munich...
      Gi* analysis successful for chunk 177 (1129 points in original chunk).
    Processing chunk ID: 198 for Munich...
      Gi* analysis successful for chunk 198 (1162 points in original chunk).
    Processing chunk ID: 199 for Munich...
      Gi* analysis successful for chunk 199 (1145 points in original chunk).
    Processing chunk ID: 219 for Munich...
      Gi* analysis successful for chunk 219 (1106 points in original chunk).
    Processing chunk ID: 220 for Munich...
      Gi* analysis successful for chunk 220 (1109 points in original chunk).
    Processing chunk ID: 221 for Munich...
      Gi* analysis successful for chunk 221 (1131 points in original chunk).
    Processing chunk ID: 200 for Munich...
      Gi* analysis successful for chunk 200 (1146 points in original chunk).
    Processing chunk ID: 180 for Munich...
      Gi* analysis successful for chunk 180 (1163 points in original chunk).
    Processing chunk ID: 201 for Munich...
      Gi* analysis successful for chunk 201 (1191 points in original chunk).
    Processing chunk ID: 222 for Munich...
      Gi* analysis successful for chunk 222 (1115 points in original chunk).
    Processing chunk ID: 223 for Munich...
      Gi* analysis successful for chunk 223 (1116 points in original chunk).
    Processing chunk ID: 202 for Munich...
      Gi* analysis successful for chunk 202 (1141 points in original chunk).
    Processing chunk ID: 181 for Munich...
      Gi* analysis successful for chunk 181 (1112 points in original chunk).
    Processing chunk ID: 160 for Munich...
      Gi* analysis successful for chunk 160 (1118 points in original chunk).
    Processing chunk ID: 159 for Munich...
      Gi* analysis successful for chunk 159 (1152 points in original chunk).
    Processing chunk ID: 139 for Munich...
      Gi* analysis successful for chunk 139 (1157 points in original chunk).
    Processing chunk ID: 138 for Munich...
      Gi* analysis successful for chunk 138 (1181 points in original chunk).
    Processing chunk ID: 140 for Munich...
      Gi* analysis successful for chunk 140 (1153 points in original chunk).
    Processing chunk ID: 161 for Munich...
      Gi* analysis successful for chunk 161 (1123 points in original chunk).
    Processing chunk ID: 182 for Munich...
      Gi* analysis successful for chunk 182 (1128 points in original chunk).
    Processing chunk ID: 162 for Munich...
      Gi* analysis successful for chunk 162 (1151 points in original chunk).
    Processing chunk ID: 141 for Munich...
      Gi* analysis successful for chunk 141 (1181 points in original chunk).
    Processing chunk ID: 142 for Munich...
      Gi* analysis successful for chunk 142 (116 points in original chunk).
    Processing chunk ID: 163 for Munich...
      Gi* analysis successful for chunk 163 (951 points in original chunk).
    Processing chunk ID: 164 for Munich...
      Gi* analysis successful for chunk 164 (123 points in original chunk).
    Processing chunk ID: 183 for Munich...
      Gi* analysis successful for chunk 183 (1146 points in original chunk).
    Processing chunk ID: 204 for Munich...
      Gi* analysis successful for chunk 204 (1174 points in original chunk).
    Processing chunk ID: 184 for Munich...
      Gi* analysis successful for chunk 184 (1113 points in original chunk).
    Processing chunk ID: 205 for Munich...
      Gi* analysis successful for chunk 205 (1137 points in original chunk).
    Processing chunk ID: 226 for Munich...
      Gi* analysis successful for chunk 226 (1104 points in original chunk).
    Processing chunk ID: 225 for Munich...
      Gi* analysis successful for chunk 225 (1124 points in original chunk).
    Processing chunk ID: 224 for Munich...
      Gi* analysis successful for chunk 224 (1151 points in original chunk).
    Processing chunk ID: 203 for Munich...
      Gi* analysis successful for chunk 203 (1171 points in original chunk).
    Processing chunk ID: 244 for Munich...
      Gi* analysis successful for chunk 244 (1115 points in original chunk).
    Processing chunk ID: 245 for Munich...
      Gi* analysis successful for chunk 245 (1164 points in original chunk).
    Processing chunk ID: 265 for Munich...
      Gi* analysis successful for chunk 265 (1153 points in original chunk).
    Processing chunk ID: 286 for Munich...
      Gi* analysis successful for chunk 286 (1110 points in original chunk).
    Processing chunk ID: 266 for Munich...
      Gi* analysis successful for chunk 266 (1194 points in original chunk).
    Processing chunk ID: 287 for Munich...
      Gi* analysis successful for chunk 287 (1150 points in original chunk).
    Processing chunk ID: 288 for Munich...
      Gi* analysis successful for chunk 288 (1117 points in original chunk).
    Processing chunk ID: 267 for Munich...
      Gi* analysis successful for chunk 267 (1156 points in original chunk).
    Processing chunk ID: 246 for Munich...
      Gi* analysis successful for chunk 246 (1124 points in original chunk).
    Processing chunk ID: 247 for Munich...
      Gi* analysis successful for chunk 247 (1102 points in original chunk).
    Processing chunk ID: 268 for Munich...
      Gi* analysis successful for chunk 268 (1141 points in original chunk).
    Processing chunk ID: 289 for Munich...
      Gi* analysis successful for chunk 289 (1103 points in original chunk).
    Processing chunk ID: 309 for Munich...
      Gi* analysis successful for chunk 309 (1116 points in original chunk).
    Processing chunk ID: 310 for Munich...
      Gi* analysis successful for chunk 310 (1107 points in original chunk).
    Processing chunk ID: 308 for Munich...
      Gi* analysis successful for chunk 308 (1154 points in original chunk).
    Processing chunk ID: 307 for Munich...
      Gi* analysis successful for chunk 307 (1111 points in original chunk).
    Processing chunk ID: 306 for Munich...
      Gi* analysis successful for chunk 306 (1122 points in original chunk).
    Processing chunk ID: 305 for Munich...
      Gi* analysis successful for chunk 305 (1140 points in original chunk).
    Processing chunk ID: 285 for Munich...
      Gi* analysis successful for chunk 285 (1125 points in original chunk).
    Processing chunk ID: 284 for Munich...
      Gi* analysis successful for chunk 284 (1135 points in original chunk).
    Processing chunk ID: 264 for Munich...
      Gi* analysis successful for chunk 264 (1155 points in original chunk).
    Processing chunk ID: 243 for Munich...
      Gi* analysis successful for chunk 243 (1113 points in original chunk).
    Processing chunk ID: 242 for Munich...
      Gi* analysis successful for chunk 242 (1140 points in original chunk).
    Processing chunk ID: 263 for Munich...
      Gi* analysis successful for chunk 263 (1170 points in original chunk).
    Processing chunk ID: 262 for Munich...
      Gi* analysis successful for chunk 262 (1149 points in original chunk).
    Processing chunk ID: 283 for Munich...
      Gi* analysis successful for chunk 283 (1118 points in original chunk).
    Processing chunk ID: 241 for Munich...
      Gi* analysis successful for chunk 241 (1114 points in original chunk).
    Processing chunk ID: 261 for Munich...
      Gi* analysis successful for chunk 261 (1130 points in original chunk).
    Processing chunk ID: 240 for Munich...
      Gi* analysis successful for chunk 240 (1094 points in original chunk).
    Processing chunk ID: 282 for Munich...
      Gi* analysis successful for chunk 282 (1097 points in original chunk).
    Processing chunk ID: 303 for Munich...
      Gi* analysis successful for chunk 303 (1094 points in original chunk).
    Processing chunk ID: 304 for Munich...
      Gi* analysis successful for chunk 304 (1108 points in original chunk).
    Processing chunk ID: 323 for Munich...
      Gi* analysis successful for chunk 323 (1178 points in original chunk).
    Processing chunk ID: 302 for Munich...
      Gi* analysis successful for chunk 302 (1149 points in original chunk).
    Processing chunk ID: 322 for Munich...
      Gi* analysis successful for chunk 322 (1133 points in original chunk).
    Processing chunk ID: 301 for Munich...
      Gi* analysis successful for chunk 301 (1105 points in original chunk).
    Processing chunk ID: 280 for Munich...
      Gi* analysis successful for chunk 280 (1106 points in original chunk).
    Processing chunk ID: 281 for Munich...
      Gi* analysis successful for chunk 281 (1143 points in original chunk).
    Processing chunk ID: 260 for Munich...
      Gi* analysis successful for chunk 260 (1188 points in original chunk).
    Processing chunk ID: 239 for Munich...
      Gi* analysis successful for chunk 239 (1146 points in original chunk).
    Processing chunk ID: 218 for Munich...
      Gi* analysis successful for chunk 218 (1138 points in original chunk).
    Processing chunk ID: 238 for Munich...
      Gi* analysis successful for chunk 238 (1100 points in original chunk).
    Processing chunk ID: 259 for Munich...
      Gi* analysis successful for chunk 259 (1137 points in original chunk).
    Processing chunk ID: 217 for Munich...
      Gi* analysis successful for chunk 217 (1100 points in original chunk).
    Processing chunk ID: 279 for Munich...
      Gi* analysis successful for chunk 279 (1106 points in original chunk).
    Processing chunk ID: 258 for Munich...
      Gi* analysis successful for chunk 258 (1139 points in original chunk).
    Processing chunk ID: 237 for Munich...
      Gi* analysis successful for chunk 237 (1103 points in original chunk).
    Processing chunk ID: 216 for Munich...
      Gi* analysis successful for chunk 216 (1123 points in original chunk).
    Processing chunk ID: 257 for Munich...
      Gi* analysis successful for chunk 257 (1177 points in original chunk).
    Processing chunk ID: 236 for Munich...
      Gi* analysis successful for chunk 236 (1137 points in original chunk).
    Processing chunk ID: 215 for Munich...
      Gi* analysis successful for chunk 215 (1115 points in original chunk).
    Processing chunk ID: 278 for Munich...
      Gi* analysis successful for chunk 278 (1144 points in original chunk).
    Processing chunk ID: 299 for Munich...
      Gi* analysis successful for chunk 299 (1143 points in original chunk).
    Processing chunk ID: 300 for Munich...
      Gi* analysis successful for chunk 300 (1112 points in original chunk).
    Processing chunk ID: 321 for Munich...
      Gi* analysis successful for chunk 321 (1133 points in original chunk).
    Processing chunk ID: 342 for Munich...
      Gi* analysis successful for chunk 342 (1109 points in original chunk).
    Processing chunk ID: 320 for Munich...
      Gi* analysis successful for chunk 320 (1173 points in original chunk).
    Processing chunk ID: 341 for Munich...
      Gi* analysis successful for chunk 341 (1138 points in original chunk).
    Processing chunk ID: 340 for Munich...
      Gi* analysis successful for chunk 340 (1123 points in original chunk).
    Processing chunk ID: 319 for Munich...
      Gi* analysis successful for chunk 319 (1159 points in original chunk).
    Processing chunk ID: 298 for Munich...
      Gi* analysis successful for chunk 298 (1122 points in original chunk).
    Processing chunk ID: 277 for Munich...
      Gi* analysis successful for chunk 277 (1116 points in original chunk).
    Processing chunk ID: 297 for Munich...

Variante mit chunks hat funktioniert, dauert aber ca 40 Minuten

In [ ]:
# Definieren Sie den Ordner in Google Drive, in dem die Ergebnisse gespeichert werden sollen
# Passen Sie den Pfad bei Bedarf an
output_folder_gi_results = "/content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/"
os.makedirs(output_folder_gi_results, exist_ok=True) # Erstellt den Ordner, falls er nicht existiert

print(f"Speichere Gi* Analyse-Ergebnisse (chunked) im Ordner: {output_folder_gi_results}")

# Schleife über das Dictionary der Gi* Ergebnisse pro Stadt
for city, gdf_gi_results in city_gi_results_chunked.items():
    if gdf_gi_results is not None and not gdf_gi_results.empty:
        # Erstellen Sie einen Dateinamen basierend auf dem Stadtnamen
        # Verwenden Sie ein Format, das GeoPandas schreiben kann, z.B. GeoJSON
        file_name = f"{city.replace(' ', '_')}_gi_results_chunked.geojson"
        file_path = os.path.join(output_folder_gi_results, file_name)

        try:
            # Speichern Sie den GeoDataFrame als GeoJSON-Datei
            gdf_gi_results.to_file(file_path, driver='GeoJSON')
            print(f"  Ergebnisse für {city} gespeichert unter: {file_path} ({len(gdf_gi_results)} Zeilen)")
        except Exception as e:
            print(f"  Fehler beim Speichern der Ergebnisse für {city}: {e}")
    else:
        print(f"  Keine Gi* Ergebnisse für {city} zum Speichern verfügbar.")

print("\nSpeichern der Gi* Analyse-Ergebnisse (chunked) abgeschlossen.")

Speichere Gi* Analyse-Ergebnisse (chunked) im Ordner: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/
  Ergebnisse für Aschaffenburg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Aschaffenburg_gi_results_chunked.geojson (69388 Zeilen)
  Ergebnisse für Augsburg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Augsburg_gi_results_chunked.geojson (164416 Zeilen)
  Ergebnisse für Bamberg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Bamberg_gi_results_chunked.geojson (121600 Zeilen)
  Ergebnisse für Bayreuth gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Bayreuth_gi_results_chunked.geojson (149921 Zeilen)
  Ergebnisse für Erlangen gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Erlangen_gi_results_chunked.geojson (80701 Zeilen)
  Ergebnisse für Fürth gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Fürth_gi_results_chunked.geojson (60345 Zeilen)
  Ergebnisse für Ingolstadt gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Ingolstadt_gi_results_chunked.geojson (150375 Zeilen)
  Ergebnisse für Kempten (Allgäu) gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Kempten_(Allgäu)_gi_results_chunked.geojson (67439 Zeilen)
  Ergebnisse für Landshut gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Landshut_gi_results_chunked.geojson (146396 Zeilen)
  Ergebnisse für Munich gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Munich_gi_results_chunked.geojson (349953 Zeilen)
  Ergebnisse für Nuremberg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Nuremberg_gi_results_chunked.geojson (209685 Zeilen)
  Ergebnisse für Passau gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Passau_gi_results_chunked.geojson (77737 Zeilen)
  Ergebnisse für Regensburg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Regensburg_gi_results_chunked.geojson (172595 Zeilen)
  Ergebnisse für Rosenheim gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Rosenheim_gi_results_chunked.geojson (42315 Zeilen)
  Ergebnisse für Schweinfurt gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Schweinfurt_gi_results_chunked.geojson (39879 Zeilen)
  Ergebnisse für Würzburg gespeichert unter: /content/drive/MyDrive/Cold Spots Bayern/gi_results_chunked/Würzburg_gi_results_chunked.geojson (89247 Zeilen)

Speichern der Gi* Analyse-Ergebnisse (chunked) abgeschlossen.

In [ ]:
display(city_gi_results_chunked['Munich'][['avg_summer_LST_Celsius', 'Gi_Star', 'Gi_Star_p_value', 'Gi_Star_sig']].head())

         avg_summer_LST_Celsius   Gi_Star  Gi_Star_p_value        Gi_Star_sig
1010628               34.020015  0.001246            0.135  Nicht signifikant
1013385               32.094435  0.001203            0.003  Hot Spot (p<0.05)
1013386               32.066427  0.001203            0.003  Hot Spot (p<0.05)
1013387               31.919926  0.001203            0.003  Hot Spot (p<0.05)
1013388               31.930275  0.001203            0.003  Hot Spot (p<0.05)

# Weiterverarbeitung der Cold-Spot-Ergebnisse

Schritte und weitere Ziele:
- gdfs filtern nach ausschließlich Cold Spots jeder Stadt
- OSMnx Erreichbarkeitsanalysen
- Karte für jede Stadt, die Cold Spots genau und geometriegenau eingezeichnet hat, und die Einzugsgebiet eingezeichnet hat (vgl. cooler Stadtplan Münster https://geo.stadt-muenster.de/coolerstadtplan/)